import 'dart:typed_data';

import '../arena/arena_reader.dart';
import '../message/message_copy.dart';
import '../wire/pointer.dart';
import '../wire/wire_helpers.dart';
import 'list_reader.dart';

/// Base class for all generated struct readers.
///
/// Subclasses expose typed getters by calling the helper methods below.
/// The helpers handle bounds checking (field absent in older messages → default)
/// and XOR-based default masking as required by the Cap'n Proto spec.
abstract class StructReader {
  final RawStructReader _raw;

  StructReader(this._raw);

  /// Exposes the underlying raw reader so that group accessors generated by
  /// capnpc-dart can forward the same raw bytes to their own constructor.
  RawStructReader get raw => _raw;

  // ---- Data section helpers ----
  // [byteOffset] is the byte offset from the start of the data section.
  // [bitOffset] is the bit offset from the start of the data section.
  // Values are XOR'd with [defaultValue] per the Cap'n Proto default masking spec.

  bool getBoolField(int bitOffset, {bool defaultValue = false}) {
    if (bitOffset ~/ 64 >= _raw.dataWords) return defaultValue;
    final byteIndex = bitOffset ~/ 8;
    final bitMask = 1 << (bitOffset & 7);
    final absOffset = _raw.dataWordOffset * bytesPerWord + byteIndex;
    final storedBit =
        (readUint8(_raw.segment.data, absOffset) & bitMask) != 0;
    return storedBit ^ defaultValue;
  }

  int getUint8Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readUint8(
            _raw.segment.data, _raw.dataWordOffset * bytesPerWord + byteOffset) ^
        defaultValue;
  }

  int getUint16Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readUint16(
            _raw.segment.data, _raw.dataWordOffset * bytesPerWord + byteOffset) ^
        defaultValue;
  }

  int getUint32Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readUint32(
            _raw.segment.data, _raw.dataWordOffset * bytesPerWord + byteOffset) ^
        defaultValue;
  }

  int getUint64Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readUint64(
            _raw.segment.data, _raw.dataWordOffset * bytesPerWord + byteOffset) ^
        defaultValue;
  }

  int getInt8Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readInt8(
            _raw.segment.data, _raw.dataWordOffset * bytesPerWord + byteOffset) ^
        defaultValue;
  }

  int getInt16Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readInt16(
            _raw.segment.data, _raw.dataWordOffset * bytesPerWord + byteOffset) ^
        defaultValue;
  }

  int getInt32Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readInt32(
            _raw.segment.data, _raw.dataWordOffset * bytesPerWord + byteOffset) ^
        defaultValue;
  }

  int getInt64Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readInt64(
            _raw.segment.data, _raw.dataWordOffset * bytesPerWord + byteOffset) ^
        defaultValue;
  }

  double getFloat32Field(int byteOffset, {double defaultValue = 0.0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    final absOffset = _raw.dataWordOffset * bytesPerWord + byteOffset;
    if (defaultValue == 0.0) return readFloat32(_raw.segment.data, absOffset);
    final stored = readUint32(_raw.segment.data, absOffset);
    return reinterpretUint32AsFloat32(
        stored ^ reinterpretFloat32AsUint32(defaultValue));
  }

  double getFloat64Field(int byteOffset, {double defaultValue = 0.0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    final absOffset = _raw.dataWordOffset * bytesPerWord + byteOffset;
    if (defaultValue == 0.0) return readFloat64(_raw.segment.data, absOffset);
    final stored = readUint64(_raw.segment.data, absOffset);
    return reinterpretUint64AsFloat64(
        stored ^ reinterpretFloat64AsUint64(defaultValue));
  }

  // ---- Pointer section helpers ----

  /// Returns true if the pointer at [ptrIndex] is non-null.
  bool hasPointerField(int ptrIndex) {
    if (ptrIndex >= _raw.ptrWords) return false;
    final wordOffset = _raw.ptrWordOffset + ptrIndex;
    return WirePointer.decode(_raw.segment.data, wordOffset) is! NullPointer;
  }

  /// Reads a Text (UTF-8 string) from the pointer at [ptrIndex].
  /// Returns null if the pointer is null.
  String? getTextField(int ptrIndex) {
    if (ptrIndex >= _raw.ptrWords) return null;
    return _raw.arena
        .resolveTextAt(_raw.segment, _raw.ptrWordOffset + ptrIndex);
  }

  /// Reads a Data (raw bytes) field from the pointer at [ptrIndex].
  /// Returns null if the pointer is null.
  Uint8List? getDataField(int ptrIndex) {
    if (ptrIndex >= _raw.ptrWords) return null;
    return _raw.arena
        .resolveDataAt(_raw.segment, _raw.ptrWordOffset + ptrIndex);
  }

  /// Reads the AnyPointer at [ptrIndex], deep-copies the referenced struct
  /// into a new standalone message, and returns the serialized bytes.
  /// Returns null if the pointer is null.
  Uint8List? getAnyPointerAsMessageBytes(int ptrIndex) {
    if (ptrIndex >= _raw.ptrWords) return null;
    return copyAnyPointerToNewMessage(_raw, ptrIndex);
  }

  /// Reads a nested struct from the pointer at [ptrIndex].
  /// Returns null if the pointer is null.
  ///
  /// Uses a callback instead of [StructFactory] to avoid an import cycle
  /// between the layout and arena layers.
  R? getStructFieldWith<R extends StructReader>(
    int ptrIndex,
    R Function(RawStructReader) fromRaw,
  ) {
    if (ptrIndex >= _raw.ptrWords) return null;
    final wordOffset = _raw.ptrWordOffset + ptrIndex;
    final raw = _raw.arena
        .resolveOptionalStructAt(_raw.segment, wordOffset, _raw.nestingLimit);
    return raw == null ? null : fromRaw(raw);
  }

  // ---- List field helpers ----

  RawListReader? _resolveListField(int ptrIndex) {
    if (ptrIndex >= _raw.ptrWords) return null;
    return _raw.arena.resolveListAt(
        _raw.segment, _raw.ptrWordOffset + ptrIndex, _raw.nestingLimit);
  }

  ListReader<bool>? getBoolListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : BoolListReader(raw);
  }

  ListReader<int>? getInt8ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveIntListReader(raw, readInt8, 1);
  }

  ListReader<int>? getUint8ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveIntListReader(raw, readUint8, 1);
  }

  ListReader<int>? getInt16ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveIntListReader(raw, readInt16, 2);
  }

  ListReader<int>? getUint16ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveIntListReader(raw, readUint16, 2);
  }

  ListReader<int>? getInt32ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveIntListReader(raw, readInt32, 4);
  }

  ListReader<int>? getUint32ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveIntListReader(raw, readUint32, 4);
  }

  ListReader<int>? getInt64ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveIntListReader(raw, readInt64, 8);
  }

  ListReader<int>? getUint64ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveIntListReader(raw, readUint64, 8);
  }

  ListReader<double>? getFloat32ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveDoubleListReader(raw, readFloat32, 4);
  }

  ListReader<double>? getFloat64ListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : PrimitiveDoubleListReader(raw, readFloat64, 8);
  }

  ListReader<String?>? getTextListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : TextListReader(raw);
  }

  ListReader<Uint8List?>? getDataListField(int ptrIndex) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : DataListReader(raw);
  }

  /// Reads a composite struct list from the pointer at [ptrIndex].
  /// Returns null if the pointer is null.
  ListReader<R>? getStructListFieldWith<R>(
    int ptrIndex,
    R Function(RawStructReader) fromRaw,
  ) {
    final raw = _resolveListField(ptrIndex);
    return raw == null ? null : StructListReader<R>(raw, fromRaw);
  }
}
