import 'dart:typed_data';

import '../arena/arena_builder.dart';
import '../arena/arena_reader.dart' show ArenaReader, RawStructReader;
import '../message/message_copy.dart' show ensureSingleSegment;
import '../wire/pointer.dart' show ListElementSize, CapabilityPointer;
import '../wire/wire_helpers.dart';
import 'list_builder.dart';
import 'struct_reader.dart';

/// Base class for all generated struct builders.
///
/// Subclasses expose typed setters and init methods by calling the helpers
/// below. The helpers apply XOR-based default masking per the Cap'n Proto spec.
abstract class StructBuilder {
  final RawStructBuilder _raw;

  StructBuilder(this._raw);

  /// Exposes the underlying raw builder so that group accessors generated by
  /// capnpc-dart can forward the same raw bytes to their own constructor.
  RawStructBuilder get raw => _raw;

  /// Returns a read-only **live view** over this builder's data.
  ///
  /// The returned reader shares the same underlying buffer as the builder.
  /// Subsequent writes through the builder are immediately visible through
  /// the returned reader.
  ///
  /// If you need an immutable snapshot, serialize and deserialize the message:
  /// ```dart
  /// final snapshot = MessageReader.deserialize(builder.serialize());
  /// ```
  ///
  /// Generated subclasses override this to return the typed reader.
  StructReader asReader();

  // ---- Data section helpers ----
  // [byteOffset] is the byte offset from the start of the data section.
  // [bitOffset] is the bit offset from the start of the data section.
  // Values are XOR'd with [defaultValue] per the Cap'n Proto default masking spec.

  void setBoolField(int bitOffset, bool value, {bool defaultValue = false}) {
    final byteIndex = bitOffset ~/ 8;
    final bitMask = 1 << (bitOffset & 7);
    final absOffset = _raw.dataWordOffset * bytesPerWord + byteIndex;
    final current = readUint8(_raw.segment.data, absOffset);
    final stored = value ^ defaultValue;
    writeUint8(
      _raw.segment.data,
      absOffset,
      stored ? (current | bitMask) : (current & ~bitMask),
    );
  }

  void setUint8Field(int byteOffset, int value, {int defaultValue = 0}) {
    writeUint8(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, value ^ defaultValue);
  }

  void setUint16Field(int byteOffset, int value, {int defaultValue = 0}) {
    writeUint16(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, value ^ defaultValue);
  }

  void setUint32Field(int byteOffset, int value, {int defaultValue = 0}) {
    writeUint32(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, value ^ defaultValue);
  }

  void setUint64Field(int byteOffset, int value, {int defaultValue = 0}) {
    writeUint64(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, value ^ defaultValue);
  }

  void setInt8Field(int byteOffset, int value, {int defaultValue = 0}) {
    writeInt8(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, value ^ defaultValue);
  }

  void setInt16Field(int byteOffset, int value, {int defaultValue = 0}) {
    writeInt16(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, value ^ defaultValue);
  }

  void setInt32Field(int byteOffset, int value, {int defaultValue = 0}) {
    writeInt32(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, value ^ defaultValue);
  }

  void setInt64Field(int byteOffset, int value, {int defaultValue = 0}) {
    writeInt64(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, value ^ defaultValue);
  }

  void setFloat32Field(int byteOffset, double value,
      {double defaultValue = 0.0}) {
    final bits = reinterpretFloat32AsUint32(value) ^
        reinterpretFloat32AsUint32(defaultValue);
    writeUint32(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, bits);
  }

  void setFloat64Field(int byteOffset, double value,
      {double defaultValue = 0.0}) {
    final bits = reinterpretFloat64AsUint64(value) ^
        reinterpretFloat64AsUint64(defaultValue);
    writeUint64(_raw.segment.data,
        _raw.dataWordOffset * bytesPerWord + byteOffset, bits);
  }

  // ---- Pointer section helpers ----

  /// Returns true if the pointer slot at [ptrIndex] has been written.
  bool hasPointerField(int ptrIndex) {
    if (ptrIndex >= _raw.ptrWords) return false;
    final absOffset = (_raw.ptrWordOffset + ptrIndex) * bytesPerWord;
    return readUint64(_raw.segment.data, absOffset) != 0;
  }

  /// Writes a Text (UTF-8 string) pointer at [ptrIndex].
  /// Passing null leaves the slot zeroed (null pointer).
  void setTextField(int ptrIndex, String? value) {
    _raw.arena.writeTextField(
        _raw.segment, _raw.ptrWordOffset + ptrIndex, value);
  }

  /// Writes a Data (raw bytes) pointer at [ptrIndex].
  /// Passing null leaves the slot zeroed (null pointer).
  void setDataField(int ptrIndex, Uint8List? value) {
    _raw.arena.writeDataField(
        _raw.segment, _raw.ptrWordOffset + ptrIndex, value);
  }

  /// Embeds [messageBytes] (a serialized Cap'n Proto message) as the
  /// AnyPointer at [ptrIndex].  Multi-segment messages are deep-copied into a
  /// single segment first.
  void setAnyPointerFromMessage(int ptrIndex, Uint8List messageBytes) {
    _raw.arena.writeAnyPointerFromMessage(
        _raw.segment,
        _raw.ptrWordOffset + ptrIndex,
        ensureSingleSegment(messageBytes));
  }

  /// Writes a capability pointer at [ptrIndex] referencing [capTableIndex]
  /// within the message's capability table.
  void setCapabilityField(int ptrIndex, int capTableIndex) {
    CapabilityPointer(capabilityIndex: capTableIndex)
        .encode(_raw.segment.data, _raw.ptrWordOffset + ptrIndex);
  }

  /// Allocates a new nested struct for the pointer at [ptrIndex] and returns
  /// a typed builder via [fromRaw].
  ///
  /// Uses a callback instead of [StructFactory] to avoid an import cycle
  /// between the layout and arena layers.
  B initStructFieldWith<B extends StructBuilder>(
    int ptrIndex,
    B Function(RawStructBuilder) fromRaw,
    int dataWords,
    int ptrWords,
  ) {
    final raw = _raw.arena.allocateStruct(
      ptrSeg: _raw.segment,
      ptrWordOffset: _raw.ptrWordOffset + ptrIndex,
      dataWords: dataWords,
      ptrWords: ptrWords,
    );
    return fromRaw(raw);
  }

  // ---- List field helpers ----

  RawListBuilder _allocateListField(
    int ptrIndex,
    ListElementSize elementSize,
    int count, {
    int structDataWords = 0,
    int structPtrWords = 0,
  }) =>
      _raw.arena.allocateList(
        ptrSeg: _raw.segment,
        ptrWordOffset: _raw.ptrWordOffset + ptrIndex,
        elementSize: elementSize,
        elementCount: count,
        structDataWords: structDataWords,
        structPtrWords: structPtrWords,
      );

  ListBuilder<Null> initVoidListField(int ptrIndex, int count) =>
      VoidListBuilder(_allocateListField(ptrIndex, ListElementSize.void_, count));

  ListBuilder<E> initEnumListField<E>(
          int ptrIndex, int count, int Function(E) toUint16) =>
      EnumListBuilder<E>(
          _allocateListField(ptrIndex, ListElementSize.twoBytes, count),
          toUint16);

  ListBuilder<bool> initBoolListField(int ptrIndex, int count) =>
      BoolListBuilder(_allocateListField(ptrIndex, ListElementSize.bit, count));

  ListBuilder<int> initInt8ListField(int ptrIndex, int count) =>
      PrimitiveIntListBuilder(
          _allocateListField(ptrIndex, ListElementSize.byte, count),
          readInt8, writeInt8, 1);

  ListBuilder<int> initUint8ListField(int ptrIndex, int count) =>
      PrimitiveIntListBuilder(
          _allocateListField(ptrIndex, ListElementSize.byte, count),
          readUint8, writeUint8, 1);

  ListBuilder<int> initInt16ListField(int ptrIndex, int count) =>
      PrimitiveIntListBuilder(
          _allocateListField(ptrIndex, ListElementSize.twoBytes, count),
          readInt16, writeInt16, 2);

  ListBuilder<int> initUint16ListField(int ptrIndex, int count) =>
      PrimitiveIntListBuilder(
          _allocateListField(ptrIndex, ListElementSize.twoBytes, count),
          readUint16, writeUint16, 2);

  ListBuilder<int> initInt32ListField(int ptrIndex, int count) =>
      PrimitiveIntListBuilder(
          _allocateListField(ptrIndex, ListElementSize.fourBytes, count),
          readInt32, writeInt32, 4);

  ListBuilder<int> initUint32ListField(int ptrIndex, int count) =>
      PrimitiveIntListBuilder(
          _allocateListField(ptrIndex, ListElementSize.fourBytes, count),
          readUint32, writeUint32, 4);

  ListBuilder<int> initInt64ListField(int ptrIndex, int count) =>
      PrimitiveIntListBuilder(
          _allocateListField(ptrIndex, ListElementSize.eightBytes, count),
          readInt64, writeInt64, 8);

  ListBuilder<int> initUint64ListField(int ptrIndex, int count) =>
      PrimitiveIntListBuilder(
          _allocateListField(ptrIndex, ListElementSize.eightBytes, count),
          readUint64, writeUint64, 8);

  ListBuilder<double> initFloat32ListField(int ptrIndex, int count) =>
      PrimitiveDoubleListBuilder(
          _allocateListField(ptrIndex, ListElementSize.fourBytes, count),
          readFloat32, writeFloat32, 4);

  ListBuilder<double> initFloat64ListField(int ptrIndex, int count) =>
      PrimitiveDoubleListBuilder(
          _allocateListField(ptrIndex, ListElementSize.eightBytes, count),
          readFloat64, writeFloat64, 8);

  ListBuilder<String?> initTextListField(int ptrIndex, int count) =>
      TextListBuilder(
          _allocateListField(ptrIndex, ListElementSize.pointer, count));

  ListBuilder<Uint8List?> initDataListField(int ptrIndex, int count) =>
      DataListBuilder(
          _allocateListField(ptrIndex, ListElementSize.pointer, count));

  /// Allocates a composite struct list with [count] elements and returns a
  /// typed builder via [fromRaw].
  ListBuilder<B> initStructListFieldWith<B>(
    int ptrIndex,
    int count,
    B Function(RawStructBuilder) fromRaw,
    int dataWords,
    int ptrWords,
  ) =>
      StructListBuilder<B>(
        _allocateListField(ptrIndex, ListElementSize.composite, count,
            structDataWords: dataWords, structPtrWords: ptrWords),
        fromRaw,
      );

  /// Allocates a `List(List(T))` field and returns a builder for the outer list.
  ///
  /// Call [NestedListBuilder.initAt] for each outer slot to allocate the inner
  /// list at that position.
  NestedListBuilder<ListBuilder<T>> initNestedListField<T>(
    int ptrIndex,
    int outerCount,
    ListBuilder<T> Function(RawListBuilder) fromRaw,
    ListElementSize innerElementSize, {
    int innerStructDataWords = 0,
    int innerStructPtrWords = 0,
  }) {
    final outerRaw =
        _allocateListField(ptrIndex, ListElementSize.pointer, outerCount);
    return NestedListBuilder<ListBuilder<T>>(
      length: outerRaw.elementCount,
      initAt: (i, innerCount) {
        final pw = outerRaw.dataByteOffset ~/ bytesPerWord + i;
        final innerRaw = outerRaw.arena.allocateList(
          ptrSeg: outerRaw.segment,
          ptrWordOffset: pw,
          elementSize: innerElementSize,
          elementCount: innerCount,
          structDataWords: innerStructDataWords,
          structPtrWords: innerStructPtrWords,
        );
        return fromRaw(innerRaw);
      },
    );
  }

  /// Allocates a `List(List(List(T)))` field and returns a builder for the outer list.
  NestedListBuilder<NestedListBuilder<ListBuilder<T>>> initBiNestedListField<T>(
    int ptrIndex,
    int outerCount,
    ListBuilder<T> Function(RawListBuilder) fromRaw,
    ListElementSize innerElementSize, {
    int innerStructDataWords = 0,
    int innerStructPtrWords = 0,
  }) {
    final outerRaw =
        _allocateListField(ptrIndex, ListElementSize.pointer, outerCount);
    return NestedListBuilder<NestedListBuilder<ListBuilder<T>>>(
      length: outerRaw.elementCount,
      initAt: (i, midCount) {
        final pw0 = outerRaw.dataByteOffset ~/ bytesPerWord + i;
        final midRaw = outerRaw.arena.allocateList(
          ptrSeg: outerRaw.segment,
          ptrWordOffset: pw0,
          elementSize: ListElementSize.pointer,
          elementCount: midCount,
        );
        return NestedListBuilder<ListBuilder<T>>(
          length: midRaw.elementCount,
          initAt: (j, innerCount) {
            final pw1 = midRaw.dataByteOffset ~/ bytesPerWord + j;
            final innerRaw = midRaw.arena.allocateList(
              ptrSeg: midRaw.segment,
              ptrWordOffset: pw1,
              elementSize: innerElementSize,
              elementCount: innerCount,
              structDataWords: innerStructDataWords,
              structPtrWords: innerStructPtrWords,
            );
            return fromRaw(innerRaw);
          },
        );
      },
    );
  }

  /// Returns a read-only **live view** over this builder's current contents.
  ///
  /// The returned [RawStructReader] shares the same underlying buffer as the
  /// builder. Subsequent writes through the builder are immediately visible
  /// through the returned reader.
  RawStructReader rawToReader() {
    final arena = ArenaReader.fromBuilder(_raw.arena);
    return RawStructReader(
      segment: arena.getSegment(_raw.segment.id),
      arena: arena,
      dataWordOffset: _raw.dataWordOffset,
      dataWords: _raw.dataWords,
      ptrWordOffset: _raw.ptrWordOffset,
      ptrWords: _raw.ptrWords,
      nestingLimit: 64,
    );
  }
}
