import 'dart:typed_data';

import '../arena/arena_reader.dart';
import '../exception/decode_exception.dart';
import '../message/message_copy.dart';
import '../message/message_reader_options.dart';
import '../wire/pointer.dart';
import '../wire/wire_helpers.dart';
import 'any_pointer.dart';
import 'list_reader.dart';

/// Base class for all generated struct readers.
///
/// Subclasses expose typed getters by calling the helper methods below.
/// The helpers handle bounds checking (field absent in older messages → default)
/// and XOR-based default masking as required by the Cap'n Proto spec.
///
/// **Intended users**
/// * Authors of generated `capnpc_dart` bindings and low-level runtime integrations.
///
/// **Primary use cases**
/// * Supports the typed bindings that map schema declarations to the Cap'n Proto wire layout.
abstract class StructReader {
  final RawStructReader _raw;
  final List<Object?> _capabilities;

  /// Creates a [StructReader] instance.
  StructReader(this._raw, {List<Object?> capabilities = const []})
    : _capabilities = capabilities;

  /// Exposes the underlying raw reader so that group accessors generated by
  /// capnpc-dart can forward the same raw bytes to their own constructor.
  RawStructReader get raw => _raw;

  /// Capability table associated with this struct's message payload.
  ///
  /// Raw serialized messages do not carry this table. RPC payload readers pass
  /// it separately so generated interface accessors can return typed clients
  /// instead of low-level cap-table indices.
  List<Object?> get capabilityTable => _capabilities;

  // ---- Data section helpers ----
  // [byteOffset] is the byte offset from the start of the data section.
  // [bitOffset] is the bit offset from the start of the data section.
  // Values are XOR'd with [defaultValue] per the Cap'n Proto default masking spec.

  /// Performs the [getBoolField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getBoolField(0);
  /// ```
  bool getBoolField(int bitOffset, {bool defaultValue = false}) {
    if (bitOffset ~/ 64 >= _raw.dataWords) return defaultValue;
    final byteIndex = bitOffset ~/ 8;
    final bitMask = 1 << (bitOffset & 7);
    final absOffset = _raw.dataWordOffset * bytesPerWord + byteIndex;
    final storedBit = (readUint8(_raw.segment.data, absOffset) & bitMask) != 0;
    return storedBit ^ defaultValue;
  }

  /// Performs the [getUint8Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getUint8Field(0);
  /// ```
  int getUint8Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readUint8(
          _raw.segment.data,
          _raw.dataWordOffset * bytesPerWord + byteOffset,
        ) ^
        defaultValue;
  }

  /// Performs the [getUint16Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getUint16Field(0);
  /// ```
  int getUint16Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readUint16(
          _raw.segment.data,
          _raw.dataWordOffset * bytesPerWord + byteOffset,
        ) ^
        defaultValue;
  }

  /// Performs the [getUint32Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getUint32Field(0);
  /// ```
  int getUint32Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readUint32(
          _raw.segment.data,
          _raw.dataWordOffset * bytesPerWord + byteOffset,
        ) ^
        defaultValue;
  }

  /// Performs the [getUint64Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getUint64Field(0);
  /// ```
  int getUint64Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readUint64(
          _raw.segment.data,
          _raw.dataWordOffset * bytesPerWord + byteOffset,
        ) ^
        defaultValue;
  }

  /// Performs the [getInt8Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getInt8Field(0);
  /// ```
  int getInt8Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readInt8(
          _raw.segment.data,
          _raw.dataWordOffset * bytesPerWord + byteOffset,
        ) ^
        defaultValue;
  }

  /// Performs the [getInt16Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getInt16Field(0);
  /// ```
  int getInt16Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readInt16(
          _raw.segment.data,
          _raw.dataWordOffset * bytesPerWord + byteOffset,
        ) ^
        defaultValue;
  }

  /// Performs the [getInt32Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getInt32Field(0);
  /// ```
  int getInt32Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readInt32(
          _raw.segment.data,
          _raw.dataWordOffset * bytesPerWord + byteOffset,
        ) ^
        defaultValue;
  }

  /// Performs the [getInt64Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getInt64Field(0);
  /// ```
  int getInt64Field(int byteOffset, {int defaultValue = 0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    return readInt64(
          _raw.segment.data,
          _raw.dataWordOffset * bytesPerWord + byteOffset,
        ) ^
        defaultValue;
  }

  /// Performs the [getFloat32Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getFloat32Field(0);
  /// ```
  double getFloat32Field(int byteOffset, {double defaultValue = 0.0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    final absOffset = _raw.dataWordOffset * bytesPerWord + byteOffset;
    if (defaultValue == 0.0) return readFloat32(_raw.segment.data, absOffset);
    final stored = readUint32(_raw.segment.data, absOffset);
    return reinterpretUint32AsFloat32(
      stored ^ reinterpretFloat32AsUint32(defaultValue),
    );
  }

  /// Performs the [getFloat64Field] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getFloat64Field(0);
  /// ```
  double getFloat64Field(int byteOffset, {double defaultValue = 0.0}) {
    if (byteOffset ~/ bytesPerWord >= _raw.dataWords) return defaultValue;
    final absOffset = _raw.dataWordOffset * bytesPerWord + byteOffset;
    if (defaultValue == 0.0) return readFloat64(_raw.segment.data, absOffset);
    final stored = readUint64(_raw.segment.data, absOffset);
    return reinterpretUint64AsFloat64(
      stored ^ reinterpretFloat64AsUint64(defaultValue),
    );
  }

  // ---- Pointer section helpers ----

  /// Returns true if the pointer at [ptrIndex] is non-null.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final isPresent = reader.hasPointerField(0);
  /// ```
  bool hasPointerField(int ptrIndex) {
    if (ptrIndex >= _raw.ptrWords) return false;
    final wordOffset = _raw.ptrWordOffset + ptrIndex;
    return WirePointer.decode(_raw.segment.data, wordOffset) is! NullPointer;
  }

  /// Returns the capability-table index stored in the capability pointer at
  /// [ptrIndex], or -1 if the pointer is absent or not a capability pointer.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getCapabilityField(0);
  /// ```
  int getCapabilityField(int ptrIndex) {
    if (ptrIndex >= _raw.ptrWords) return -1;
    final wordOffset = _raw.ptrWordOffset + ptrIndex;
    final wp = WirePointer.decode(_raw.segment.data, wordOffset);
    if (wp is NullPointer) return -1;
    if (wp is CapabilityPointer) return wp.capabilityIndex;
    throw DecodeException('expected capability pointer, got ${wp.runtimeType}');
  }

  /// Returns the capability object referenced by [ptrIndex], or null if the
  /// pointer is null / not a capability pointer.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getCapabilityObjectField(0);
  /// ```
  Object? getCapabilityObjectField(int ptrIndex) {
    final capIndex = getCapabilityField(ptrIndex);
    if (capIndex < 0) return null;
    if (capIndex >= _capabilities.length) {
      throw DecodeException(
        'capability table index $capIndex is out of range for ${_capabilities.length} capabilities',
      );
    }
    final cap = _capabilities[capIndex];
    if (cap == null) {
      throw DecodeException('capability table index $capIndex is null');
    }
    return cap;
  }

  /// Reads a Text (UTF-8 string) from the pointer at [ptrIndex].
  /// Returns [defaultValue] if the pointer is null — either because the
  /// field is genuinely absent (older message / never set) or, per the
  /// Cap'n Proto default-value spec, because it was explicitly set back to
  /// the schema-declared default (which pointer fields encode as a null
  /// pointer, same as "unset").
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getTextField(0);
  /// ```
  String? getTextField(int ptrIndex, {String? defaultValue}) {
    if (ptrIndex >= _raw.ptrWords) return defaultValue;
    return _raw.arena.resolveTextAt(
          _raw.segment,
          _raw.ptrWordOffset + ptrIndex,
        ) ??
        defaultValue;
  }

  /// Reads a Data (raw bytes) field from the pointer at [ptrIndex].
  /// Returns [defaultValue] if the pointer is null (see [getTextField]).
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getDataField(0);
  /// ```
  Uint8List? getDataField(int ptrIndex, {Uint8List? defaultValue}) {
    if (ptrIndex >= _raw.ptrWords) return defaultValue;
    return _raw.arena.resolveDataAt(
          _raw.segment,
          _raw.ptrWordOffset + ptrIndex,
        ) ??
        defaultValue;
  }

  /// Reads the AnyPointer at [ptrIndex], deep-copies the referenced struct
  /// into a new standalone message, and returns the serialized bytes.
  /// Returns null if the pointer is null.
  ///
  /// Capability pointers are zeroed by default because raw message bytes do not
  /// include a capability table. RPC payloads that carry a matching cap table
  /// can set [preserveCapabilityPointers].
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final result = reader.getAnyPointerAsMessageBytes(0);
  /// ```
  Uint8List? getAnyPointerAsMessageBytes(
    int ptrIndex, {
    bool preserveCapabilityPointers = false,
  }) {
    if (ptrIndex >= _raw.ptrWords) return null;
    return copyAnyPointerToNewMessage(
      _raw,
      ptrIndex,
      preserveCapabilityPointers: preserveCapabilityPointers,
    );
  }

  /// Returns a typed view of the AnyPointer at [ptrIndex].
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final fieldValue = reader.getAnyPointerField(0);
  /// ```
  AnyPointerReader? getAnyPointerField(int ptrIndex) {
    if (ptrIndex < 0 || ptrIndex >= _raw.ptrWords) return null;
    final wordOffset = _raw.ptrWordOffset + ptrIndex;
    if (WirePointer.decode(_raw.segment.data, wordOffset) is NullPointer) {
      return null;
    }
    return AnyPointerReader(_raw, ptrIndex, capabilities: _capabilities);
  }

  /// Reads a nested struct from the pointer at [ptrIndex]. Returns the
  /// struct decoded from [defaultValue] if the pointer is null and
  /// [defaultValue] is given (see [getTextField] for how this default
  /// mechanism relates to the plain "field absent" case); returns null
  /// otherwise.
  ///
  /// [defaultValue], when supplied, is a standalone single-message byte
  /// buffer (as produced by [getAnyPointerAsMessageBytes] on the schema's
  /// own default value at codegen time) whose root pointer is the default
  /// struct — matching how capnpc-dart embeds struct-typed field defaults
  /// as raw bytes rather than a Dart literal.
  ///
  /// Uses a callback instead of [StructFactory] to avoid an import cycle
  /// between the layout and arena layers.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final operation = reader.getStructFieldWith;
  /// ```
  R? getStructFieldWith<R extends StructReader>(
    int ptrIndex,
    R Function(RawStructReader) fromRaw, {
    Uint8List? defaultValue,
  }) {
    if (ptrIndex < _raw.ptrWords) {
      final wordOffset = _raw.ptrWordOffset + ptrIndex;
      final raw = _raw.arena.resolveOptionalStructAt(
        _raw.segment,
        wordOffset,
        _raw.nestingLimit,
      );
      if (raw != null) return fromRaw(raw);
    }
    if (defaultValue == null) return null;
    return fromRaw(_defaultMessageArena(defaultValue).getRootRaw());
  }

  // ---- List field helpers ----

  /// Parses [bytes] — a standalone single-message buffer holding a
  /// schema-declared field default — as its own tiny [ArenaReader]. Schema
  /// defaults are part of the trusted schema itself (not untrusted network
  /// input), so the default [MessageReaderOptions] are used unconditionally.
  ArenaReader _defaultMessageArena(Uint8List bytes) =>
      ArenaReader.fromBytes(bytes, const MessageReaderOptions());

  RawListReader? _resolveListField(int ptrIndex, {Uint8List? defaultValue}) {
    if (ptrIndex < _raw.ptrWords) {
      final raw = _raw.arena.resolveListAt(
        _raw.segment,
        _raw.ptrWordOffset + ptrIndex,
        _raw.nestingLimit,
      );
      if (raw != null) return raw;
    }
    if (defaultValue == null) return null;
    final arena = _defaultMessageArena(defaultValue);
    return arena.resolveListAt(arena.getSegment(0), 0, arena.nestingLimit);
  }

  /// Resolves the list field at [ptrIndex] and checks that its on-wire
  /// element size matches [expected].
  ///
  /// Every typed list reader below (`BoolListReader`, `PrimitiveIntListReader`,
  /// `TextListReader`, ...) computes its per-element byte stride from the
  /// *expected* type, not from the resolved [RawListReader.elementSize] —
  /// so without this check, a message whose list pointer declares a smaller
  /// on-wire element size than expected (e.g. `bit` where `fourBytes` was
  /// expected) would let [RawListReader.elementCount] — validated against
  /// the smaller size's bounds — be used as an index bound for the larger
  /// stride, reading past the segment. Throws [DecodeException] instead of
  /// letting that read fail as a raw, uncategorized range error.
  RawListReader? _resolveListFieldChecked(
    int ptrIndex,
    ListElementSize expected, {
    Uint8List? defaultValue,
  }) {
    final raw = _resolveListField(ptrIndex, defaultValue: defaultValue);
    if (raw != null && raw.elementSize != expected) {
      throw DecodeException(
        'expected $expected list, got ${raw.elementSize}',
      );
    }
    return raw;
  }

  // [defaultValue] (see getStructFieldWith's doc comment for the shared
  // mechanism) supplies the list read back when the field is unset and the
  // schema declares an explicit default for it.

  /// Performs the [getBoolListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getBoolListField(0);
  /// ```
  ListReader<bool>? getBoolListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.bit,
      defaultValue: defaultValue,
    );
    return raw == null ? null : BoolListReader(raw);
  }

  /// Performs the [getInt8ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getInt8ListField(0);
  /// ```
  ListReader<int>? getInt8ListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.byte,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveIntListReader(raw, readInt8, 1);
  }

  /// Performs the [getUint8ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getUint8ListField(0);
  /// ```
  ListReader<int>? getUint8ListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.byte,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveIntListReader(raw, readUint8, 1);
  }

  /// Performs the [getInt16ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getInt16ListField(0);
  /// ```
  ListReader<int>? getInt16ListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.twoBytes,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveIntListReader(raw, readInt16, 2);
  }

  /// Performs the [getUint16ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getUint16ListField(0);
  /// ```
  ListReader<int>? getUint16ListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.twoBytes,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveIntListReader(raw, readUint16, 2);
  }

  /// Performs the [getInt32ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getInt32ListField(0);
  /// ```
  ListReader<int>? getInt32ListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.fourBytes,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveIntListReader(raw, readInt32, 4);
  }

  /// Performs the [getUint32ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getUint32ListField(0);
  /// ```
  ListReader<int>? getUint32ListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.fourBytes,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveIntListReader(raw, readUint32, 4);
  }

  /// Performs the [getInt64ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getInt64ListField(0);
  /// ```
  ListReader<int>? getInt64ListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.eightBytes,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveIntListReader(raw, readInt64, 8);
  }

  /// Performs the [getUint64ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getUint64ListField(0);
  /// ```
  ListReader<int>? getUint64ListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.eightBytes,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveIntListReader(raw, readUint64, 8);
  }

  /// Performs the [getFloat32ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getFloat32ListField(0);
  /// ```
  ListReader<double>? getFloat32ListField(
    int ptrIndex, {
    Uint8List? defaultValue,
  }) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.fourBytes,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveDoubleListReader(raw, readFloat32, 4);
  }

  /// Performs the [getFloat64ListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getFloat64ListField(0);
  /// ```
  ListReader<double>? getFloat64ListField(
    int ptrIndex, {
    Uint8List? defaultValue,
  }) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.eightBytes,
      defaultValue: defaultValue,
    );
    return raw == null ? null : PrimitiveDoubleListReader(raw, readFloat64, 8);
  }

  /// Performs the [getTextListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getTextListField(0);
  /// ```
  ListReader<String?>? getTextListField(
    int ptrIndex, {
    Uint8List? defaultValue,
  }) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.pointer,
      defaultValue: defaultValue,
    );
    return raw == null ? null : TextListReader(raw);
  }

  /// Performs the [getDataListField] operation.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getDataListField(0);
  /// ```
  ListReader<Uint8List?>? getDataListField(
    int ptrIndex, {
    Uint8List? defaultValue,
  }) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.pointer,
      defaultValue: defaultValue,
    );
    return raw == null ? null : DataListReader(raw);
  }

  /// Reads a composite struct list from the pointer at [ptrIndex].
  /// Returns null if the pointer is null and no [defaultValue] is given.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final operation = reader.getStructListFieldWith;
  /// ```
  ListReader<R>? getStructListFieldWith<R>(
    int ptrIndex,
    R Function(RawStructReader) fromRaw, {
    Uint8List? defaultValue,
  }) {
    final raw = _resolveListField(ptrIndex, defaultValue: defaultValue);
    return raw == null ? null : StructListReader<R>(raw, fromRaw);
  }

  /// Reads a `List(Void)` from the pointer at [ptrIndex].
  /// Returns null if the pointer is null and no [defaultValue] is given.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getVoidListField(0);
  /// ```
  ListReader<Null>? getVoidListField(int ptrIndex, {Uint8List? defaultValue}) {
    final raw = _resolveListField(ptrIndex, defaultValue: defaultValue);
    return raw == null ? null : VoidListReader(raw);
  }

  /// Reads a list of enum values (stored as uint16) from [ptrIndex].
  /// [fromInt] maps the raw integer to [E?] (null = unknown discriminant).
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final operation = reader.getEnumListField;
  /// ```
  ListReader<E?>? getEnumListField<E>(
    int ptrIndex,
    E? Function(int) fromInt, {
    Uint8List? defaultValue,
  }) {
    final raw = _resolveListFieldChecked(
      ptrIndex,
      ListElementSize.twoBytes,
      defaultValue: defaultValue,
    );
    return raw == null ? null : EnumListReader<E>(raw, fromInt);
  }

  /// Reads a `List(List(T))` from [ptrIndex].
  /// [fromRaw] converts each inner [RawListReader] to [ListReader<T>].
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final operation = reader.getNestedListField;
  /// ```
  ListReader<ListReader<T>?>? getNestedListField<T>(
    int ptrIndex,
    ListReader<T>? Function(RawListReader) fromRaw,
  ) {
    final raw = _resolveListFieldChecked(ptrIndex, ListElementSize.pointer);
    return raw == null ? null : NestedListReader<T>(raw, fromRaw);
  }

  /// Reads a `List(Interface)` field at [ptrIndex].
  ///
  /// Returns a [ListReader<int>] whose elements are cap-table indices.
  /// Use the companion cap-table list (e.g. `paramsCapabilities`) to
  /// obtain the actual [Capability] objects: `caps[reader[i]]`.
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final values = reader.getCapabilityListField(0);
  /// ```
  ListReader<int>? getCapabilityListField(int ptrIndex) {
    final raw = _resolveListFieldChecked(ptrIndex, ListElementSize.pointer);
    return raw == null ? null : CapabilityListReader(raw);
  }

  /// Reads a typed `List(Interface)` field at [ptrIndex].
  ///
  /// **Example**
  /// ```dart
  /// // Given the required message, schema, or raw-layout values:
  /// final operation = reader.getCapabilityListFieldWith;
  /// ```
  ListReader<T?>? getCapabilityListFieldWith<T>(
    int ptrIndex,
    T Function(Object capability) fromCapability,
  ) {
    final raw = _resolveListField(ptrIndex);
    return raw == null
        ? null
        : TypedCapabilityListReader<T>(raw, _capabilities, fromCapability);
  }
}
