import 'package:capnpc_dart/capnpc_dart.dart';
import 'package:test/test.dart';

// ---------------------------------------------------------------------------
// Helpers to build in-memory schema models.
// ---------------------------------------------------------------------------

SchemaNode fileNode(int id, List<SchemaNestedNode> nested) => SchemaNode(
  id: id,
  displayName: 'test.capnp',
  displayNamePrefixLength: 0,
  scopeId: 0,
  nestedNodes: nested,
  body: const FileBody(),
);

SchemaNode structNode(
  int id,
  String name,
  int dw,
  int pw,
  List<SchemaField> fields, {
  bool isGroup = false,
  int discCount = 0,
  int discOffset = 0,
  List<SchemaNestedNode> nested = const [],
  List<String> parameters = const [],
}) => SchemaNode(
  id: id,
  displayName: 'test.capnp:$name',
  displayNamePrefixLength: 'test.capnp:'.length,
  scopeId: 1,
  nestedNodes: nested,
  body: StructBody(
    dataWordCount: dw,
    pointerCount: pw,
    isGroup: isGroup,
    discriminantCount: discCount,
    discriminantOffset: discOffset,
    fields: fields,
  ),
  parameters: parameters,
);

SchemaNode interfaceNode(int id, String name, List<SchemaMethod> methods) =>
    SchemaNode(
      id: id,
      displayName: 'test.capnp:$name',
      displayNamePrefixLength: 'test.capnp:'.length,
      scopeId: 1,
      nestedNodes: const [],
      body: InterfaceBody(methods: methods),
    );

SchemaNode enumNode(int id, String name, List<SchemaEnumerant> enumerants) =>
    SchemaNode(
      id: id,
      displayName: 'test.capnp:$name',
      displayNamePrefixLength: 'test.capnp:'.length,
      scopeId: 1,
      nestedNodes: const [],
      body: EnumBody(enumerants: enumerants),
    );

SchemaField dataField(
  String name,
  int codeOrder,
  int offset,
  SchemaType type,
) => SchemaField(
  name: name,
  codeOrder: codeOrder,
  discriminantValue: 0xFFFF,
  body: SlotField(offset: offset, type: type, hadExplicitDefault: false),
);

SchemaField unionField(
  String name,
  int codeOrder,
  int discVal,
  int offset,
  SchemaType type,
) => SchemaField(
  name: name,
  codeOrder: codeOrder,
  discriminantValue: discVal,
  body: SlotField(offset: offset, type: type, hadExplicitDefault: false),
);

SchemaField ptrField(String name, int codeOrder, int offset, SchemaType type) =>
    SchemaField(
      name: name,
      codeOrder: codeOrder,
      discriminantValue: 0xFFFF,
      body: SlotField(offset: offset, type: type, hadExplicitDefault: false),
    );

SchemaField defaultedField(
  String name,
  int codeOrder,
  int offset,
  SchemaType type,
  Object? defaultValue,
) => SchemaField(
  name: name,
  codeOrder: codeOrder,
  discriminantValue: 0xFFFF,
  body: SlotField(
    offset: offset,
    type: type,
    hadExplicitDefault: true,
    defaultValue: defaultValue,
  ),
);

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  group('generateDartFile — empty file', () {
    test('produces header and no class bodies', () {
      final file = fileNode(1, []);
      final src = generateDartFile(file, [file]);
      expect(
        src,
        contains("import 'package:capnproto_dart/capnproto_dart.dart'"),
      );
      expect(src, contains('// Generated by capnpc-dart'));
      expect(src, isNot(contains('class ')));
    });
  });

  group('generateDartFile — enum', () {
    test('generates enum values and converters', () {
      final eNode = enumNode(10, 'Color', [
        const SchemaEnumerant(name: 'red', codeOrder: 0),
        const SchemaEnumerant(name: 'green', codeOrder: 1),
        const SchemaEnumerant(name: 'blue', codeOrder: 2),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'Color', id: 10)]);
      final src = generateDartFile(file, [file, eNode]);

      expect(src, contains('enum Color {'));
      expect(src, contains('red,'));
      expect(src, contains('green,'));
      expect(src, contains('blue,'));
      expect(src, contains('Color? colorFromUint16(int v)'));
      expect(src, contains('int colorToUint16(Color v)'));
      expect(src, contains('const EnumSchemaInfo colorSchema'));
      expect(src, contains("name: 'red'"));
      expect(src, contains('codeOrder: 0'));
    });

    test('sorts enumerants by codeOrder', () {
      final eNode = enumNode(10, 'Priority', [
        const SchemaEnumerant(name: 'low', codeOrder: 2),
        const SchemaEnumerant(name: 'high', codeOrder: 0),
        const SchemaEnumerant(name: 'medium', codeOrder: 1),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'Priority', id: 10)]);
      final src = generateDartFile(file, [file, eNode]);

      final highIdx = src.indexOf('high,');
      final medIdx = src.indexOf('medium,');
      final lowIdx = src.indexOf('low,');
      expect(highIdx, lessThan(medIdx));
      expect(medIdx, lessThan(lowIdx));
    });
  });

  group('generateDartFile — simple struct', () {
    late String src;

    setUp(() {
      final sNode = structNode(
        20,
        'Person',
        1, // 1 data word
        1, // 1 pointer
        [
          dataField('age', 0, 0, const UInt32Type()), // byte offset 0
          ptrField('name', 1, 0, const TextType()), // ptr slot 0
        ],
      );
      final file = fileNode(1, [SchemaNestedNode(name: 'Person', id: 20)]);
      src = generateDartFile(file, [file, sNode]);
    });

    test('generates Reader class', () {
      expect(src, contains('final class PersonReader extends StructReader'));
      expect(src, contains('int get age => getUint32Field(0)'));
      expect(src, contains("String? get name => getTextField(0)"));
    });

    test('generates Builder class', () {
      expect(src, contains('final class PersonBuilder extends StructBuilder'));
      expect(src, contains('set age(int v)'));
      expect(src, contains('setUint32Field(0, v)'));
      expect(src, contains('set name(String? v)'));
      expect(src, contains('setTextField(0, v)'));
    });

    test('generates Factory class with correct dims', () {
      expect(src, contains('final class _PersonFactory'));
      expect(src, contains('int get dataWords => 1'));
      expect(src, contains('int get ptrWords => 1'));
      expect(src, contains('PersonReader fromRawReader'));
      expect(src, contains('PersonBuilder fromRawBuilder'));
    });

    test('generates factory singleton', () {
      expect(src, contains('final personFactory = _PersonFactory()'));
    });

    test('generates struct reflection metadata', () {
      expect(src, contains('const StructSchemaInfo personSchema'));
      expect(src, contains("shortName: 'Person'"));
      expect(src, contains('dataWords: 1'));
      expect(src, contains('pointerWords: 1'));
      expect(src, contains("name: 'age'"));
      expect(src, contains("type: PrimitiveTypeSchemaInfo('UInt32')"));
      expect(src, contains("name: 'name'"));
      expect(src, contains("type: PrimitiveTypeSchemaInfo('Text')"));
      expect(src, contains('StructSchemaInfo get schema => personSchema'));
      expect(
        src,
        contains('static const StructSchemaInfo schema = personSchema'),
      );
    });
  });

  group('generateDartFile — Void field accessors (GEN-009)', () {
    test('non-union Void field produces no reader getter', () {
      final s = structNode(20, 'S', 1, 0, [
        dataField('nothing', 0, 0, const VoidType()),
        dataField('x', 1, 4, const UInt32Type()),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, s]);
      expect(src, isNot(contains('void get nothing')));
      expect(src, isNot(contains('set nothing')));
    });

    test('non-union Void field produces no builder setter', () {
      final s = structNode(20, 'S', 1, 0, [
        dataField('nothing', 0, 0, const VoidType()),
        dataField('x', 1, 4, const UInt32Type()),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, s]);
      expect(src, isNot(contains('set nothing')));
      expect(src, isNot(contains('selectNothing')));
    });

    test('union Void member produces selectXxx() in builder', () {
      final s = structNode(
        20,
        'Tag',
        1, // 1 data word for the discriminant
        0,
        [
          unionField('none', 0, 0, 0, const VoidType()),
          unionField('value', 1, 1, 4, const UInt32Type()),
        ],
        discCount: 2,
        discOffset: 4, // discriminant at byte 8 (word 1)
      );
      final file = fileNode(1, [SchemaNestedNode(name: 'Tag', id: 20)]);
      final src = generateDartFile(file, [file, s]);
      // Reader: no getter for Void union member
      expect(src, isNot(contains('void get none')));
      // Builder: selection method
      expect(src, contains('void selectNone()'));
      expect(src, contains('setUint16Field(8, 0)'));
    });

    test('union Void member produces no reader getter', () {
      final s = structNode(
        20,
        'Tag',
        1,
        0,
        [unionField('absent', 0, 3, 0, const VoidType())],
        discCount: 1,
        discOffset: 0,
      );
      final file = fileNode(1, [SchemaNestedNode(name: 'Tag', id: 20)]);
      final src = generateDartFile(file, [file, s]);
      expect(src, isNot(contains('void get absent')));
    });
  });

  group('generateDartFile — integer byte offsets', () {
    test('UInt16 field uses offset*2', () {
      final sNode = structNode(20, 'S', 1, 0, [
        dataField('x', 0, 2, const UInt16Type()),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);
      expect(src, contains('getUint16Field(4)'));
      expect(src, contains('setUint16Field(4, v)'));
    });

    test('Int64 field uses offset*8', () {
      final sNode = structNode(20, 'S', 1, 0, [
        dataField('x', 0, 1, const Int64Type()),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);
      expect(src, contains('getInt64Field(8)'));
      expect(src, contains('setInt64Field(8, v)'));
    });
  });

  group('generateDartFile — struct ref field', () {
    test('generates init and has methods on builder', () {
      const addrId = 30;
      final addrNode = structNode(addrId, 'Address', 1, 0, []);
      final sNode = structNode(20, 'Person', 1, 1, [
        ptrField('address', 0, 0, StructRefType(addrId)),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'Person', id: 20),
        SchemaNestedNode(name: 'Address', id: addrId),
      ]);
      final src = generateDartFile(file, [file, sNode, addrNode]);

      expect(src, contains('AddressReader? get address =>'));
      expect(
        src,
        contains(
          'getStructFieldWith(0, (r) => AddressReader(r, capabilities: capabilityTable))',
        ),
      );
      expect(src, contains('AddressBuilder initAddress()'));
      expect(src, contains('bool hasAddress()'));
    });
  });

  group('generateDartFile — list field', () {
    test('uint32 list reader and builder', () {
      final sNode = structNode(20, 'S', 0, 1, [
        ptrField('values', 0, 0, const ListType(UInt32Type())),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('ListReader<int>? get values'));
      expect(src, contains('getUint32ListField(0)'));
      expect(src, contains('ListBuilder<int> initValues(int length)'));
      expect(src, contains('initUint32ListField(0, length)'));
    });

    test('struct list reader and builder', () {
      const itemId = 40;
      final itemNode = structNode(itemId, 'Item', 1, 0, []);
      final sNode = structNode(20, 'S', 0, 1, [
        ptrField('items', 0, 0, ListType(StructRefType(itemId))),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'S', id: 20),
        SchemaNestedNode(name: 'Item', id: itemId),
      ]);
      final src = generateDartFile(file, [file, sNode, itemNode]);

      expect(src, contains('ListReader<ItemReader>? get items'));
      expect(src, contains('ListBuilder<ItemBuilder> initItems(int length)'));
    });

    test('interface list reader exposes typed clients and cap indices', () {
      const sessionId = 41;
      final sessionNode = interfaceNode(sessionId, 'Session', []);
      final sNode = structNode(20, 'S', 0, 1, [
        ptrField('sessions', 0, 0, ListType(InterfaceRefType(sessionId))),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'S', id: 20),
        SchemaNestedNode(name: 'Session', id: sessionId),
      ]);
      final src = generateDartFile(file, [file, sNode, sessionNode]);

      expect(
        src,
        contains(
          'ListReader<SessionClient?>? get sessions => getCapabilityListFieldWith<SessionClient>(0, (cap) => SessionClient(cap as Capability))',
        ),
      );
      expect(
        src,
        contains(
          'ListReader<int>? get sessionsCapIndices => getCapabilityListField(0)',
        ),
      );
    });

    test('interface list builder exposes raw init and typed setter', () {
      const sessionId = 41;
      final sessionNode = interfaceNode(sessionId, 'Session', []);
      final sNode = structNode(20, 'S', 0, 1, [
        ptrField('sessions', 0, 0, ListType(InterfaceRefType(sessionId))),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'S', id: 20),
        SchemaNestedNode(name: 'Session', id: sessionId),
      ]);
      final src = generateDartFile(file, [file, sNode, sessionNode]);

      // Raw init method is still present
      expect(src, contains('ListBuilder<int> initSessions(int length)'));
      // Typed setter for List(Interface) builder
      expect(
        src,
        contains(
          'void setSessionsTyped(List<SessionClient> caps, List<Object?> capTable)',
        ),
      );
      expect(src, contains('capTable.add(caps[i].capability)'));
      expect(src, contains('builder[i] = capTable.length - 1'));
    });

    test('interface field builder exposes raw setter and typed setter', () {
      const sessionId = 41;
      final sessionNode = interfaceNode(sessionId, 'Session', []);
      final sNode = structNode(20, 'S', 0, 1, [
        ptrField('session', 0, 0, InterfaceRefType(sessionId)),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'S', id: 20),
        SchemaNestedNode(name: 'Session', id: sessionId),
      ]);
      final src = generateDartFile(file, [file, sNode, sessionNode]);

      // Raw setter (existing)
      expect(src, contains('void setSession(int capTableIndex)'));
      // Typed setter (new)
      expect(
        src,
        contains(
          'void setSessionTyped(SessionClient cap, List<Object?> capTable)',
        ),
      );
      expect(src, contains('capTable.add(cap.capability)'));
    });
  });

  group('generateDartFile — union', () {
    test('generates which getter and _setWhich setter', () {
      final sNode = structNode(
        20,
        'Shape',
        1,
        0,
        [
          unionField('circle', 0, 0, 0, const Float32Type()),
          unionField('square', 1, 1, 0, const Float32Type()),
        ],
        discCount: 2,
        discOffset: 2, // discriminant at uint16 offset 2 → byte 4
      );
      final file = fileNode(1, [SchemaNestedNode(name: 'Shape', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      // discriminant byte offset = 2 * 2 = 4
      expect(src, contains('int get which => getUint16Field(4)'));
      expect(src, contains('void _setWhich(int v) => setUint16Field(4, v)'));
    });

    test('union field builder sets discriminant', () {
      final sNode = structNode(
        20,
        'Shape',
        1,
        0,
        [unionField('circle', 0, 0, 0, const Float32Type())],
        discCount: 1,
        discOffset: 0,
      );
      final file = fileNode(1, [SchemaNestedNode(name: 'Shape', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('setUint16Field(0, 0)'));
    });
  });

  group('generateDartFile — enum ref field', () {
    test('generates fromUint16 getter and toUint16 setter', () {
      const colorId = 50;
      final colorNode = enumNode(colorId, 'Color', [
        const SchemaEnumerant(name: 'red', codeOrder: 0),
      ]);
      final sNode = structNode(20, 'S', 1, 0, [
        dataField('color', 0, 0, EnumRefType(colorId)),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'S', id: 20),
        SchemaNestedNode(name: 'Color', id: colorId),
      ]);
      final src = generateDartFile(file, [file, sNode, colorNode]);

      expect(
        src,
        contains('Color? get color => colorFromUint16(getUint16Field(0))'),
      );
      expect(src, contains('set color(Color v)'));
      expect(src, contains('setUint16Field(0, colorToUint16(v))'));
    });
  });

  group('generateDartFile — interface', () {
    const paramsId = 30;
    const resultsId = 31;
    const ifaceId = 0x1234abcd; // positive id for easy hex check

    late String src;
    setUp(() {
      final paramsNode = structNode(paramsId, 'GreetParams', 0, 1, [
        ptrField('name', 0, 0, const TextType()),
      ]);
      final resultsNode = structNode(resultsId, 'GreetResults', 0, 1, [
        ptrField('reply', 0, 0, const TextType()),
      ]);
      final iface = interfaceNode(ifaceId, 'Greeter', [
        SchemaMethod(
          name: 'greet',
          ordinal: 0,
          paramStructTypeId: paramsId,
          resultStructTypeId: resultsId,
        ),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'Greeter', id: ifaceId),
      ]);
      src = generateDartFile(file, [file, paramsNode, resultsNode, iface]);
    });

    test('imports capnproto_dart_rpc', () {
      expect(
        src,
        contains("import 'package:capnproto_dart_rpc/capnproto_dart_rpc.dart'"),
      );
    });

    test('params and results structs appear before the client stub', () {
      final paramsIdx = src.indexOf('GreetParamsReader');
      final clientIdx = src.indexOf('GreeterClient');
      expect(paramsIdx, lessThan(clientIdx));
    });

    test('generates client class with correct interface id', () {
      expect(src, contains('class GreeterClient extends Capability'));
      expect(
        src,
        contains('static const int _interfaceId = 0x000000001234abcd'),
      );
      expect(
        src,
        contains('static const InterfaceSchemaInfo schema = greeterSchema'),
      );
    });

    test('generates typed greet method', () {
      expect(src, contains('Future<GreetResultsReader> greet('));
      expect(src, contains('void Function(GreetParamsBuilder) build'));
      expect(
        src,
        contains('_cap.dispatch(0x000000001234abcd, 0, mb.serialize())'),
      );
      expect(
        src,
        contains('.getRoot(greetResultsFactory, capabilities: result.caps)'),
      );
    });

    test('generates factory', () {
      expect(
        src,
        contains(
          'class GreeterClientFactory extends CapabilityFactory<GreeterClient>',
        ),
      );
      expect(src, contains('GreeterClient fromCapability(Capability cap)'));
    });

    test('generates interface reflection metadata', () {
      expect(src, contains('const InterfaceSchemaInfo greeterSchema'));
      expect(src, contains("shortName: 'Greeter'"));
      expect(src, contains("name: 'greet'"));
      expect(src, contains('ordinal: 0'));
      expect(src, contains('paramStructTypeId: 0x000000000000001e'));
      expect(src, contains('resultStructTypeId: 0x000000000000001f'));
    });
  });

  group('generateDartFile — explicit defaults', () {
    test('uint32 field with non-zero default emits defaultValue: arg', () {
      final sNode = structNode(20, 'S', 1, 0, [
        defaultedField('x', 0, 0, const UInt32Type(), 42),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('getUint32Field(0, defaultValue: 42)'));
      expect(src, contains('setUint32Field(0, v, defaultValue: 42)'));
    });

    test('bool field with default true emits defaultValue: true', () {
      final sNode = structNode(20, 'S', 1, 0, [
        defaultedField('flag', 0, 0, const BoolType(), true),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('getBoolField(0, defaultValue: true)'));
      expect(src, contains('setBoolField(0, v, defaultValue: true)'));
    });

    test('zero/false default does not emit defaultValue: arg', () {
      final sNode = structNode(20, 'S', 1, 0, [
        defaultedField('x', 0, 0, const UInt32Type(), 0),
        defaultedField('flag', 1, 1, const BoolType(), false),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('getUint32Field(0)'));
      expect(src, contains('setUint32Field(0, v)'));
      expect(src, contains('getBoolField(1)'));
      expect(src, contains('setBoolField(1, v)'));
      expect(src, contains('defaultValue: 0'));
      expect(src, contains('defaultValue: false'));
    });

    test('null defaultValue does not emit defaultValue: arg', () {
      final sNode = structNode(20, 'S', 1, 0, [
        SchemaField(
          name: 'x',
          codeOrder: 0,
          discriminantValue: 0xFFFF,
          body: const SlotField(
            offset: 0,
            type: UInt32Type(),
            hadExplicitDefault: true,
          ),
        ),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, isNot(contains('defaultValue:')));
    });

    test('float32 field with non-zero default emits defaultValue:', () {
      final sNode = structNode(20, 'S', 1, 0, [
        defaultedField('ratio', 0, 0, const Float32Type(), 0.5),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('getFloat32Field(0, defaultValue: 0.5)'));
      expect(src, contains('setFloat32Field(0, v, defaultValue: 0.5)'));
    });

    test(
      'enum field with non-zero default emits defaultValue: inside getUint16',
      () {
        const colorId = 50;
        final colorNode = enumNode(colorId, 'Color', [
          const SchemaEnumerant(name: 'red', codeOrder: 0),
          const SchemaEnumerant(name: 'blue', codeOrder: 1),
        ]);
        final sNode = structNode(20, 'S', 1, 0, [
          defaultedField('color', 0, 0, EnumRefType(colorId), 1),
        ]);
        final file = fileNode(1, [
          SchemaNestedNode(name: 'S', id: 20),
          SchemaNestedNode(name: 'Color', id: colorId),
        ]);
        final src = generateDartFile(file, [file, sNode, colorNode]);

        expect(
          src,
          contains('colorFromUint16(getUint16Field(0, defaultValue: 1))'),
        );
        expect(
          src,
          contains('setUint16Field(0, colorToUint16(v), defaultValue: 1)'),
        );
      },
    );
  });

  group('generateDartFile — generic structs (GEN-008)', () {
    // A 2-pointer template struct KeyValue with TypeParameterRef fields.
    SchemaNode keyValueTemplate() => structNode(100, 'KeyValue', 0, 2, [
      ptrField('key', 0, 0, const TypeParameterRefType(0)),
      ptrField('value', 1, 1, const TypeParameterRefType(1)),
    ]);

    test(
      'TypeParameterRefType field generates AnyPointer reader in template',
      () {
        final kv = keyValueTemplate();
        final file = fileNode(1, [SchemaNestedNode(name: 'KeyValue', id: 100)]);
        final src = generateDartFile(file, [file, kv]);

        expect(src, contains('KeyValueReader'));
        expect(
          src,
          contains('AnyPointerReader? get key => getAnyPointerField(0)'),
        );
        expect(
          src,
          contains('AnyPointerReader? get value => getAnyPointerField(1)'),
        );
        expect(
          src,
          contains(
            'T? getKeyTyped<T>(AnyPointerCodec<T> codec) => codec.decode(key)',
          ),
        );
        expect(src, contains('type: TypeParameterSchemaInfo(0)'));
        expect(src, contains('type: TypeParameterSchemaInfo(1)'));
      },
    );

    test(
      'TypeParameterRefType field generates AnyPointer builder API in template builder',
      () {
        final kv = keyValueTemplate();
        final file = fileNode(1, [SchemaNestedNode(name: 'KeyValue', id: 100)]);
        final src = generateDartFile(file, [file, kv]);

        expect(src, contains('AnyPointerBuilder initKey()'));
        expect(src, contains('set key(AnyPointerReader? v)'));
        expect(src, contains('void setKeyMessage(Uint8List? v)'));
        expect(src, contains('void setKeyTyped<T>('));
        expect(
          src,
          contains(
            'codec.encode(initKey(), value, capabilities: capabilities)',
          ),
        );
        expect(src, contains('setAnyPointerField(0, v)'));
      },
    );

    test(
      'concrete StructRefType with typeArgs generates specialized reader class',
      () {
        final kv = keyValueTemplate();
        final outer = structNode(200, 'Wrapper', 0, 1, [
          ptrField(
            'pair',
            0,
            0,
            StructRefType(100, typeArgs: [const TextType(), const TextType()]),
          ),
        ]);
        final file = fileNode(1, [
          SchemaNestedNode(name: 'KeyValue', id: 100),
          SchemaNestedNode(name: 'Wrapper', id: 200),
        ]);
        final src = generateDartFile(file, [file, kv, outer]);

        expect(
          src,
          contains('final class KeyValueTextTextReader extends StructReader'),
        );
        expect(src, contains("String? get key => getTextField(0)"));
        expect(src, contains("String? get value => getTextField(1)"));
        expect(
          src,
          contains(
            'KeyValueTextTextReader? get pair => getStructFieldWith(0, (r) => KeyValueTextTextReader(r, capabilities: capabilityTable))',
          ),
        );
      },
    );

    test(
      'concrete StructRefType in List field generates specialized list reader',
      () {
        final kv = keyValueTemplate();
        final outer = structNode(200, 'Config', 0, 1, [
          ptrField(
            'entries',
            0,
            0,
            ListType(
              StructRefType(
                100,
                typeArgs: [const TextType(), const TextType()],
              ),
            ),
          ),
        ]);
        final file = fileNode(1, [
          SchemaNestedNode(name: 'KeyValue', id: 100),
          SchemaNestedNode(name: 'Config', id: 200),
        ]);
        final src = generateDartFile(file, [file, kv, outer]);

        expect(
          src,
          contains('final class KeyValueTextTextReader extends StructReader'),
        );
        expect(
          src,
          contains(
            'ListReader<KeyValueTextTextReader>? get entries => getStructListFieldWith(0, (r) => KeyValueTextTextReader(r, capabilities: capabilityTable))',
          ),
        );
      },
    );

    test('template class is still generated alongside specialized class', () {
      final kv = keyValueTemplate();
      final outer = structNode(200, 'Wrapper', 0, 1, [
        ptrField(
          'pair',
          0,
          0,
          StructRefType(100, typeArgs: [const TextType(), const TextType()]),
        ),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'KeyValue', id: 100),
        SchemaNestedNode(name: 'Wrapper', id: 200),
      ]);
      final src = generateDartFile(file, [file, kv, outer]);

      expect(src, contains('final class KeyValueReader extends StructReader'));
      expect(
        src,
        contains('final class KeyValueTextTextReader extends StructReader'),
      );
    });
  });

  group('generateDartFile — generic methods (GEN-031)', () {
    test('generates typed convenience API for TypeParameterRef params/results', () {
      final params = structNode(
        100,
        'Service.echoAny\$Params',
        0,
        1,
        [ptrField('value', 0, 0, const TypeParameterRefType(0))],
        parameters: ['Value'],
      );
      final results = structNode(
        101,
        'Service.echoAny\$Results',
        0,
        1,
        [ptrField('value', 0, 0, const TypeParameterRefType(0))],
        parameters: ['Value'],
      );
      final iface = interfaceNode(200, 'Service', [
        const SchemaMethod(
          name: 'echoAny',
          ordinal: 0,
          paramStructTypeId: 100,
          resultStructTypeId: 101,
        ),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'Service', id: 200)]);
      final src = generateDartFile(file, [file, params, results, iface]);

      expect(
        src,
        contains(
          'Future<Value?> echoAnyTyped<Value>(AnyPointerCodec<Value> valueCodec, Value value) async',
        ),
      );
      expect(
        src,
        contains(
          'b.setValueTyped(valueCodec, value, capabilities: typedCapabilities)',
        ),
      );
      expect(src, contains('final typedCapabilities = <Capability>[]'));
      expect(src, contains('paramsCapabilities: typedCapabilities'));
      expect(src, contains('return result.getValueTyped(valueCodec)'));
    });

    test('generic capability params/results keep typed capability table', () {
      final params = structNode(
        100,
        'Factory.echoCapability\$Params',
        0,
        1,
        [ptrField('capability', 0, 0, const TypeParameterRefType(0))],
        parameters: ['Cap'],
      );
      final results = structNode(
        101,
        'Factory.echoCapability\$Results',
        0,
        1,
        [ptrField('sameCapability', 0, 0, const TypeParameterRefType(0))],
        parameters: ['Cap'],
      );
      final iface = interfaceNode(200, 'Factory', [
        const SchemaMethod(
          name: 'echoCapability',
          ordinal: 3,
          paramStructTypeId: 100,
          resultStructTypeId: 101,
        ),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'Factory', id: 200)]);
      final src = generateDartFile(file, [file, params, results, iface]);

      expect(
        src,
        contains(
          'Future<Cap?> echoCapabilityTyped<Cap>(AnyPointerCodec<Cap> capCodec, Cap capability) async',
        ),
      );
      expect(
        src,
        contains(
          'b.setCapabilityTyped(capCodec, capability, capabilities: typedCapabilities)',
        ),
      );
      expect(src, contains('paramsCapabilities: typedCapabilities'));
      expect(src, contains('return result.getSameCapabilityTyped(capCodec)'));
    });
  });

  group('generateDartFile — capability-returning methods (GEN-002)', () {
    const sessionIfaceId = 40;
    const greeterIfaceId = 0x1234abcd;
    const paramsId = 41;
    const resultsId = 42;

    // A result struct with a single cap field at ptr slot 0.
    SchemaNode capResultNode() => structNode(
      resultsId,
      'NewSessionResults',
      0,
      1,
      [ptrField('session', 0, 0, InterfaceRefType(sessionIfaceId))],
    );

    SchemaNode sessionIfaceNode() => SchemaNode(
      id: sessionIfaceId,
      displayName: 'test.capnp:Session',
      displayNamePrefixLength: 'test.capnp:'.length,
      scopeId: 1,
      nestedNodes: const [],
      body: InterfaceBody(methods: const [], superclassIds: const []),
    );

    late String src;
    setUp(() {
      final paramsNode = structNode(paramsId, 'NewSessionParams', 0, 1, [
        ptrField('name', 0, 0, const TextType()),
      ]);
      final resultsNode = capResultNode();
      final sessionIface = sessionIfaceNode();
      final greeterIface = interfaceNode(greeterIfaceId, 'Greeter', [
        SchemaMethod(
          name: 'newSession',
          ordinal: 0,
          paramStructTypeId: paramsId,
          resultStructTypeId: resultsId,
        ),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'Session', id: sessionIfaceId),
        SchemaNestedNode(name: 'Greeter', id: greeterIfaceId),
      ]);
      src = generateDartFile(file, [
        file,
        paramsNode,
        resultsNode,
        sessionIface,
        greeterIface,
      ]);
    });

    test('returns a result wrapper that preserves returned capabilities', () {
      expect(src, contains('Future<GreeterNewSessionResult> newSession('));
      expect(src, contains('final class GreeterNewSessionResult'));
      expect(src, contains('final NewSessionResultsReader result;'));
      expect(src, contains('final SessionClient session;'));
      expect(src, isNot(contains('SessionClient newSession(')));
    });

    test('also generates a pipeline method', () {
      expect(src, contains('GreeterNewSessionPipeline newSessionPipeline('));
      expect(src, contains('beginDispatch('));
    });

    test('pipeline class uses correct ptr slot (not hardcoded 0)', () {
      expect(src, contains('final class GreeterNewSessionPipeline'));
      expect(src, contains('call.pipelineResult(0)'));
    });

    test('pipeline class exposes typed cap getter and result future', () {
      expect(src, contains('final SessionClient session;'));
      expect(src, contains('final Future<NewSessionResultsReader> result;'));
    });

    test('normal result wrapper uses correct ptr slot', () {
      expect(
        src,
        contains(
          'SessionClient(requireCapabilityFromResult(dispatchResult, 0))',
        ),
      );
    });

    test('cap field at non-zero ptr slot uses correct index', () {
      // Put the cap at ptr slot 2 (after two text fields).
      final resultsNodeSlot2 = structNode(resultsId + 10, 'GetResults', 0, 3, [
        ptrField('name', 0, 0, const TextType()),
        ptrField('desc', 1, 1, const TextType()),
        ptrField('session', 2, 2, InterfaceRefType(sessionIfaceId)),
      ]);
      final sessionIface = sessionIfaceNode();
      final greeterIface = interfaceNode(greeterIfaceId, 'Svc', [
        SchemaMethod(
          name: 'get',
          ordinal: 0,
          paramStructTypeId: paramsId,
          resultStructTypeId: resultsId + 10,
        ),
      ]);
      final paramsNode = structNode(paramsId, 'GetParams', 0, 0, []);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'Session', id: sessionIfaceId),
        SchemaNestedNode(name: 'Svc', id: greeterIfaceId),
      ]);
      final s = generateDartFile(file, [
        file,
        paramsNode,
        resultsNodeSlot2,
        sessionIface,
        greeterIface,
      ]);

      expect(s, contains('call.pipelineResult(2)'));
      expect(
        s,
        contains(
          'SessionClient(requireCapabilityFromResult(dispatchResult, 2))',
        ),
      );
      expect(s, isNot(contains('call.pipelineResult(0)')));
    });
  });

  group('generateDartFile — inherited method name collisions (GEN-008)', () {
    // Left and Right each define process(); Both extends both.
    const leftId = 0xaa01;
    const rightId = 0xbb02;
    const bothId = 0xcc03;
    const leftParamsId = 40;
    const leftResultsId = 41;
    const rightParamsId = 42;
    const rightResultsId = 43;
    const bothParamsId = 44;
    const bothResultsId = 45;

    late String src;

    setUp(() {
      final leftParams = structNode(leftParamsId, 'LeftProcessParams', 1, 0, [
        dataField('x', 0, 0, const Int32Type()),
      ]);
      final leftResults = structNode(
        leftResultsId,
        'LeftProcessResults',
        1,
        0,
        [dataField('r', 0, 0, const Int32Type())],
      );
      final rightParams = structNode(
        rightParamsId,
        'RightProcessParams',
        0,
        1,
        [ptrField('x', 0, 0, const TextType())],
      );
      final rightResults = structNode(
        rightResultsId,
        'RightProcessResults',
        0,
        1,
        [ptrField('r', 0, 0, const TextType())],
      );
      final bothParams = structNode(bothParamsId, 'BothFooParams', 0, 0, []);
      final bothResults = structNode(bothResultsId, 'BothFooResults', 0, 0, []);
      final leftIface = interfaceNode(leftId, 'Left', [
        SchemaMethod(
          name: 'process',
          ordinal: 0,
          paramStructTypeId: leftParamsId,
          resultStructTypeId: leftResultsId,
        ),
      ]);
      final rightIface = interfaceNode(rightId, 'Right', [
        SchemaMethod(
          name: 'process',
          ordinal: 0,
          paramStructTypeId: rightParamsId,
          resultStructTypeId: rightResultsId,
        ),
      ]);
      // Both extends Left and Right, and adds its own non-conflicting method.
      final bothIface = SchemaNode(
        id: bothId,
        displayName: 'test.capnp:Both',
        displayNamePrefixLength: 'test.capnp:'.length,
        scopeId: 1,
        nestedNodes: const [],
        body: InterfaceBody(
          methods: [
            SchemaMethod(
              name: 'foo',
              ordinal: 0,
              paramStructTypeId: bothParamsId,
              resultStructTypeId: bothResultsId,
            ),
          ],
          superclassIds: [leftId, rightId],
        ),
      );
      final file = fileNode(1, [
        SchemaNestedNode(name: 'Left', id: leftId),
        SchemaNestedNode(name: 'Right', id: rightId),
        SchemaNestedNode(name: 'Both', id: bothId),
      ]);
      src = generateDartFile(file, [
        file,
        leftParams,
        leftResults,
        rightParams,
        rightResults,
        bothParams,
        bothResults,
        leftIface,
        rightIface,
        bothIface,
      ]);
    });

    // Helper: extract the content of the BothClient or BothServer class block.
    String bothClientSection() {
      final start = src.indexOf('class BothClient');
      final end = src.indexOf('\nclass BothClientFactory', start);
      return src.substring(start, end);
    }

    String bothServerSection() {
      final start = src.indexOf('abstract class BothServer');
      return src.substring(start);
    }

    test('conflicting method gets interface-name prefix in BothClient', () {
      final section = bothClientSection();
      // The prefixed names must appear in BothClient.
      expect(section, contains('leftProcess('));
      expect(section, contains('rightProcess('));
      // The bare 'process' method must NOT appear in BothClient itself.
      expect(
        section,
        isNot(contains('Future<LeftProcessResultsReader> process(')),
      );
      expect(
        section,
        isNot(contains('Future<RightProcessResultsReader> process(')),
      );
    });

    test(
      'non-conflicting own method keeps its original name in BothClient',
      () {
        expect(bothClientSection(), contains('foo('));
      },
    );

    test(
      'conflicting method gets prefix in BothServer abstract declaration',
      () {
        expect(bothServerSection(), contains('leftProcess('));
        expect(bothServerSection(), contains('rightProcess('));
      },
    );

    test('server dispatch still calls the prefixed abstract method', () {
      expect(
        bothServerSection(),
        contains(
          'await leftProcessWithContext(p, paramsCapabilities, dispatchContext)',
        ),
      );
      expect(
        bothServerSection(),
        contains(
          'await rightProcessWithContext(p, paramsCapabilities, dispatchContext)',
        ),
      );
    });

    test('server exposes context-aware hook without requiring override', () {
      expect(
        bothServerSection(),
        contains(
          'Future<DispatchResult> leftProcessWithContext(LeftProcessParamsReader params, List<Capability> paramsCapabilities, DispatchContext context) =>',
        ),
      );
      expect(
        bothServerSection(),
        contains('leftProcess(params, paramsCapabilities);'),
      );
    });

    test('non-conflicting method in BothServer uses original name', () {
      // foo has empty results struct → isVoid=true → Future<void> foo(...)
      expect(bothServerSection(), contains('foo('));
    });
  });

  group('generateDartFile — unsupported list element types (GEN-004)', () {
    late SchemaNode enumNode10;
    late SchemaNode strNode20;
    late SchemaNode file;

    setUp(() {
      enumNode10 = enumNode(10, 'Color', [
        const SchemaEnumerant(name: 'red', codeOrder: 0),
        const SchemaEnumerant(name: 'blue', codeOrder: 1),
      ]);
      strNode20 = structNode(20, 'Item', 0, 0, []);
      file = fileNode(1, [
        SchemaNestedNode(name: 'Color', id: 10),
        SchemaNestedNode(name: 'Item', id: 20),
        SchemaNestedNode(name: 'AllLists', id: 30),
      ]);
    });

    test('List(Void) generates getVoidListField reader', () {
      final s = structNode(30, 'AllLists', 0, 1, [
        ptrField('voids', 0, 0, const ListType(VoidType())),
      ]);
      final src = generateDartFile(file, [file, enumNode10, strNode20, s]);
      expect(src, contains('ListReader<Null>?'));
      expect(src, contains('getVoidListField(0)'));
    });

    test('List(Void) init generates initVoidListField', () {
      final s = structNode(30, 'AllLists', 0, 1, [
        ptrField('voids', 0, 0, const ListType(VoidType())),
      ]);
      final src = generateDartFile(file, [file, enumNode10, strNode20, s]);
      expect(src, contains('ListBuilder<Null>'));
      expect(src, contains('initVoidListField(0, length)'));
    });

    test('List(Enum) generates getEnumListField reader', () {
      final s = structNode(30, 'AllLists', 0, 1, [
        ptrField('colors', 0, 0, const ListType(EnumRefType(10))),
      ]);
      final src = generateDartFile(file, [file, enumNode10, strNode20, s]);
      expect(src, contains('ListReader<Color?>?'));
      expect(src, contains('getEnumListField(0, colorFromUint16)'));
    });

    test('List(Enum) init generates initEnumListField', () {
      final s = structNode(30, 'AllLists', 0, 1, [
        ptrField('colors', 0, 0, const ListType(EnumRefType(10))),
      ]);
      final src = generateDartFile(file, [file, enumNode10, strNode20, s]);
      expect(src, contains('ListBuilder<Color>'));
      expect(src, contains('initEnumListField(0, length, colorToUint16)'));
    });

    test('List(List(Float64)) generates getNestedListField reader', () {
      final s = structNode(30, 'AllLists', 0, 1, [
        ptrField('rows', 0, 0, const ListType(ListType(Float64Type()))),
      ]);
      final src = generateDartFile(file, [file, enumNode10, strNode20, s]);
      expect(src, contains('ListReader<ListReader<double>?>?'));
      expect(src, contains('getNestedListField(0, float64ListFromRaw)'));
    });

    test('List(List(List(Int32))) generates double-nested reader', () {
      final s = structNode(30, 'AllLists', 0, 1, [
        ptrField(
          'matrices',
          0,
          0,
          const ListType(ListType(ListType(Int32Type()))),
        ),
      ]);
      final src = generateDartFile(file, [file, enumNode10, strNode20, s]);
      expect(src, contains('ListReader<ListReader<ListReader<int>?>?>?'));
      expect(src, contains('getNestedListField('));
      expect(src, contains('NestedListReader<int>'));
      expect(src, contains('int32ListFromRaw'));
    });

    test('List(List(Interface)) reader generates typed nested capability list', () {
      const sessionId = 41;
      final sessionNode = interfaceNode(sessionId, 'Session', []);
      final s = structNode(30, 'AllLists', 0, 1, [
        ptrField(
          'sessionGroups',
          0,
          0,
          ListType(ListType(InterfaceRefType(sessionId))),
        ),
      ]);
      final f = fileNode(1, [
        SchemaNestedNode(name: 'Session', id: sessionId),
        SchemaNestedNode(name: 'AllLists', id: 30),
      ]);
      final src = generateDartFile(f, [f, sessionNode, s]);

      // Outer list contains inner capability list readers
      expect(
        src,
        contains('ListReader<ListReader<SessionClient?>?>?'),
      );
      expect(src, contains('TypedCapabilityListReader<SessionClient>'));
    });

    test('List(List(Interface)) builder generates nested capability list init', () {
      const sessionId = 41;
      final sessionNode = interfaceNode(sessionId, 'Session', []);
      final s = structNode(30, 'AllLists', 0, 1, [
        ptrField(
          'sessionGroups',
          0,
          0,
          ListType(ListType(InterfaceRefType(sessionId))),
        ),
      ]);
      final f = fileNode(1, [
        SchemaNestedNode(name: 'Session', id: sessionId),
        SchemaNestedNode(name: 'AllLists', id: 30),
      ]);
      final src = generateDartFile(f, [f, sessionNode, s]);

      // Builder returns NestedListBuilder<ListBuilder<int>> for List(List(Interface))
      expect(src, contains('NestedListBuilder<ListBuilder<int>>'));
      expect(src, contains('initNestedListField('));
      expect(src, contains('capabilityListBuilderFromRaw'));
    });
  });

  group('generateDartFiles — codegen entrypoint', () {
    test('maps .capnp filename to .capnp.dart', () {
      final sNode = structNode(20, 'Msg', 1, 0, [
        dataField('x', 0, 0, const Int32Type()),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'Msg', id: 20)]);
      final request = CodeGeneratorRequest(
        nodes: [file, sNode],
        requestedFiles: [RequestedFile(id: 1, filename: 'proto/msg.capnp')],
      );
      final results = generateDartFiles(request);

      expect(results.keys, contains('proto/msg.capnp.dart'));
      expect(results['proto/msg.capnp.dart'], contains('MsgReader'));
    });
  });
}
