import 'package:capnpc_dart/capnpc_dart.dart';
import 'package:test/test.dart';

// ---------------------------------------------------------------------------
// Helpers to build in-memory schema models.
// ---------------------------------------------------------------------------

SchemaNode fileNode(int id, List<SchemaNestedNode> nested) => SchemaNode(
      id: id,
      displayName: 'test.capnp',
      displayNamePrefixLength: 0,
      scopeId: 0,
      nestedNodes: nested,
      body: const FileBody(),
    );

SchemaNode structNode(
  int id,
  String name,
  int dw,
  int pw,
  List<SchemaField> fields, {
  bool isGroup = false,
  int discCount = 0,
  int discOffset = 0,
  List<SchemaNestedNode> nested = const [],
}) =>
    SchemaNode(
      id: id,
      displayName: 'test.capnp:$name',
      displayNamePrefixLength: 'test.capnp:'.length,
      scopeId: 1,
      nestedNodes: nested,
      body: StructBody(
        dataWordCount: dw,
        pointerCount: pw,
        isGroup: isGroup,
        discriminantCount: discCount,
        discriminantOffset: discOffset,
        fields: fields,
      ),
    );

SchemaNode interfaceNode(int id, String name, List<SchemaMethod> methods) =>
    SchemaNode(
      id: id,
      displayName: 'test.capnp:$name',
      displayNamePrefixLength: 'test.capnp:'.length,
      scopeId: 1,
      nestedNodes: const [],
      body: InterfaceBody(methods: methods),
    );

SchemaNode enumNode(int id, String name, List<SchemaEnumerant> enumerants) =>
    SchemaNode(
      id: id,
      displayName: 'test.capnp:$name',
      displayNamePrefixLength: 'test.capnp:'.length,
      scopeId: 1,
      nestedNodes: const [],
      body: EnumBody(enumerants: enumerants),
    );

SchemaField dataField(String name, int codeOrder, int offset, SchemaType type) =>
    SchemaField(
      name: name,
      codeOrder: codeOrder,
      discriminantValue: 0xFFFF,
      body: SlotField(offset: offset, type: type, hadExplicitDefault: false),
    );

SchemaField unionField(
        String name, int codeOrder, int discVal, int offset, SchemaType type) =>
    SchemaField(
      name: name,
      codeOrder: codeOrder,
      discriminantValue: discVal,
      body: SlotField(offset: offset, type: type, hadExplicitDefault: false),
    );

SchemaField ptrField(String name, int codeOrder, int offset, SchemaType type) =>
    SchemaField(
      name: name,
      codeOrder: codeOrder,
      discriminantValue: 0xFFFF,
      body: SlotField(offset: offset, type: type, hadExplicitDefault: false),
    );

SchemaField defaultedField(
        String name, int codeOrder, int offset, SchemaType type,
        Object? defaultValue) =>
    SchemaField(
      name: name,
      codeOrder: codeOrder,
      discriminantValue: 0xFFFF,
      body: SlotField(
          offset: offset,
          type: type,
          hadExplicitDefault: true,
          defaultValue: defaultValue),
    );

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  group('generateDartFile — empty file', () {
    test('produces header and no class bodies', () {
      final file = fileNode(1, []);
      final src = generateDartFile(file, [file]);
      expect(src, contains("import 'package:capnproto_dart/capnproto_dart.dart'"));
      expect(src, contains('// Generated by capnpc-dart'));
      expect(src, isNot(contains('class ')));
    });
  });

  group('generateDartFile — enum', () {
    test('generates enum values and converters', () {
      final eNode = enumNode(10, 'Color', [
        const SchemaEnumerant(name: 'red', codeOrder: 0),
        const SchemaEnumerant(name: 'green', codeOrder: 1),
        const SchemaEnumerant(name: 'blue', codeOrder: 2),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'Color', id: 10)]);
      final src = generateDartFile(file, [file, eNode]);

      expect(src, contains('enum Color {'));
      expect(src, contains('red,'));
      expect(src, contains('green,'));
      expect(src, contains('blue,'));
      expect(src, contains('Color? colorFromUint16(int v)'));
      expect(src, contains('int colorToUint16(Color v)'));
    });

    test('sorts enumerants by codeOrder', () {
      final eNode = enumNode(10, 'Priority', [
        const SchemaEnumerant(name: 'low', codeOrder: 2),
        const SchemaEnumerant(name: 'high', codeOrder: 0),
        const SchemaEnumerant(name: 'medium', codeOrder: 1),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'Priority', id: 10)]);
      final src = generateDartFile(file, [file, eNode]);

      final highIdx = src.indexOf('high,');
      final medIdx = src.indexOf('medium,');
      final lowIdx = src.indexOf('low,');
      expect(highIdx, lessThan(medIdx));
      expect(medIdx, lessThan(lowIdx));
    });
  });

  group('generateDartFile — simple struct', () {
    late String src;

    setUp(() {
      final sNode = structNode(
        20,
        'Person',
        1, // 1 data word
        1, // 1 pointer
        [
          dataField('age', 0, 0, const UInt32Type()),  // byte offset 0
          ptrField('name', 1, 0, const TextType()),    // ptr slot 0
        ],
      );
      final file = fileNode(1, [SchemaNestedNode(name: 'Person', id: 20)]);
      src = generateDartFile(file, [file, sNode]);
    });

    test('generates Reader class', () {
      expect(src, contains('final class PersonReader extends StructReader'));
      expect(src, contains('int get age => getUint32Field(0)'));
      expect(src, contains("String? get name => getTextField(0)"));
    });

    test('generates Builder class', () {
      expect(src, contains('final class PersonBuilder extends StructBuilder'));
      expect(src, contains('set age(int v)'));
      expect(src, contains('setUint32Field(0, v)'));
      expect(src, contains('set name(String? v)'));
      expect(src, contains('setTextField(0, v)'));
    });

    test('generates Factory class with correct dims', () {
      expect(src, contains('final class _PersonFactory'));
      expect(src, contains('int get dataWords => 1'));
      expect(src, contains('int get ptrWords => 1'));
      expect(src, contains('PersonReader fromRawReader'));
      expect(src, contains('PersonBuilder fromRawBuilder'));
    });

    test('generates factory singleton', () {
      expect(src, contains('final personFactory = _PersonFactory()'));
    });
  });

  group('generateDartFile — integer byte offsets', () {
    test('UInt16 field uses offset*2', () {
      final sNode = structNode(20, 'S', 1, 0, [
        dataField('x', 0, 2, const UInt16Type()),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);
      expect(src, contains('getUint16Field(4)'));
      expect(src, contains('setUint16Field(4, v)'));
    });

    test('Int64 field uses offset*8', () {
      final sNode = structNode(20, 'S', 1, 0, [
        dataField('x', 0, 1, const Int64Type()),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);
      expect(src, contains('getInt64Field(8)'));
      expect(src, contains('setInt64Field(8, v)'));
    });
  });

  group('generateDartFile — struct ref field', () {
    test('generates init and has methods on builder', () {
      const addrId = 30;
      final addrNode = structNode(addrId, 'Address', 1, 0, []);
      final sNode = structNode(20, 'Person', 1, 1, [
        ptrField('address', 0, 0, StructRefType(addrId)),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'Person', id: 20),
        SchemaNestedNode(name: 'Address', id: addrId),
      ]);
      final src = generateDartFile(file, [file, sNode, addrNode]);

      expect(src, contains('AddressReader? get address =>'));
      expect(src, contains('getStructFieldWith(0, (r) => AddressReader(r))'));
      expect(src, contains('AddressBuilder initAddress()'));
      expect(src, contains('bool hasAddress()'));
    });
  });

  group('generateDartFile — list field', () {
    test('uint32 list reader and builder', () {
      final sNode = structNode(20, 'S', 0, 1, [
        ptrField('values', 0, 0, const ListType(UInt32Type())),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('ListReader<int>? get values'));
      expect(src, contains('getUint32ListField(0)'));
      expect(src, contains('ListBuilder<int> initValues(int length)'));
      expect(src, contains('initUint32ListField(0, length)'));
    });

    test('struct list reader and builder', () {
      const itemId = 40;
      final itemNode = structNode(itemId, 'Item', 1, 0, []);
      final sNode = structNode(20, 'S', 0, 1, [
        ptrField('items', 0, 0, ListType(StructRefType(itemId))),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'S', id: 20),
        SchemaNestedNode(name: 'Item', id: itemId),
      ]);
      final src = generateDartFile(file, [file, sNode, itemNode]);

      expect(src, contains('ListReader<ItemReader>? get items'));
      expect(src, contains('ListBuilder<ItemBuilder> initItems(int length)'));
    });
  });

  group('generateDartFile — union', () {
    test('generates which getter and _setWhich setter', () {
      final sNode = structNode(
        20,
        'Shape',
        1,
        0,
        [
          unionField('circle', 0, 0, 0, const Float32Type()),
          unionField('square', 1, 1, 0, const Float32Type()),
        ],
        discCount: 2,
        discOffset: 2, // discriminant at uint16 offset 2 → byte 4
      );
      final file = fileNode(1, [SchemaNestedNode(name: 'Shape', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      // discriminant byte offset = 2 * 2 = 4
      expect(src, contains('int get which => getUint16Field(4)'));
      expect(src, contains('void _setWhich(int v) => setUint16Field(4, v)'));
    });

    test('union field builder sets discriminant', () {
      final sNode = structNode(
        20,
        'Shape',
        1,
        0,
        [
          unionField('circle', 0, 0, 0, const Float32Type()),
        ],
        discCount: 1,
        discOffset: 0,
      );
      final file = fileNode(1, [SchemaNestedNode(name: 'Shape', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('setUint16Field(0, 0)'));
    });
  });

  group('generateDartFile — enum ref field', () {
    test('generates fromUint16 getter and toUint16 setter', () {
      const colorId = 50;
      final colorNode = enumNode(colorId, 'Color', [
        const SchemaEnumerant(name: 'red', codeOrder: 0),
      ]);
      final sNode = structNode(20, 'S', 1, 0, [
        dataField('color', 0, 0, EnumRefType(colorId)),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'S', id: 20),
        SchemaNestedNode(name: 'Color', id: colorId),
      ]);
      final src = generateDartFile(file, [file, sNode, colorNode]);

      expect(src, contains('Color? get color => colorFromUint16(getUint16Field(0))'));
      expect(src, contains('set color(Color v)'));
      expect(src, contains('setUint16Field(0, colorToUint16(v))'));
    });
  });

  group('generateDartFile — interface', () {
    const paramsId = 30;
    const resultsId = 31;
    const ifaceId = 0x1234abcd; // positive id for easy hex check

    late String src;
    setUp(() {
      final paramsNode = structNode(paramsId, 'GreetParams', 0, 1, [
        ptrField('name', 0, 0, const TextType()),
      ]);
      final resultsNode = structNode(resultsId, 'GreetResults', 0, 1, [
        ptrField('reply', 0, 0, const TextType()),
      ]);
      final iface = interfaceNode(ifaceId, 'Greeter', [
        SchemaMethod(
          name: 'greet',
          ordinal: 0,
          paramStructTypeId: paramsId,
          resultStructTypeId: resultsId,
        ),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'Greeter', id: ifaceId)]);
      src = generateDartFile(file, [file, paramsNode, resultsNode, iface]);
    });

    test('imports capnproto_dart_rpc', () {
      expect(src, contains("import 'package:capnproto_dart_rpc/capnproto_dart_rpc.dart'"));
    });

    test('params and results structs appear before the client stub', () {
      final paramsIdx = src.indexOf('GreetParamsReader');
      final clientIdx = src.indexOf('GreeterClient');
      expect(paramsIdx, lessThan(clientIdx));
    });

    test('generates client class with correct interface id', () {
      expect(src, contains('class GreeterClient extends Capability'));
      expect(src, contains('static const int _interfaceId = 0x000000001234abcd'));
    });

    test('generates typed greet method', () {
      expect(src, contains('Future<GreetResultsReader> greet('));
      expect(src, contains('void Function(GreetParamsBuilder) build'));
      expect(src, contains('_cap.dispatch(0x000000001234abcd, 0, mb.serialize())'));
      expect(src, contains('.getRoot(greetResultsFactory)'));
    });

    test('generates factory', () {
      expect(src, contains('class GreeterClientFactory extends CapabilityFactory<GreeterClient>'));
      expect(src, contains('GreeterClient fromCapability(Capability cap)'));
    });
  });

  group('generateDartFile — explicit defaults', () {
    test('uint32 field with non-zero default emits defaultValue: arg', () {
      final sNode = structNode(20, 'S', 1, 0, [
        defaultedField('x', 0, 0, const UInt32Type(), 42),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('getUint32Field(0, defaultValue: 42)'));
      expect(src, contains('setUint32Field(0, v, defaultValue: 42)'));
    });

    test('bool field with default true emits defaultValue: true', () {
      final sNode = structNode(20, 'S', 1, 0, [
        defaultedField('flag', 0, 0, const BoolType(), true),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('getBoolField(0, defaultValue: true)'));
      expect(src, contains('setBoolField(0, v, defaultValue: true)'));
    });

    test('zero/false default does not emit defaultValue: arg', () {
      final sNode = structNode(20, 'S', 1, 0, [
        defaultedField('x', 0, 0, const UInt32Type(), 0),
        defaultedField('flag', 1, 1, const BoolType(), false),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, isNot(contains('defaultValue:')));
    });

    test('null defaultValue does not emit defaultValue: arg', () {
      final sNode = structNode(20, 'S', 1, 0, [
        SchemaField(
          name: 'x',
          codeOrder: 0,
          discriminantValue: 0xFFFF,
          body: const SlotField(
              offset: 0, type: UInt32Type(), hadExplicitDefault: true),
        ),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, isNot(contains('defaultValue:')));
    });

    test('float32 field with non-zero default emits defaultValue:', () {
      final sNode = structNode(20, 'S', 1, 0, [
        defaultedField('ratio', 0, 0, const Float32Type(), 0.5),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'S', id: 20)]);
      final src = generateDartFile(file, [file, sNode]);

      expect(src, contains('getFloat32Field(0, defaultValue: 0.5)'));
      expect(src, contains('setFloat32Field(0, v, defaultValue: 0.5)'));
    });

    test('enum field with non-zero default emits defaultValue: inside getUint16', () {
      const colorId = 50;
      final colorNode = enumNode(colorId, 'Color', [
        const SchemaEnumerant(name: 'red', codeOrder: 0),
        const SchemaEnumerant(name: 'blue', codeOrder: 1),
      ]);
      final sNode = structNode(20, 'S', 1, 0, [
        defaultedField('color', 0, 0, EnumRefType(colorId), 1),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'S', id: 20),
        SchemaNestedNode(name: 'Color', id: colorId),
      ]);
      final src = generateDartFile(file, [file, sNode, colorNode]);

      expect(src, contains('colorFromUint16(getUint16Field(0, defaultValue: 1))'));
      expect(src, contains('setUint16Field(0, colorToUint16(v), defaultValue: 1)'));
    });
  });

  group('generateDartFile — generic structs (GEN-008)', () {
    // A 2-pointer template struct KeyValue with TypeParameterRef fields.
    SchemaNode keyValueTemplate() => structNode(
          100,
          'KeyValue',
          0,
          2,
          [
            ptrField('key', 0, 0, const TypeParameterRefType(0)),
            ptrField('value', 1, 1, const TypeParameterRefType(1)),
          ],
        );

    test('TypeParameterRefType field generates Uint8List? AnyPointer getter in template', () {
      final kv = keyValueTemplate();
      final file = fileNode(1, [SchemaNestedNode(name: 'KeyValue', id: 100)]);
      final src = generateDartFile(file, [file, kv]);

      expect(src, contains('KeyValueReader'));
      expect(src, contains('Uint8List? get key => getAnyPointerAsMessageBytes(0)'));
      expect(src, contains('Uint8List? get value => getAnyPointerAsMessageBytes(1)'));
    });

    test('TypeParameterRefType field generates AnyPointer setter in template builder', () {
      final kv = keyValueTemplate();
      final file = fileNode(1, [SchemaNestedNode(name: 'KeyValue', id: 100)]);
      final src = generateDartFile(file, [file, kv]);

      expect(src, contains('set key(Uint8List? v)'));
      expect(src, contains('set value(Uint8List? v)'));
      expect(src, contains('setAnyPointerFromMessage(0, v)'));
    });

    test('concrete StructRefType with typeArgs generates specialized reader class', () {
      final kv = keyValueTemplate();
      final outer = structNode(
        200,
        'Wrapper',
        0,
        1,
        [
          ptrField('pair', 0, 0,
              StructRefType(100, typeArgs: [const TextType(), const TextType()])),
        ],
      );
      final file = fileNode(1, [
        SchemaNestedNode(name: 'KeyValue', id: 100),
        SchemaNestedNode(name: 'Wrapper', id: 200),
      ]);
      final src = generateDartFile(file, [file, kv, outer]);

      expect(src, contains('final class KeyValueTextTextReader extends StructReader'));
      expect(src, contains("String? get key => getTextField(0)"));
      expect(src, contains("String? get value => getTextField(1)"));
      expect(src,
          contains('KeyValueTextTextReader? get pair => getStructFieldWith(0, (r) => KeyValueTextTextReader(r))'));
    });

    test('concrete StructRefType in List field generates specialized list reader', () {
      final kv = keyValueTemplate();
      final outer = structNode(
        200,
        'Config',
        0,
        1,
        [
          ptrField('entries', 0, 0,
              ListType(StructRefType(100, typeArgs: [const TextType(), const TextType()]))),
        ],
      );
      final file = fileNode(1, [
        SchemaNestedNode(name: 'KeyValue', id: 100),
        SchemaNestedNode(name: 'Config', id: 200),
      ]);
      final src = generateDartFile(file, [file, kv, outer]);

      expect(src, contains('final class KeyValueTextTextReader extends StructReader'));
      expect(src,
          contains('ListReader<KeyValueTextTextReader>? get entries => getStructListFieldWith(0, (r) => KeyValueTextTextReader(r))'));
    });

    test('template class is still generated alongside specialized class', () {
      final kv = keyValueTemplate();
      final outer = structNode(
        200,
        'Wrapper',
        0,
        1,
        [
          ptrField('pair', 0, 0,
              StructRefType(100, typeArgs: [const TextType(), const TextType()])),
        ],
      );
      final file = fileNode(1, [
        SchemaNestedNode(name: 'KeyValue', id: 100),
        SchemaNestedNode(name: 'Wrapper', id: 200),
      ]);
      final src = generateDartFile(file, [file, kv, outer]);

      expect(src, contains('final class KeyValueReader extends StructReader'));
      expect(src, contains('final class KeyValueTextTextReader extends StructReader'));
    });
  });

  group('generateDartFile — capability-returning methods (GEN-002)', () {
    const sessionIfaceId = 40;
    const greeterIfaceId = 0x1234abcd;
    const paramsId = 41;
    const resultsId = 42;

    // A result struct with a single cap field at ptr slot 0.
    SchemaNode capResultNode() => structNode(resultsId, 'NewSessionResults', 0, 1, [
          ptrField('session', 0, 0, InterfaceRefType(sessionIfaceId)),
        ]);

    SchemaNode sessionIfaceNode() => SchemaNode(
          id: sessionIfaceId,
          displayName: 'test.capnp:Session',
          displayNamePrefixLength: 'test.capnp:'.length,
          scopeId: 1,
          nestedNodes: const [],
          body: InterfaceBody(methods: const [], superclassIds: const []),
        );

    late String src;
    setUp(() {
      final paramsNode = structNode(paramsId, 'NewSessionParams', 0, 1, [
        ptrField('name', 0, 0, const TextType()),
      ]);
      final resultsNode = capResultNode();
      final sessionIface = sessionIfaceNode();
      final greeterIface = interfaceNode(greeterIfaceId, 'Greeter', [
        SchemaMethod(
          name: 'newSession',
          ordinal: 0,
          paramStructTypeId: paramsId,
          resultStructTypeId: resultsId,
        ),
      ]);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'Session', id: sessionIfaceId),
        SchemaNestedNode(name: 'Greeter', id: greeterIfaceId),
      ]);
      src = generateDartFile(
          file, [file, paramsNode, resultsNode, sessionIface, greeterIface]);
    });

    test('always returns Future<XxxResultsReader>, not XxxClient', () {
      expect(src, contains('Future<NewSessionResultsReader> newSession('));
      expect(src, isNot(contains('SessionClient newSession(')));
    });

    test('also generates a pipeline method', () {
      expect(src, contains('GreeterNewSessionPipeline newSessionPipeline('));
      expect(src, contains('beginDispatch('));
    });

    test('pipeline class uses correct ptr slot (not hardcoded 0)', () {
      expect(src, contains('final class GreeterNewSessionPipeline'));
      expect(src, contains('call.pipelineResult(0)'));
    });

    test('pipeline class exposes typed cap getter and result future', () {
      expect(src, contains('final SessionClient session;'));
      expect(src, contains('final Future<NewSessionResultsReader> result;'));
    });

    test('cap field at non-zero ptr slot uses correct index', () {
      // Put the cap at ptr slot 2 (after two text fields).
      final resultsNodeSlot2 = structNode(resultsId + 10, 'GetResults', 0, 3, [
        ptrField('name', 0, 0, const TextType()),
        ptrField('desc', 1, 1, const TextType()),
        ptrField('session', 2, 2, InterfaceRefType(sessionIfaceId)),
      ]);
      final sessionIface = sessionIfaceNode();
      final greeterIface = interfaceNode(greeterIfaceId, 'Svc', [
        SchemaMethod(
          name: 'get',
          ordinal: 0,
          paramStructTypeId: paramsId,
          resultStructTypeId: resultsId + 10,
        ),
      ]);
      final paramsNode = structNode(paramsId, 'GetParams', 0, 0, []);
      final file = fileNode(1, [
        SchemaNestedNode(name: 'Session', id: sessionIfaceId),
        SchemaNestedNode(name: 'Svc', id: greeterIfaceId),
      ]);
      final s = generateDartFile(
          file, [file, paramsNode, resultsNodeSlot2, sessionIface, greeterIface]);

      expect(s, contains('call.pipelineResult(2)'));
      expect(s, isNot(contains('call.pipelineResult(0)')));
    });
  });

  group('generateDartFiles — codegen entrypoint', () {
    test('maps .capnp filename to .capnp.dart', () {
      final sNode = structNode(20, 'Msg', 1, 0, [
        dataField('x', 0, 0, const Int32Type()),
      ]);
      final file = fileNode(1, [SchemaNestedNode(name: 'Msg', id: 20)]);
      final request = CodeGeneratorRequest(
        nodes: [file, sNode],
        requestedFiles: [RequestedFile(id: 1, filename: 'proto/msg.capnp')],
      );
      final results = generateDartFiles(request);

      expect(results.keys, contains('proto/msg.capnp.dart'));
      expect(results['proto/msg.capnp.dart'], contains('MsgReader'));
    });
  });
}
