// Generated by capnpc-dart from this schema (verified against the real
// `capnp` CLI's actual text-format output/input — see text_format_test.dart):
//
//   enum SmallEnum { only @0; }
//   struct Extras {
//     i8 @0 :Int8;
//     i64 @1 :Int64;
//     u64 @2 :UInt64;
//     f32 @3 :Float32;
//     count @4 :UInt32 = 5;
//     pos :group { gx @5 :Int32; gy @6 :Int32; }
//     small @7 :SmallEnum;
//     union { ua @8 :Int32; ub @9 :Bool; uc @10 :Text; }
//   }
//
// Exists specifically to cover text-format cases `widget_fixture.dart`
// doesn't: a group field, an out-of-range/unknown enumerant, integer
// boundary values wider than Int32/UInt32, a Float32 field (whose rounding
// behavior differs from Float64 — see `_formatFloat32` in text_format.dart),
// and a field with a non-zero explicit default.
//
// ignore_for_file: annotate_overrides, unnecessary_this

import 'package:capnproto_dart/capnproto_dart.dart';

enum SmallEnum { only }

const EnumSchemaInfo smallEnumSchema = EnumSchemaInfo(
  id: 0x8e671081d221056c,
  displayName: 'extras.capnp:SmallEnum',
  shortName: 'SmallEnum',
  enumerants: [EnumerantSchemaInfo(name: 'only', codeOrder: 0, ordinal: 0)],
);

SmallEnum? smallEnumFromUint16(int v) =>
    v < SmallEnum.values.length ? SmallEnum.values[v] : null;
int smallEnumToUint16(SmallEnum v) => v.index;

final class PosReader extends StructReader {
  PosReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = posSchema;

  int get gx => getInt32Field(28);

  int get gy => getInt32Field(32);
}

final class PosBuilder extends StructBuilder {
  PosBuilder(super.raw);

  @override
  PosReader asReader() => PosReader(rawToReader());

  set gx(int v) {
    setInt32Field(28, v);
  }

  set gy(int v) {
    setInt32Field(32, v);
  }
}

const StructSchemaInfo posSchema = StructSchemaInfo(
  id: 0xfee20a3b882e197f,
  displayName: 'extras.capnp:Extras.pos',
  shortName: 'pos',
  dataWords: 6,
  pointerWords: 1,
  isGroup: true,
  fields: [
    FieldSchemaInfo(
      name: 'gx',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(offset: 7, type: PrimitiveTypeSchemaInfo('Int32')),
    ),
    FieldSchemaInfo(
      name: 'gy',
      codeOrder: 1,
      body: SlotFieldSchemaInfo(offset: 8, type: PrimitiveTypeSchemaInfo('Int32')),
    ),
  ],
);

final class ExtrasReader extends StructReader {
  ExtrasReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = extrasSchema;

  int get which => getUint16Field(40);

  int get i8 => getInt8Field(0);

  int get i64 => getInt64Field(8);

  int get u64 => getUint64Field(16);

  double get f32 => getFloat32Field(4);

  int get count => getUint32Field(24, defaultValue: 5);

  PosReader get pos => PosReader(raw, capabilities: capabilityTable);

  SmallEnum? get small => smallEnumFromUint16(getUint16Field(2));

  int get ua => getInt32Field(36);

  bool get ub => getBoolField(288);

  String? get uc => getTextField(0);
}

final class ExtrasBuilder extends StructBuilder {
  ExtrasBuilder(super.raw);

  @override
  ExtrasReader asReader() => ExtrasReader(rawToReader());

  set i8(int v) {
    setInt8Field(0, v);
  }

  set i64(int v) {
    setInt64Field(8, v);
  }

  set u64(int v) {
    setUint64Field(16, v);
  }

  set f32(double v) {
    setFloat32Field(4, v);
  }

  set count(int v) {
    setUint32Field(24, v, defaultValue: 5);
  }

  PosBuilder get pos => PosBuilder(raw);

  set small(SmallEnum v) {
    setUint16Field(2, smallEnumToUint16(v));
  }

  /// Writes a raw (possibly out-of-range) enumerant ordinal directly,
  /// bypassing the [SmallEnum]-typed setter — used to simulate a message
  /// produced under a newer schema version with more enumerants than this
  /// one knows about (schema evolution), which is the only way to observe
  /// `encodeText`'s unknown-enumerant fallback without a second real schema.
  set smallRaw(int v) {
    setUint16Field(2, v);
  }

  set ua(int v) {
    setUint16Field(40, 0);
    setInt32Field(36, v);
  }

  set ub(bool v) {
    setUint16Field(40, 1);
    setBoolField(288, v);
  }

  set uc(String? v) {
    setUint16Field(40, 2);
    setTextField(0, v);
  }
}

final class _ExtrasFactory extends StructFactory<ExtrasReader, ExtrasBuilder> {
  @override
  StructSchemaInfo get schema => extrasSchema;
  @override
  int get dataWords => 6;
  @override
  int get ptrWords => 1;
  @override
  ExtrasReader fromRawReader(RawStructReader r) => ExtrasReader(r);
  @override
  ExtrasReader fromRawReaderWithCapabilities(
    RawStructReader r,
    List<Object?> capabilities,
  ) => ExtrasReader(r, capabilities: capabilities);
  @override
  ExtrasBuilder fromRawBuilder(RawStructBuilder r) => ExtrasBuilder(r);
}

const StructSchemaInfo extrasSchema = StructSchemaInfo(
  id: 0xc11f5a14219c89c3,
  displayName: 'extras.capnp:Extras',
  shortName: 'Extras',
  dataWords: 6,
  pointerWords: 1,
  discriminantCount: 3,
  discriminantOffset: 20,
  fields: [
    FieldSchemaInfo(
      name: 'i8',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(offset: 0, type: PrimitiveTypeSchemaInfo('Int8')),
    ),
    FieldSchemaInfo(
      name: 'i64',
      codeOrder: 1,
      body: SlotFieldSchemaInfo(offset: 1, type: PrimitiveTypeSchemaInfo('Int64')),
    ),
    FieldSchemaInfo(
      name: 'u64',
      codeOrder: 2,
      body: SlotFieldSchemaInfo(offset: 2, type: PrimitiveTypeSchemaInfo('UInt64')),
    ),
    FieldSchemaInfo(
      name: 'f32',
      codeOrder: 3,
      body: SlotFieldSchemaInfo(offset: 1, type: PrimitiveTypeSchemaInfo('Float32')),
    ),
    FieldSchemaInfo(
      name: 'count',
      codeOrder: 4,
      body: SlotFieldSchemaInfo(
        offset: 6,
        type: PrimitiveTypeSchemaInfo('UInt32'),
        hadExplicitDefault: true,
        defaultValue: 5,
      ),
    ),
    FieldSchemaInfo(
      name: 'pos',
      codeOrder: 5,
      body: GroupFieldSchemaInfo(typeId: 0xfee20a3b882e197f),
    ),
    FieldSchemaInfo(
      name: 'small',
      codeOrder: 6,
      body: SlotFieldSchemaInfo(
        offset: 1,
        type: EnumRefTypeSchemaInfo(0x8e671081d221056c),
      ),
    ),
    FieldSchemaInfo(
      name: 'ua',
      codeOrder: 7,
      discriminantValue: 0,
      body: SlotFieldSchemaInfo(offset: 9, type: PrimitiveTypeSchemaInfo('Int32')),
    ),
    FieldSchemaInfo(
      name: 'ub',
      codeOrder: 8,
      discriminantValue: 1,
      body: SlotFieldSchemaInfo(offset: 288, type: PrimitiveTypeSchemaInfo('Bool')),
    ),
    FieldSchemaInfo(
      name: 'uc',
      codeOrder: 9,
      discriminantValue: 2,
      body: SlotFieldSchemaInfo(offset: 0, type: PrimitiveTypeSchemaInfo('Text')),
    ),
  ],
);

final extrasFactory = _ExtrasFactory();
