// Generated by capnpc-dart from this schema (verified against the real
// `capnp` CLI's actual text-format output/input — see text_format_test.dart):
//
//   enum Level {
//     low @0;
//     high @2;
//     medium @1;
//   }
//   struct Signal {
//     level @0 :Level;
//   }
//
// Level's `@N`s are deliberately out of declaration order — regression
// fixture for the enum codeOrder-vs-ordinal bug (a schema whose enum
// declaration order differs from its explicit wire values used to make
// capnpc-dart generate a Dart `enum` whose `.index` didn't match the real
// wire value at all — see dart_generator.dart's `_writeEnum`).
//
// ignore_for_file: annotate_overrides, unnecessary_this

import 'package:capnproto_dart/capnproto_dart.dart';

enum Level { low, medium, high }

const EnumSchemaInfo levelSchema = EnumSchemaInfo(
  id: 0xac95babbb17f8d00,
  displayName: 'signal.capnp:Level',
  shortName: 'Level',
  enumerants: [
    EnumerantSchemaInfo(name: 'low', codeOrder: 0, ordinal: 0),
    EnumerantSchemaInfo(name: 'medium', codeOrder: 2, ordinal: 1),
    EnumerantSchemaInfo(name: 'high', codeOrder: 1, ordinal: 2),
  ],
);

Level? levelFromUint16(int v) =>
    v < Level.values.length ? Level.values[v] : null;
int levelToUint16(Level v) => v.index;

final class SignalReader extends StructReader {
  SignalReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = signalSchema;

  Level? get level => levelFromUint16(getUint16Field(0));
}

final class SignalBuilder extends StructBuilder {
  SignalBuilder(super.raw);

  @override
  SignalReader asReader() => SignalReader(rawToReader());

  set level(Level v) {
    setUint16Field(0, levelToUint16(v));
  }
}

final class _SignalFactory extends StructFactory<SignalReader, SignalBuilder> {
  @override
  StructSchemaInfo get schema => signalSchema;
  @override
  int get dataWords => 1;
  @override
  int get ptrWords => 0;
  @override
  SignalReader fromRawReader(RawStructReader r) => SignalReader(r);
  @override
  SignalReader fromRawReaderWithCapabilities(
    RawStructReader r,
    List<Object?> capabilities,
  ) => SignalReader(r, capabilities: capabilities);
  @override
  SignalBuilder fromRawBuilder(RawStructBuilder r) => SignalBuilder(r);
}

const StructSchemaInfo signalSchema = StructSchemaInfo(
  id: 0xb9c5b173a45a69c0,
  displayName: 'signal.capnp:Signal',
  shortName: 'Signal',
  dataWords: 1,
  pointerWords: 0,
  fields: [
    FieldSchemaInfo(
      name: 'level',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(
        offset: 0,
        type: EnumRefTypeSchemaInfo(0xac95babbb17f8d00),
      ),
    ),
  ],
);

final signalFactory = _SignalFactory();
