// Generated by capnpc-dart from this schema (verified against the real
// `capnp` CLI's actual text-format output/input — see text_format_test.dart):
//
//   enum Color { red @0; green @1; blue @2; }
//   struct Point { x @0 :Int32; y @1 :Int32; }
//   struct Widget {
//     name @0 :Text;
//     tag @1 :Data;
//     size @2 :UInt32;
//     ratio @3 :Float64;
//     active @4 :Bool;
//     color @5 :Color;
//     origin @6 :Point;
//     tags @7 :List(Text);
//     points @8 :List(Point);
//     nums @9 :List(Int32);
//     union { a @10 :Int32; b @11 :Text; }
//   }
//
// ignore_for_file: annotate_overrides, unnecessary_this

import 'dart:typed_data';
import 'package:capnproto_dart/capnproto_dart.dart';

enum Color {
  red,
  green,
  blue,
}

const EnumSchemaInfo colorSchema = EnumSchemaInfo(
  id: 0x80378f2b1b82c661,
  displayName: 'test.capnp:Color',
  shortName: 'Color',
  enumerants: [
    EnumerantSchemaInfo(
      name: 'red',
      codeOrder: 0,
    ),
    EnumerantSchemaInfo(
      name: 'green',
      codeOrder: 1,
    ),
    EnumerantSchemaInfo(
      name: 'blue',
      codeOrder: 2,
    ),
  ],
);

Color? colorFromUint16(int v) => v < Color.values.length ? Color.values[v] : null;
int colorToUint16(Color v) => v.index;

final class PointReader extends StructReader {
  PointReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = pointSchema;

  int get x => getInt32Field(0);

  int get y => getInt32Field(4);
}

final class PointBuilder extends StructBuilder {
  PointBuilder(super.raw);

  @override
  PointReader asReader() => PointReader(rawToReader());

  set x(int v) {
    setInt32Field(0, v);
  }

  set y(int v) {
    setInt32Field(4, v);
  }
}

final class _PointFactory
    extends StructFactory<PointReader, PointBuilder> {
  @override StructSchemaInfo get schema => pointSchema;
  @override int get dataWords => 1;
  @override int get ptrWords => 0;
  @override
  PointReader fromRawReader(RawStructReader r) => PointReader(r);
  @override
  PointReader fromRawReaderWithCapabilities(RawStructReader r, List<Object?> capabilities) => PointReader(r, capabilities: capabilities);
  @override
  PointBuilder fromRawBuilder(RawStructBuilder r) => PointBuilder(r);
}

const StructSchemaInfo pointSchema = StructSchemaInfo(
  id: 0x919eb07f75e36046,
  displayName: 'test.capnp:Point',
  shortName: 'Point',
  dataWords: 1,
  pointerWords: 0,
  fields: [
    FieldSchemaInfo(
      name: 'x',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(
        offset: 0,
        type: PrimitiveTypeSchemaInfo('Int32'),
      ),
    ),
    FieldSchemaInfo(
      name: 'y',
      codeOrder: 1,
      body: SlotFieldSchemaInfo(
        offset: 1,
        type: PrimitiveTypeSchemaInfo('Int32'),
      ),
    ),
  ],
);

final pointFactory = _PointFactory();

final class WidgetReader extends StructReader {
  WidgetReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = widgetSchema;

  int get which => getUint16Field(20);

  String? get name => getTextField(0);

  Uint8List? get tag => getDataField(1);

  int get size => getUint32Field(0);

  double get ratio => getFloat64Field(8);

  bool get active => getBoolField(32);

  Color? get color => colorFromUint16(getUint16Field(6));

  PointReader? get origin => getStructFieldWith(2, (r) => PointReader(r, capabilities: capabilityTable));

  ListReader<String?>? get tags => getTextListField(3);

  ListReader<PointReader>? get points => getStructListFieldWith(4, (r) => PointReader(r, capabilities: capabilityTable));

  ListReader<int>? get nums => getInt32ListField(5);

  int get a => getInt32Field(16);

  String? get b => getTextField(6);
}

final class WidgetBuilder extends StructBuilder {
  WidgetBuilder(super.raw);

  @override
  WidgetReader asReader() => WidgetReader(rawToReader());

  void _setWhich(int v) => setUint16Field(20, v);

  set name(String? v) {
    setTextField(0, v);
  }

  set tag(Uint8List? v) {
    setDataField(1, v);
  }

  set size(int v) {
    setUint32Field(0, v);
  }

  set ratio(double v) {
    setFloat64Field(8, v);
  }

  set active(bool v) {
    setBoolField(32, v);
  }

  set color(Color v) {
    setUint16Field(6, colorToUint16(v));
  }

  PointBuilder initOrigin() {
    return initStructFieldWith(2,
        (r) => PointBuilder(r), 1, 0);
  }

  bool hasOrigin() => hasPointerField(2);

  ListBuilder<String?> initTags(int length) {
    return initTextListField(3, length);
  }

  ListBuilder<PointBuilder> initPoints(int length) {
    return initStructListFieldWith(4, length, (r) => PointBuilder(r), 1, 0);
  }

  ListBuilder<int> initNums(int length) {
    return initInt32ListField(5, length);
  }

  set a(int v) {
    setUint16Field(20, 0);
    setInt32Field(16, v);
  }

  set b(String? v) {
    setUint16Field(20, 1);
    setTextField(6, v);
  }
}

final class _WidgetFactory
    extends StructFactory<WidgetReader, WidgetBuilder> {
  @override StructSchemaInfo get schema => widgetSchema;
  @override int get dataWords => 3;
  @override int get ptrWords => 7;
  @override
  WidgetReader fromRawReader(RawStructReader r) => WidgetReader(r);
  @override
  WidgetReader fromRawReaderWithCapabilities(RawStructReader r, List<Object?> capabilities) => WidgetReader(r, capabilities: capabilities);
  @override
  WidgetBuilder fromRawBuilder(RawStructBuilder r) => WidgetBuilder(r);
}

const StructSchemaInfo widgetSchema = StructSchemaInfo(
  id: 0xb11d9f3d0764f1f5,
  displayName: 'test.capnp:Widget',
  shortName: 'Widget',
  dataWords: 3,
  pointerWords: 7,
  discriminantCount: 2,
  discriminantOffset: 10,
  fields: [
    FieldSchemaInfo(
      name: 'name',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(
        offset: 0,
        type: PrimitiveTypeSchemaInfo('Text'),
      ),
    ),
    FieldSchemaInfo(
      name: 'tag',
      codeOrder: 1,
      body: SlotFieldSchemaInfo(
        offset: 1,
        type: PrimitiveTypeSchemaInfo('Data'),
      ),
    ),
    FieldSchemaInfo(
      name: 'size',
      codeOrder: 2,
      body: SlotFieldSchemaInfo(
        offset: 0,
        type: PrimitiveTypeSchemaInfo('UInt32'),
      ),
    ),
    FieldSchemaInfo(
      name: 'ratio',
      codeOrder: 3,
      body: SlotFieldSchemaInfo(
        offset: 1,
        type: PrimitiveTypeSchemaInfo('Float64'),
      ),
    ),
    FieldSchemaInfo(
      name: 'active',
      codeOrder: 4,
      body: SlotFieldSchemaInfo(
        offset: 32,
        type: PrimitiveTypeSchemaInfo('Bool'),
      ),
    ),
    FieldSchemaInfo(
      name: 'color',
      codeOrder: 5,
      body: SlotFieldSchemaInfo(
        offset: 3,
        type: EnumRefTypeSchemaInfo(0x80378f2b1b82c661),
      ),
    ),
    FieldSchemaInfo(
      name: 'origin',
      codeOrder: 6,
      body: SlotFieldSchemaInfo(
        offset: 2,
        type: StructRefTypeSchemaInfo(0x919eb07f75e36046),
      ),
    ),
    FieldSchemaInfo(
      name: 'tags',
      codeOrder: 7,
      body: SlotFieldSchemaInfo(
        offset: 3,
        type: ListTypeSchemaInfo(PrimitiveTypeSchemaInfo('Text')),
      ),
    ),
    FieldSchemaInfo(
      name: 'points',
      codeOrder: 8,
      body: SlotFieldSchemaInfo(
        offset: 4,
        type: ListTypeSchemaInfo(StructRefTypeSchemaInfo(0x919eb07f75e36046)),
      ),
    ),
    FieldSchemaInfo(
      name: 'nums',
      codeOrder: 9,
      body: SlotFieldSchemaInfo(
        offset: 5,
        type: ListTypeSchemaInfo(PrimitiveTypeSchemaInfo('Int32')),
      ),
    ),
    FieldSchemaInfo(
      name: 'a',
      codeOrder: 10,
      discriminantValue: 0,
      body: SlotFieldSchemaInfo(
        offset: 4,
        type: PrimitiveTypeSchemaInfo('Int32'),
      ),
    ),
    FieldSchemaInfo(
      name: 'b',
      codeOrder: 11,
      discriminantValue: 1,
      body: SlotFieldSchemaInfo(
        offset: 6,
        type: PrimitiveTypeSchemaInfo('Text'),
      ),
    ),
  ],
);

final widgetFactory = _WidgetFactory();

