import '../schema/schema_model.dart';

/// Generates a single Dart source file from a set of [SchemaNode]s that
/// belong to a given file node.
String generateDartFile(
  SchemaNode fileNode,
  List<SchemaNode> allNodes, {
  String packageName = 'capnproto_dart',
}) {
  final nodeMap = {for (final n in allNodes) n.id: n};
  final sb = StringBuffer();

  final structs = <SchemaNode>[];
  final enums = <SchemaNode>[];
  final interfaces = <SchemaNode>[];
  _collectNodes(fileNode, nodeMap, structs, enums, interfaces);

  sb.writeln('// Generated by capnpc-dart — do not edit by hand.');
  sb.writeln('// ignore_for_file: annotate_overrides, unnecessary_this');
  sb.writeln();
  sb.writeln("import 'dart:typed_data';");
  sb.writeln("import 'package:$packageName/$packageName.dart';");
  if (interfaces.isNotEmpty) {
    sb.writeln("import 'package:capnproto_dart_rpc/capnproto_dart_rpc.dart';");
  }
  sb.writeln();

  for (final node in enums) {
    _writeEnum(sb, node, node.body as EnumBody);
    sb.writeln();
  }

  for (final node in structs) {
    _writeStruct(sb, node, node.body as StructBody, nodeMap);
    sb.writeln();
  }

  final groups = <SchemaNode>[];
  final groupSeen = <int>{};
  for (final node in structs) {
    _collectGroups(node, nodeMap, groups, groupSeen);
  }
  for (final node in groups) {
    _writeStruct(sb, node, node.body as StructBody, nodeMap);
    sb.writeln();
  }

  for (final node in interfaces) {
    _writeInterface(sb, node, node.body as InterfaceBody, nodeMap);
    sb.writeln();
  }

  // Pre-collect all concrete generic instantiations and emit specialized readers.
  final specializations = <String, ({int nodeId, List<SchemaType> typeArgs})>{};
  final allStructNodes = [...structs, ...groups];
  for (final node in allStructNodes) {
    _collectNodeFieldSpecializations(node, nodeMap, specializations);
  }
  for (final entry in specializations.entries) {
    _writeSpecializedStruct(sb, entry.key, entry.value.nodeId, entry.value.typeArgs, nodeMap);
    sb.writeln();
  }

  return sb.toString();
}

void _collectNodes(
  SchemaNode root,
  Map<int, SchemaNode> nodeMap,
  List<SchemaNode> structs,
  List<SchemaNode> enums,
  List<SchemaNode> interfaces,
) {
  for (final nested in root.nestedNodes) {
    final node = nodeMap[nested.id];
    if (node == null) continue;
    if (node.body is StructBody) {
      final body = node.body as StructBody;
      if (!body.isGroup) structs.add(node);
      _collectNodes(node, nodeMap, structs, enums, interfaces);
    } else if (node.body is EnumBody) {
      enums.add(node);
    } else if (node.body is InterfaceBody) {
      interfaces.add(node);
      final iface = node.body as InterfaceBody;
      for (final method in iface.methods) {
        for (final id in [method.paramStructTypeId, method.resultStructTypeId]) {
          final ms = nodeMap[id];
          if (ms != null && ms.body is StructBody) {
            final sb = ms.body as StructBody;
            if (!sb.isGroup) structs.add(ms);
          }
        }
      }
    }
  }
}

void _collectGroups(
  SchemaNode node,
  Map<int, SchemaNode> nodeMap,
  List<SchemaNode> groups,
  Set<int> seen,
) {
  final body = node.body;
  if (body is! StructBody) return;
  for (final field in body.fields) {
    if (field.body is! GroupField) continue;
    final gf = field.body as GroupField;
    if (seen.contains(gf.typeId)) continue;
    final groupNode = nodeMap[gf.typeId];
    if (groupNode == null) continue;
    seen.add(gf.typeId);
    groups.add(groupNode);
    _collectGroups(groupNode, nodeMap, groups, seen);
  }
}

// ---------------------------------------------------------------------------
// Interface generation
// ---------------------------------------------------------------------------

void _writeInterface(
  StringBuffer sb,
  SchemaNode node,
  InterfaceBody body,
  Map<int, SchemaNode> nodeMap,
) {
  final name = _dartClassName(node.displayName);

  // Collect all methods including inherited ones (depth-first from ancestors).
  final rawMethods = <({SchemaNode ifaceNode, SchemaMethod method})>[];
  _collectAllMethods(node, body, nodeMap, rawMethods, {});

  // Detect name conflicts: a method name is conflicted when it appears in 2+
  // *different* interface nodes.  Same-interface names are impossible (Cap'n
  // Proto schemas forbid duplicate method names per interface).
  final nameToIfaceIds = <String, Set<int>>{};
  for (final m in rawMethods) {
    (nameToIfaceIds[_camel(m.method.name)] ??= {}).add(m.ifaceNode.id);
  }
  final conflictedNames = {
    for (final e in nameToIfaceIds.entries)
      if (e.value.length > 1) e.key,
  };

  // Resolve the Dart-level method name (prefixed when there is a conflict).
  String resolveDartName(SchemaNode ifaceNode, SchemaMethod method) {
    final camel = _camel(method.name);
    if (!conflictedNames.contains(camel)) return camel;
    final shortIface = _dartClassName(ifaceNode.displayName);
    return '${_lcfirst(shortIface)}${_ucfirst(camel)}';
  }

  final allMethods = rawMethods
      .map((m) => (
            ifaceNode: m.ifaceNode,
            method: m.method,
            dartName: resolveDartName(m.ifaceNode, m.method),
          ))
      .toList();

  // ---- Pipeline classes (one per method whose result has interface fields) ----
  for (final m in allMethods) {
    _writeResultsPipeline(sb, name, m.method, nodeMap, m.dartName);
  }

  // ---- Client stub ----
  sb.writeln('class ${name}Client extends Capability {');
  sb.writeln('  static const int _interfaceId = ${_hexId(node.id)};');
  sb.writeln();
  sb.writeln('  final Capability _cap;');
  sb.writeln('  ${name}Client(this._cap);');

  for (final m in allMethods) {
    _writeClientMethod(sb, name, m.ifaceNode, m.method, nodeMap, m.dartName);
  }

  sb.writeln();
  sb.writeln('  @override');
  sb.writeln('  Future<void> dispose() => _cap.dispose();');
  sb.writeln('}');
  sb.writeln();

  // ---- Factory ----
  sb.writeln(
      'class ${name}ClientFactory extends CapabilityFactory<${name}Client> {');
  sb.writeln('  @override');
  sb.writeln(
      '  ${name}Client fromCapability(Capability cap) => ${name}Client(cap);');
  sb.writeln('}');
  sb.writeln();

  // ---- Server stub ----
  _writeServerStub(sb, node, allMethods, nodeMap);
}

/// Depth-first collection of all methods reachable via inheritance.
/// Each method retains its defining interface node; the wire-level method ID
/// is carried in `method.ordinal`.
void _collectAllMethods(
  SchemaNode ifaceNode,
  InterfaceBody body,
  Map<int, SchemaNode> nodeMap,
  List<({SchemaNode ifaceNode, SchemaMethod method})> result,
  Set<int> seen,
) {
  if (seen.contains(ifaceNode.id)) return;
  seen.add(ifaceNode.id);

  for (final scId in body.superclassIds) {
    final scNode = nodeMap[scId];
    if (scNode == null || scNode.body is! InterfaceBody) continue;
    _collectAllMethods(
        scNode, scNode.body as InterfaceBody, nodeMap, result, seen);
  }

  for (final method in body.methods) {
    result.add((ifaceNode: ifaceNode, method: method));
  }
}

void _writeClientMethod(
  StringBuffer sb,
  String ifaceName,
  SchemaNode ifaceNode,
  SchemaMethod method,
  Map<int, SchemaNode> nodeMap,
  String dartName,
) {
  final methodName = dartName;
  final paramsNode = nodeMap[method.paramStructTypeId];
  final resultsNode = nodeMap[method.resultStructTypeId];
  final paramsName = _dartClassName(paramsNode?.displayName ?? 'Unknown');
  final resultsName = _dartClassName(resultsNode?.displayName ?? 'Unknown');
  final ifaceId = _hexId(ifaceNode.id);
  final ordinal = method.ordinal;

  final capParams = _collectCapParams(paramsNode);
  final capResults = _collectCapResults(resultsNode);
  final hasPipeline = capResults.isNotEmpty;

  final namedParams = capParams.isEmpty
      ? ''
      : ', {${capParams.map((p) => 'required Capability ${p.$2}').join(', ')}}';
  final capsList = capParams.map((p) => p.$2).join(', ');
  final dispatchCaps =
      capParams.isEmpty ? '' : ', paramsCapabilities: [$capsList]';

  sb.writeln();

  // ---- Normal async method (always returns Future<XxxResultsReader>) ----
  sb.writeln(
      '  Future<${resultsName}Reader> $methodName(void Function(${paramsName}Builder) build$namedParams) async {');
  sb.writeln('    final mb = MessageBuilder();');
  if (capParams.isEmpty) {
    sb.writeln('    build(mb.initRoot(${_lcfirst(paramsName)}Factory));');
  } else {
    sb.writeln('    final b = mb.initRoot(${_lcfirst(paramsName)}Factory);');
    for (final (_, fname, capIdx) in capParams) {
      sb.writeln('    b.set${_ucfirst(fname)}($capIdx);');
    }
    sb.writeln('    build(b);');
  }
  sb.writeln(
      '    final result = await _cap.dispatch($ifaceId, $ordinal, mb.serialize()$dispatchCaps);');
  sb.writeln(
      '    return MessageReader.deserialize(result.bytes).getRoot(${_lcfirst(resultsName)}Factory);');
  sb.writeln('  }');

  // ---- Pipeline method (only when result has interface fields) ----
  if (hasPipeline) {
    final pipelineName = '${ifaceName}${_ucfirst(methodName)}Pipeline';
    sb.writeln();
    sb.writeln(
        '  $pipelineName ${methodName}Pipeline(void Function(${paramsName}Builder) build$namedParams) {');
    sb.writeln('    final mb = MessageBuilder();');
    if (capParams.isEmpty) {
      sb.writeln('    build(mb.initRoot(${_lcfirst(paramsName)}Factory));');
    } else {
      sb.writeln('    final b = mb.initRoot(${_lcfirst(paramsName)}Factory);');
      for (final (_, fname, capIdx) in capParams) {
        sb.writeln('    b.set${_ucfirst(fname)}($capIdx);');
      }
      sb.writeln('    build(b);');
    }
    sb.writeln(
        '    return $pipelineName._(_cap.beginDispatch($ifaceId, $ordinal, mb.serialize()$dispatchCaps));');
    sb.writeln('  }');
  }
}

/// Returns the [InterfaceRefType] fields (sorted by codeOrder) in [paramsNode]
/// as a list of `(ptrOffset, fieldName, capTableIndex)`.
List<(int, String, int)> _collectCapParams(SchemaNode? paramsNode) {
  if (paramsNode == null) return const [];
  final body = paramsNode.body;
  if (body is! StructBody) return const [];

  final fields = [...body.fields]
    ..sort((a, b) => a.codeOrder.compareTo(b.codeOrder));
  final result = <(int, String, int)>[];
  int capIdx = 0;
  for (final field in fields) {
    if (field.body is! SlotField) continue;
    final sf = field.body as SlotField;
    if (sf.type is InterfaceRefType) {
      result.add((sf.offset, _camel(field.name), capIdx++));
    }
  }
  return result;
}

/// Returns true if [resultsNode] represents an effectively-void result struct.
bool _isVoidResultStruct(SchemaNode? resultsNode) {
  if (resultsNode == null) return true;
  final body = resultsNode.body;
  if (body is! StructBody) return true;
  if (body.dataWordCount == 0 && body.pointerCount == 0) return true;
  return body.fields.every((f) {
    if (f.body is! SlotField) return false;
    return (f.body as SlotField).type is VoidType;
  });
}

void _writeServerStub(
  StringBuffer sb,
  SchemaNode node,
  List<({SchemaNode ifaceNode, SchemaMethod method, String dartName})> allMethods,
  Map<int, SchemaNode> nodeMap,
) {
  final name = _dartClassName(node.displayName);

  sb.writeln('abstract class ${name}Server extends Capability {');

  for (final m in allMethods) {
    final method = m.method;
    final paramsNode = nodeMap[method.paramStructTypeId];
    final resultsNode = nodeMap[method.resultStructTypeId];
    final methodName = m.dartName;
    final paramsName = _dartClassName(paramsNode?.displayName ?? 'Unknown');
    final isVoid = _isVoidResultStruct(resultsNode);

    sb.writeln();
    if (isVoid) {
      sb.writeln(
          '  Future<void> $methodName(${paramsName}Reader params, List<Capability> paramsCapabilities);');
    } else {
      sb.writeln(
          '  Future<DispatchResult> $methodName(${paramsName}Reader params, List<Capability> paramsCapabilities);');
    }
  }

  sb.writeln();
  sb.writeln('  @override');
  sb.writeln(
      '  Future<DispatchResult> dispatch(int interfaceId, int methodId, Uint8List params, {');
  sb.writeln('    List<Capability> paramsCapabilities = const [],');
  sb.writeln('  }) async {');

  if (allMethods.isNotEmpty) {
    // Group by defining interface ID.
    final byIface =
        <int, List<({SchemaNode ifaceNode, SchemaMethod method, String dartName})>>{};
    for (final m in allMethods) {
      (byIface[m.ifaceNode.id] ??= []).add(m);
    }

    sb.writeln('    switch (interfaceId) {');
    for (final entry in byIface.entries) {
      sb.writeln('      case ${_hexId(entry.key)}:');
      sb.writeln('        switch (methodId) {');
      for (final m in entry.value) {
        final paramsNode = nodeMap[m.method.paramStructTypeId];
        final resultsNode = nodeMap[m.method.resultStructTypeId];
        final methodName = m.dartName;
        final paramsName =
            _dartClassName(paramsNode?.displayName ?? 'Unknown');
        final isVoid = _isVoidResultStruct(resultsNode);

        sb.writeln('          case ${m.method.ordinal}:');
        sb.writeln('            final p = MessageReader.deserialize(params)');
        sb.writeln(
            '                .getRoot(${_lcfirst(paramsName)}Factory);');
        if (isVoid) {
          sb.writeln('            await $methodName(p, paramsCapabilities);');
          sb.writeln('            return DispatchResult.empty;');
        } else {
          sb.writeln(
              '            return await $methodName(p, paramsCapabilities);');
        }
      }
      sb.writeln('          default:');
      sb.writeln('            break;');
      sb.writeln('        }');
    }
    sb.writeln('      default:');
    sb.writeln('        break;');
    sb.writeln('    }');
  }
  sb.writeln(
      '    return super.dispatch(interfaceId, methodId, params, paramsCapabilities: paramsCapabilities);');
  sb.writeln('  }');
  sb.writeln();
  sb.writeln('  @override');
  sb.writeln('  Future<void> dispose() async {}');
  sb.writeln('}');
}

/// Returns all interface fields (sorted by codeOrder) in [resultsNode]
/// as a list of `(ptrOffset, fieldName, typeId)`.
List<(int, String, int)> _collectCapResults(SchemaNode? resultsNode) {
  if (resultsNode == null) return const [];
  final body = resultsNode.body;
  if (body is! StructBody) return const [];
  final fields = [...body.fields]
    ..sort((a, b) => a.codeOrder.compareTo(b.codeOrder));
  final result = <(int, String, int)>[];
  for (final field in fields) {
    if (field.body is! SlotField) continue;
    final sf = field.body as SlotField;
    if (sf.type is InterfaceRefType) {
      result.add((sf.offset, _camel(field.name), (sf.type as InterfaceRefType).typeId));
    }
  }
  return result;
}

/// Emits an `XxxPipeline` class for [method] if its result struct has any
/// interface fields.  Each interface field becomes a typed `XxxClient` getter
/// using the correct pointer slot index (fixing the hardcoded-0 bug).
void _writeResultsPipeline(
  StringBuffer sb,
  String ifaceName,
  SchemaMethod method,
  Map<int, SchemaNode> nodeMap,
  String dartName,
) {
  final resultsNode = nodeMap[method.resultStructTypeId];
  final capResults = _collectCapResults(resultsNode);
  if (capResults.isEmpty) return;

  final methodName = dartName;
  final resultsName = _dartClassName(resultsNode?.displayName ?? 'Unknown');
  final pipelineName = '${ifaceName}${_ucfirst(methodName)}Pipeline';

  sb.writeln();
  sb.writeln('final class $pipelineName {');
  sb.writeln('  $pipelineName._(CapCall call)');
  final fieldInits = capResults.map((r) {
    final capIfaceName =
        _dartClassName(nodeMap[r.$3]?.displayName ?? 'Unknown');
    return '    ${r.$2} = ${capIfaceName}Client(call.pipelineResult(${r.$1}))';
  }).join(',\n');
  final resultInit =
      '    result = call.result.then((r) => MessageReader.deserialize(r.bytes).getRoot(${_lcfirst(resultsName)}Factory))';
  sb.writeln('      : $fieldInits,\n$resultInit;');
  sb.writeln();
  sb.writeln('  final Future<${resultsName}Reader> result;');
  for (final (_, fname, typeId) in capResults) {
    final capIfaceName =
        _dartClassName(nodeMap[typeId]?.displayName ?? 'Unknown');
    sb.writeln('  final ${capIfaceName}Client $fname;');
  }
  sb.writeln('}');
}

// ---------------------------------------------------------------------------
// Enum generation
// ---------------------------------------------------------------------------

void _writeEnum(StringBuffer sb, SchemaNode node, EnumBody body) {
  final name = _dartClassName(node.displayName);
  final sorted = [...body.enumerants]
    ..sort((a, b) => a.codeOrder.compareTo(b.codeOrder));

  sb.writeln('enum $name {');
  for (final e in sorted) {
    sb.writeln('  ${_camel(e.name)},');
  }
  sb.writeln('}');
  sb.writeln();
  sb.writeln(
      '$name? ${_lcfirst(name)}FromUint16(int v) => '
      'v < $name.values.length ? $name.values[v] : null;');
  sb.writeln('int ${_lcfirst(name)}ToUint16($name v) => v.index;');
}

// ---------------------------------------------------------------------------
// Struct generation
// ---------------------------------------------------------------------------

void _writeStruct(
  StringBuffer sb,
  SchemaNode node,
  StructBody body,
  Map<int, SchemaNode> nodeMap,
) {
  final name = _dartClassName(node.displayName);
  final dataWords = body.dataWordCount;
  final ptrWords = body.pointerCount;

  final fields = [...body.fields]
    ..sort((a, b) => a.codeOrder.compareTo(b.codeOrder));

  // ---- Reader ----
  sb.writeln('final class ${name}Reader extends StructReader {');
  sb.writeln('  ${name}Reader(super.raw);');

  if (body.discriminantCount > 0) {
    final discByteOffset = body.discriminantOffset * 2;
    sb.writeln();
    sb.writeln('  int get which => getUint16Field($discByteOffset);');
  }

  for (final field in fields) {
    _writeReaderField(sb, field, nodeMap);
  }
  sb.writeln('}');
  sb.writeln();

  // ---- Builder ----
  sb.writeln('final class ${name}Builder extends StructBuilder {');
  sb.writeln('  ${name}Builder(super.raw);');
  sb.writeln();
  sb.writeln('  @override');
  sb.writeln('  ${name}Reader asReader() => ${name}Reader(rawToReader());');

  if (body.discriminantCount > 0) {
    final discByteOffset = body.discriminantOffset * 2;
    sb.writeln();
    sb.writeln('  void _setWhich(int v) => setUint16Field($discByteOffset, v);');
  }

  for (final field in fields) {
    _writeBuilderField(sb, field, nodeMap, body);
  }
  sb.writeln('}');
  sb.writeln();

  // ---- Factory ----
  sb.writeln('final class _${name}Factory');
  sb.writeln('    extends StructFactory<${name}Reader, ${name}Builder> {');
  sb.writeln('  @override int get dataWords => $dataWords;');
  sb.writeln('  @override int get ptrWords => $ptrWords;');
  sb.writeln('  @override');
  sb.writeln(
      '  ${name}Reader fromRawReader(RawStructReader r) => ${name}Reader(r);');
  sb.writeln('  @override');
  sb.writeln(
      '  ${name}Builder fromRawBuilder(RawStructBuilder r) => ${name}Builder(r);');
  sb.writeln('}');
  sb.writeln();
  sb.writeln('final ${_lcfirst(name)}Factory = _${name}Factory();');
}

void _writeReaderField(
  StringBuffer sb,
  SchemaField field,
  Map<int, SchemaNode> nodeMap,
) {
  final fname = _camel(field.name);
  sb.writeln();

  if (field.body is GroupField) {
    final gf = field.body as GroupField;
    final groupNode = nodeMap[gf.typeId];
    if (groupNode == null) return;
    final gname = _dartClassName(groupNode.displayName);
    sb.writeln('  ${gname}Reader get $fname => ${gname}Reader(raw);');
    return;
  }

  final sf = field.body as SlotField;
  final type = sf.type;
  final offset = sf.offset;

  // Void fields carry no data; reading them is meaningless, so skip.
  if (type is VoidType) return;

  // Capability pointer fields expose the cap-table index so callers can
  // look up the capability from DispatchResult.caps.
  if (type is InterfaceRefType) {
    sb.writeln(
        '  int get ${fname}CapIndex => getCapabilityField($offset);');
    return;
  }

  final (dartType, getter) =
      _readerGetter(type, offset, nodeMap, sf.defaultValue);
  sb.writeln('  $dartType get $fname => $getter;');
}

void _writeBuilderField(
  StringBuffer sb,
  SchemaField field,
  Map<int, SchemaNode> nodeMap,
  StructBody structBody,
) {
  final fname = _camel(field.name);
  final discVal = field.discriminantValue;
  final hasDisc = field.isUnionField;
  final discByteOffset = structBody.discriminantOffset * 2;

  if (field.body is GroupField) {
    final gf = field.body as GroupField;
    final groupNode = nodeMap[gf.typeId];
    if (groupNode == null) return;
    final gname = _dartClassName(groupNode.displayName);
    sb.writeln();
    if (hasDisc) {
      sb.writeln('  ${gname}Builder get $fname {');
      sb.writeln('    setUint16Field($discByteOffset, $discVal);');
      sb.writeln('    return ${gname}Builder(raw);');
      sb.writeln('  }');
    } else {
      sb.writeln('  ${gname}Builder get $fname => ${gname}Builder(raw);');
    }
    return;
  }

  final sf = field.body as SlotField;
  final type = sf.type;
  final offset = sf.offset;

  // Void field: no setter is meaningful.
  // For a union member emit a selection method so callers can set the
  // discriminant; for non-union Void fields emit nothing at all.
  if (type is VoidType) {
    if (hasDisc) {
      sb.writeln();
      sb.writeln('  void select${_ucfirst(fname)}() {');
      sb.writeln('    setUint16Field($discByteOffset, $discVal);');
      sb.writeln('  }');
    }
    return;
  }

  sb.writeln();

  if (_isPointerType(type)) {
    _writeBuilderPointerField(sb, fname, type, offset, nodeMap, hasDisc,
        discVal, discByteOffset);
  } else {
    _writeBuilderDataField(sb, fname, type, offset, nodeMap, hasDisc, discVal,
        discByteOffset, sf.defaultValue);
  }
}

void _writeBuilderDataField(
  StringBuffer sb,
  String fname,
  SchemaType type,
  int offset,
  Map<int, SchemaNode> nodeMap,
  bool hasDisc,
  int discVal,
  int discByteOffset, [
  Object? defaultValue,
]) {
  final (dartType, setter) = _builderDataSetter(type, offset, nodeMap, defaultValue);
  sb.writeln('  set $fname($dartType v) {');
  if (hasDisc) {
    sb.writeln('    setUint16Field($discByteOffset, $discVal);');
  }
  sb.writeln('    $setter;');
  sb.writeln('  }');
}

void _writeBuilderPointerField(
  StringBuffer sb,
  String fname,
  SchemaType type,
  int offset,
  Map<int, SchemaNode> nodeMap,
  bool hasDisc,
  int discVal,
  int discByteOffset,
) {
  final setDisc =
      hasDisc ? '    setUint16Field($discByteOffset, $discVal);\n' : '';

  if (type is TextType) {
    sb.writeln('  set $fname(String? v) {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    setTextField($offset, v);');
    sb.writeln('  }');
  } else if (type is DataType) {
    sb.writeln('  set $fname(Uint8List? v) {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    setDataField($offset, v);');
    sb.writeln('  }');
  } else if (type is StructRefType) {
    final refNode = nodeMap[type.typeId];
    final refName = _dartClassName(refNode?.displayName ?? 'Unknown');
    final refBody = refNode?.body;
    final dw = refBody is StructBody ? refBody.dataWordCount : 0;
    final pw = refBody is StructBody ? refBody.pointerCount : 0;
    final ucfname = _ucfirst(fname);
    sb.writeln('  ${refName}Builder init$ucfname() {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    return initStructFieldWith($offset,');
    sb.writeln('        (r) => ${refName}Builder(r), $dw, $pw);');
    sb.writeln('  }');
    sb.writeln();
    sb.writeln('  bool has$ucfname() => hasPointerField($offset);');
  } else if (type is ListType) {
    _writeListBuilderField(
        sb, fname, type, offset, nodeMap, setDisc, hasDisc);
  } else if (type is AnyPointerType || type is TypeParameterRefType) {
    sb.writeln('  set $fname(Uint8List? v) {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    if (v != null) setAnyPointerFromMessage($offset, v);');
    sb.writeln('  }');
  } else if (type is InterfaceRefType) {
    final ucfname = _ucfirst(fname);
    sb.writeln('  void set$ucfname(int capTableIndex) {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    setCapabilityField($offset, capTableIndex);');
    sb.writeln('  }');
  }
}

void _writeListBuilderField(
  StringBuffer sb,
  String fname,
  ListType type,
  int offset,
  Map<int, SchemaNode> nodeMap,
  String setDisc,
  bool hasDisc,
) {
  final ucfname = _ucfirst(fname);
  final elem = type.elementType;

  final (initCall, retType) = _listInitCall(elem, offset, nodeMap);
  sb.writeln('  $retType init$ucfname(int length) {');
  if (hasDisc) sb.write(setDisc);
  sb.writeln('    return $initCall;');
  sb.writeln('  }');
}

// ---------------------------------------------------------------------------
// Helpers: type mapping
// ---------------------------------------------------------------------------

/// Returns a named-parameter suffix for a non-trivial explicit default value.
String _defaultSuffix(Object? v) {
  if (v == null) return '';
  if (v is int && v == 0) return '';
  if (v is bool && !v) return '';
  if (v is double && v == 0.0) return '';
  return ', defaultValue: $v';
}

(String, String) _readerGetter(
  SchemaType type,
  int offset,
  Map<int, SchemaNode> nodeMap, [
  Object? fieldDefault,
]) {
  final ds = _defaultSuffix(fieldDefault);
  // TypeParameterRef is treated as opaque AnyPointer in the template class.
  if (type is TypeParameterRefType) {
    return ('Uint8List?', 'getAnyPointerAsMessageBytes($offset)');
  }
  // Concrete generic instantiation: use the specialized reader name.
  if (type is StructRefType && _allConcrete(type.typeArgs)) {
    final specName = _specializedName(type.typeId, type.typeArgs, nodeMap);
    return ('${specName}Reader?',
        'getStructFieldWith($offset, (r) => ${specName}Reader(r))');
  }
  return switch (type) {
    VoidType() => ('void', '{}'),
    BoolType() => ('bool', 'getBoolField($offset$ds)'),
    Int8Type() => ('int', 'getInt8Field($offset$ds)'),
    Int16Type() => ('int', 'getInt16Field(${offset * 2}$ds)'),
    Int32Type() => ('int', 'getInt32Field(${offset * 4}$ds)'),
    Int64Type() => ('int', 'getInt64Field(${offset * 8}$ds)'),
    UInt8Type() => ('int', 'getUint8Field($offset$ds)'),
    UInt16Type() => ('int', 'getUint16Field(${offset * 2}$ds)'),
    UInt32Type() => ('int', 'getUint32Field(${offset * 4}$ds)'),
    UInt64Type() => ('int', 'getUint64Field(${offset * 8}$ds)'),
    Float32Type() => ('double', 'getFloat32Field(${offset * 4}$ds)'),
    Float64Type() => ('double', 'getFloat64Field(${offset * 8}$ds)'),
    TextType() => ('String?', 'getTextField($offset)'),
    DataType() => ('Uint8List?', 'getDataField($offset)'),
    AnyPointerType() => ('Uint8List?', 'getAnyPointerAsMessageBytes($offset)'),
    EnumRefType(:final typeId) =>
      _enumReaderGetter(typeId, offset * 2, nodeMap,
          fieldDefault is int ? fieldDefault : null),
    StructRefType(:final typeId) =>
      _structReaderGetter(typeId, offset, nodeMap),
    ListType(:final elementType) =>
      _listReaderGetter(elementType, offset, nodeMap),
    InterfaceRefType() =>
      ('int', 'getCapabilityField($offset)'),
    _ => ('dynamic', 'null /* unsupported type */'),
  };
}

(String, String) _enumReaderGetter(
    int typeId, int byteOffset, Map<int, SchemaNode> nodeMap,
    [int? defaultVal]) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownEnum');
  final ds = _defaultSuffix(defaultVal);
  // fromUint16 returns $name? to handle unknown values from newer schemas.
  return ('$name?',
      '${_lcfirst(name)}FromUint16(getUint16Field($byteOffset$ds))');
}

(String, String) _structReaderGetter(
    int typeId, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownStruct');
  return ('${name}Reader?',
      'getStructFieldWith($ptrIndex, (r) => ${name}Reader(r))');
}

(String, String) _listReaderGetter(
    SchemaType elem, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  // Concrete generic instantiation: use the specialized reader name.
  if (elem is StructRefType && _allConcrete(elem.typeArgs)) {
    final specName = _specializedName(elem.typeId, elem.typeArgs, nodeMap);
    return ('ListReader<${specName}Reader>?',
        'getStructListFieldWith($ptrIndex, (r) => ${specName}Reader(r))');
  }
  return switch (elem) {
    BoolType() => ('ListReader<bool>?', 'getBoolListField($ptrIndex)'),
    Int8Type() => ('ListReader<int>?', 'getInt8ListField($ptrIndex)'),
    Int16Type() => ('ListReader<int>?', 'getInt16ListField($ptrIndex)'),
    Int32Type() => ('ListReader<int>?', 'getInt32ListField($ptrIndex)'),
    Int64Type() => ('ListReader<int>?', 'getInt64ListField($ptrIndex)'),
    UInt8Type() => ('ListReader<int>?', 'getUint8ListField($ptrIndex)'),
    UInt16Type() => ('ListReader<int>?', 'getUint16ListField($ptrIndex)'),
    UInt32Type() => ('ListReader<int>?', 'getUint32ListField($ptrIndex)'),
    UInt64Type() => ('ListReader<int>?', 'getUint64ListField($ptrIndex)'),
    Float32Type() =>
      ('ListReader<double>?', 'getFloat32ListField($ptrIndex)'),
    Float64Type() =>
      ('ListReader<double>?', 'getFloat64ListField($ptrIndex)'),
    TextType() => ('ListReader<String?>?', 'getTextListField($ptrIndex)'),
    DataType() =>
      ('ListReader<Uint8List?>?', 'getDataListField($ptrIndex)'),
    StructRefType(:final typeId) =>
      _structListReaderGetter(typeId, ptrIndex, nodeMap),
    VoidType() => ('ListReader<Null>?', 'getVoidListField($ptrIndex)'),
    EnumRefType(:final typeId) =>
      _enumListReaderGetter(typeId, ptrIndex, nodeMap),
    ListType(:final elementType) =>
      _nestedListReaderGetter(elementType, ptrIndex, nodeMap),
    _ => ('ListReader<dynamic>?', 'null /* unsupported list element */'),
  };
}

(String, String) _enumListReaderGetter(
    int typeId, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownEnum');
  return ('ListReader<$name?>?',
      'getEnumListField($ptrIndex, ${_lcfirst(name)}FromUint16)');
}

(String, String) _nestedListReaderGetter(
    SchemaType elem, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  final (innerType, lambdaExpr) = _listFromRawExpr(elem, nodeMap);
  // innerType is the Dart element type that the lambda produces (e.g. 'double').
  // getNestedListField returns ListReader<ListReader<T>?>?, so wrap accordingly.
  return ('ListReader<ListReader<$innerType>?>?',
      'getNestedListField($ptrIndex, $lambdaExpr)');
}

/// Returns (Dart element type, lambda expression `(raw) => <ListReader>`).
(String, String) _listFromRawExpr(
    SchemaType elem, Map<int, SchemaNode> nodeMap) {
  return switch (elem) {
    VoidType() => ('Null?', 'voidListFromRaw'),
    BoolType() => ('bool', 'boolListFromRaw'),
    Int8Type() => ('int', 'int8ListFromRaw'),
    Int16Type() => ('int', 'int16ListFromRaw'),
    Int32Type() => ('int', 'int32ListFromRaw'),
    Int64Type() => ('int', 'int64ListFromRaw'),
    UInt8Type() => ('int', 'uint8ListFromRaw'),
    UInt16Type() => ('int', 'uint16ListFromRaw'),
    UInt32Type() => ('int', 'uint32ListFromRaw'),
    UInt64Type() => ('int', 'uint64ListFromRaw'),
    Float32Type() => ('double', 'float32ListFromRaw'),
    Float64Type() => ('double', 'float64ListFromRaw'),
    TextType() => ('String?', 'textListFromRaw'),
    DataType() => ('Uint8List?', 'dataListFromRaw'),
    StructRefType(:final typeId) => _structListFromRawExpr(typeId, nodeMap),
    EnumRefType(:final typeId) => _enumListFromRawExpr(typeId, nodeMap),
    ListType(:final elementType) => _nestedNestedListFromRawExpr(elementType, nodeMap),
    _ => ('dynamic', '(raw) => null /* unsupported nested list element */'),
  };
}

(String, String) _structListFromRawExpr(
    int typeId, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownStruct');
  return ('${name}Reader',
      '(raw) => structListFromRaw(raw, (r) => ${name}Reader(r))');
}

(String, String) _enumListFromRawExpr(
    int typeId, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownEnum');
  return ('$name?',
      '(raw) => enumListFromRaw(raw, ${_lcfirst(name)}FromUint16)');
}

(String, String) _nestedNestedListFromRawExpr(
    SchemaType elem, Map<int, SchemaNode> nodeMap) {
  final (innerType, innerLambda) = _listFromRawExpr(elem, nodeMap);
  return ('ListReader<$innerType>?',
      '(raw) => NestedListReader<$innerType>(raw, $innerLambda)');
}

(String, String) _structListReaderGetter(
    int typeId, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownStruct');
  return ('ListReader<${name}Reader>?',
      'getStructListFieldWith($ptrIndex, (r) => ${name}Reader(r))');
}

(String, String) _builderDataSetter(
    SchemaType type, int offset, Map<int, SchemaNode> nodeMap,
    [Object? fieldDefault]) {
  final ds = _defaultSuffix(fieldDefault);
  return switch (type) {
    BoolType() => ('bool', 'setBoolField($offset, v$ds)'),
    Int8Type() => ('int', 'setInt8Field($offset, v$ds)'),
    Int16Type() => ('int', 'setInt16Field(${offset * 2}, v$ds)'),
    Int32Type() => ('int', 'setInt32Field(${offset * 4}, v$ds)'),
    Int64Type() => ('int', 'setInt64Field(${offset * 8}, v$ds)'),
    UInt8Type() => ('int', 'setUint8Field($offset, v$ds)'),
    UInt16Type() => ('int', 'setUint16Field(${offset * 2}, v$ds)'),
    UInt32Type() => ('int', 'setUint32Field(${offset * 4}, v$ds)'),
    UInt64Type() => ('int', 'setUint64Field(${offset * 8}, v$ds)'),
    Float32Type() => ('double', 'setFloat32Field(${offset * 4}, v$ds)'),
    Float64Type() => ('double', 'setFloat64Field(${offset * 8}, v$ds)'),
    EnumRefType(:final typeId) =>
      _enumBuilderSetter(typeId, offset * 2, nodeMap,
          fieldDefault is int ? fieldDefault : null),
    _ => ('dynamic', '/* unsupported data type */'),
  };
}

(String, String) _enumBuilderSetter(
    int typeId, int byteOffset, Map<int, SchemaNode> nodeMap,
    [int? defaultVal]) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownEnum');
  final ds = _defaultSuffix(defaultVal);
  return (name, 'setUint16Field($byteOffset, ${_lcfirst(name)}ToUint16(v)$ds)');
}

(String, String) _listInitCall(
    SchemaType elem, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  return switch (elem) {
    BoolType() => ('initBoolListField($ptrIndex, length)', 'ListBuilder<bool>'),
    Int8Type() =>
      ('initInt8ListField($ptrIndex, length)', 'ListBuilder<int>'),
    Int16Type() =>
      ('initInt16ListField($ptrIndex, length)', 'ListBuilder<int>'),
    Int32Type() =>
      ('initInt32ListField($ptrIndex, length)', 'ListBuilder<int>'),
    Int64Type() =>
      ('initInt64ListField($ptrIndex, length)', 'ListBuilder<int>'),
    UInt8Type() =>
      ('initUint8ListField($ptrIndex, length)', 'ListBuilder<int>'),
    UInt16Type() =>
      ('initUint16ListField($ptrIndex, length)', 'ListBuilder<int>'),
    UInt32Type() =>
      ('initUint32ListField($ptrIndex, length)', 'ListBuilder<int>'),
    UInt64Type() =>
      ('initUint64ListField($ptrIndex, length)', 'ListBuilder<int>'),
    Float32Type() =>
      ('initFloat32ListField($ptrIndex, length)', 'ListBuilder<double>'),
    Float64Type() =>
      ('initFloat64ListField($ptrIndex, length)', 'ListBuilder<double>'),
    TextType() =>
      ('initTextListField($ptrIndex, length)', 'ListBuilder<String?>'),
    DataType() =>
      ('initDataListField($ptrIndex, length)', 'ListBuilder<Uint8List?>'),
    StructRefType(:final typeId) =>
      _structListInitCall(typeId, ptrIndex, nodeMap),
    VoidType() =>
      ('initVoidListField($ptrIndex, length)', 'ListBuilder<Null>'),
    EnumRefType(:final typeId) =>
      _enumListInitCall(typeId, ptrIndex, nodeMap),
    _ => ('/* unsupported */', 'dynamic'),
  };
}

(String, String) _enumListInitCall(
    int typeId, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownEnum');
  return ('initEnumListField($ptrIndex, length, ${_lcfirst(name)}ToUint16)',
      'ListBuilder<$name>');
}

(String, String) _structListInitCall(
    int typeId, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownStruct');
  final body = node?.body;
  final dw = body is StructBody ? body.dataWordCount : 0;
  final pw = body is StructBody ? body.pointerCount : 0;
  final initCall = 'initStructListFieldWith($ptrIndex, length, '
      '(r) => ${name}Builder(r), $dw, $pw)';
  return (initCall, 'ListBuilder<${name}Builder>');
}

bool _isPointerType(SchemaType t) => switch (t) {
      TextType() ||
      DataType() ||
      StructRefType() ||
      ListType() ||
      InterfaceRefType() ||
      AnyPointerType() ||
      TypeParameterRefType() =>
        true,
      _ => false,
    };

// ---------------------------------------------------------------------------
// Identifier helpers
// ---------------------------------------------------------------------------

String _dartClassName(String rawName) {
  var name = rawName;
  final colonIdx = name.lastIndexOf(':');
  if (colonIdx >= 0) name = name.substring(colonIdx + 1);
  if (name.contains(r'$') && name.contains('.')) {
    name = name.split('.').map(_ucfirst).join();
  } else {
    final dotIdx = name.lastIndexOf('.');
    if (dotIdx >= 0) name = name.substring(dotIdx + 1);
  }
  if (name.contains(r'$')) {
    name = name.split(r'$').map(_ucfirst).join();
  }
  return name;
}

String _camel(String s) {
  if (s.isEmpty) return s;
  if (s[0] == s[0].toLowerCase()) return s;
  return s[0].toLowerCase() + s.substring(1);
}

String _lcfirst(String s) =>
    s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);
String _ucfirst(String s) =>
    s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

String _hexId(int id) {
  final hi = id >>> 32;
  final lo = id & 0xFFFFFFFF;
  return '0x${hi.toRadixString(16).padLeft(8, '0')}${lo.toRadixString(16).padLeft(8, '0')}';
}

// ---------------------------------------------------------------------------
// Generic specialization helpers
// ---------------------------------------------------------------------------

bool _hasTypeParam(SchemaType t) => switch (t) {
      TypeParameterRefType() => true,
      ListType(:final elementType) => _hasTypeParam(elementType),
      StructRefType(:final typeArgs) => typeArgs.any(_hasTypeParam),
      InterfaceRefType(:final typeArgs) => typeArgs.any(_hasTypeParam),
      _ => false,
    };

bool _allConcrete(List<SchemaType> args) =>
    args.isNotEmpty && args.every((t) => !_hasTypeParam(t));

String _typeArgName(SchemaType t, Map<int, SchemaNode> nodeMap) => switch (t) {
      VoidType() => 'Void',
      BoolType() => 'Bool',
      Int8Type() => 'Int8',
      Int16Type() => 'Int16',
      Int32Type() => 'Int32',
      Int64Type() => 'Int64',
      UInt8Type() => 'UInt8',
      UInt16Type() => 'UInt16',
      UInt32Type() => 'UInt32',
      UInt64Type() => 'UInt64',
      Float32Type() => 'Float32',
      Float64Type() => 'Float64',
      TextType() => 'Text',
      DataType() => 'Data',
      AnyPointerType() => 'AnyPointer',
      EnumRefType(:final typeId) => nodeMap[typeId]?.shortName ?? 'Unknown',
      StructRefType(:final typeId, :final typeArgs) => typeArgs.isEmpty
          ? (nodeMap[typeId]?.shortName ?? 'Unknown')
          : (nodeMap[typeId]?.shortName ?? 'Unknown') +
              typeArgs.map((a) => _typeArgName(a, nodeMap)).join(),
      InterfaceRefType(:final typeId, :final typeArgs) => typeArgs.isEmpty
          ? (nodeMap[typeId]?.shortName ?? 'Unknown')
          : (nodeMap[typeId]?.shortName ?? 'Unknown') +
              typeArgs.map((a) => _typeArgName(a, nodeMap)).join(),
      ListType(:final elementType) =>
        'List${_typeArgName(elementType, nodeMap)}',
      _ => 'Unknown',
    };

String _specializedName(
    int nodeId, List<SchemaType> typeArgs, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[nodeId];
  final baseName = _dartClassName(node?.displayName ?? 'Unknown');
  final suffix = typeArgs.map((t) => _typeArgName(t, nodeMap)).join();
  return '$baseName$suffix';
}

SchemaType _substituteType(SchemaType t, List<SchemaType> typeArgs) {
  return switch (t) {
    TypeParameterRefType(:final parameterIndex) =>
      parameterIndex < typeArgs.length ? typeArgs[parameterIndex] : t,
    ListType(:final elementType) =>
      ListType(_substituteType(elementType, typeArgs)),
    StructRefType(:final typeId, typeArgs: final ta) when ta.isNotEmpty =>
      StructRefType(typeId,
          typeArgs: ta.map((a) => _substituteType(a, typeArgs)).toList()),
    InterfaceRefType(:final typeId, typeArgs: final ta) when ta.isNotEmpty =>
      InterfaceRefType(typeId,
          typeArgs: ta.map((a) => _substituteType(a, typeArgs)).toList()),
    _ => t,
  };
}

SchemaField _substituteFieldType(SchemaField field, List<SchemaType> typeArgs) {
  if (field.body is! SlotField) return field;
  final sf = field.body as SlotField;
  final newType = _substituteType(sf.type, typeArgs);
  if (identical(newType, sf.type)) return field;
  return SchemaField(
    name: field.name,
    codeOrder: field.codeOrder,
    discriminantValue: field.discriminantValue,
    body: SlotField(
      offset: sf.offset,
      type: newType,
      hadExplicitDefault: sf.hadExplicitDefault,
      defaultValue: sf.defaultValue,
    ),
  );
}

void _collectTypeSpecializations(
  SchemaType type,
  Map<int, SchemaNode> nodeMap,
  Map<String, ({int nodeId, List<SchemaType> typeArgs})> result,
) {
  if (type is ListType) {
    _collectTypeSpecializations(type.elementType, nodeMap, result);
    return;
  }
  if (type is StructRefType && _allConcrete(type.typeArgs)) {
    final specName = _specializedName(type.typeId, type.typeArgs, nodeMap);
    if (!result.containsKey(specName)) {
      result[specName] = (nodeId: type.typeId, typeArgs: type.typeArgs);
      // Recurse into the specialized fields to find further nested specializations.
      _collectNodeFieldSpecializationsWithArgs(
          type.typeId, type.typeArgs, nodeMap, result);
    }
  }
}

void _collectNodeFieldSpecializations(
  SchemaNode node,
  Map<int, SchemaNode> nodeMap,
  Map<String, ({int nodeId, List<SchemaType> typeArgs})> result,
) {
  final body = node.body;
  if (body is! StructBody) return;
  for (final field in body.fields) {
    if (field.body is! SlotField) continue;
    _collectTypeSpecializations((field.body as SlotField).type, nodeMap, result);
  }
}

void _collectNodeFieldSpecializationsWithArgs(
  int nodeId,
  List<SchemaType> typeArgs,
  Map<int, SchemaNode> nodeMap,
  Map<String, ({int nodeId, List<SchemaType> typeArgs})> result,
) {
  final node = nodeMap[nodeId];
  if (node == null) return;
  final body = node.body;
  if (body is! StructBody) return;
  for (final field in body.fields) {
    if (field.body is! SlotField) continue;
    final sf = field.body as SlotField;
    _collectTypeSpecializations(
        _substituteType(sf.type, typeArgs), nodeMap, result);
  }
}

/// Generates a read-only specialized reader for a concrete generic instantiation.
void _writeSpecializedStruct(
  StringBuffer sb,
  String specName,
  int nodeId,
  List<SchemaType> typeArgs,
  Map<int, SchemaNode> nodeMap,
) {
  final node = nodeMap[nodeId];
  if (node == null || node.body is! StructBody) return;
  final body = node.body as StructBody;
  final fields = [...body.fields]
    ..sort((a, b) => a.codeOrder.compareTo(b.codeOrder));

  sb.writeln('final class ${specName}Reader extends StructReader {');
  sb.writeln('  ${specName}Reader(super.raw);');

  if (body.discriminantCount > 0) {
    final discByteOffset = body.discriminantOffset * 2;
    sb.writeln();
    sb.writeln('  int get which => getUint16Field($discByteOffset);');
  }

  for (final field in fields) {
    _writeReaderField(sb, _substituteFieldType(field, typeArgs), nodeMap);
  }
  sb.writeln('}');
}
