import '../schema/schema_model.dart';

/// Generates a single Dart source file from a set of [SchemaNode]s that
/// belong to a given file node.
String generateDartFile(
  SchemaNode fileNode,
  List<SchemaNode> allNodes, {
  String packageName = 'capnproto_dart',
}) {
  final nodeMap = {for (final n in allNodes) n.id: n};
  final sb = StringBuffer();

  final structs = <SchemaNode>[];
  final enums = <SchemaNode>[];
  final interfaces = <SchemaNode>[];
  _collectNodes(fileNode, nodeMap, structs, enums, interfaces);

  sb.writeln('// Generated by capnpc-dart — do not edit by hand.');
  sb.writeln('// ignore_for_file: annotate_overrides, unnecessary_this');
  sb.writeln();
  sb.writeln("import 'dart:typed_data';");
  sb.writeln("import 'package:$packageName/$packageName.dart';");
  if (interfaces.isNotEmpty) {
    sb.writeln("import 'package:capnproto_dart_rpc/capnproto_dart_rpc.dart';");
  }
  sb.writeln();

  for (final node in enums) {
    _writeEnum(sb, node, node.body as EnumBody);
    sb.writeln();
  }

  for (final node in structs) {
    _writeStruct(sb, node, node.body as StructBody, nodeMap);
    sb.writeln();
  }

  final groups = <SchemaNode>[];
  final groupSeen = <int>{};
  for (final node in structs) {
    _collectGroups(node, nodeMap, groups, groupSeen);
  }
  for (final node in groups) {
    _writeStruct(sb, node, node.body as StructBody, nodeMap);
    sb.writeln();
  }

  for (final node in interfaces) {
    _writeInterface(sb, node, node.body as InterfaceBody, nodeMap);
    sb.writeln();
  }

  return sb.toString();
}

void _collectNodes(
  SchemaNode root,
  Map<int, SchemaNode> nodeMap,
  List<SchemaNode> structs,
  List<SchemaNode> enums,
  List<SchemaNode> interfaces,
) {
  for (final nested in root.nestedNodes) {
    final node = nodeMap[nested.id];
    if (node == null) continue;
    if (node.body is StructBody) {
      final body = node.body as StructBody;
      if (!body.isGroup) structs.add(node);
      _collectNodes(node, nodeMap, structs, enums, interfaces);
    } else if (node.body is EnumBody) {
      enums.add(node);
    } else if (node.body is InterfaceBody) {
      interfaces.add(node);
      final iface = node.body as InterfaceBody;
      for (final method in iface.methods) {
        for (final id in [method.paramStructTypeId, method.resultStructTypeId]) {
          final ms = nodeMap[id];
          if (ms != null && ms.body is StructBody) {
            final sb = ms.body as StructBody;
            if (!sb.isGroup) structs.add(ms);
          }
        }
      }
    }
  }
}

void _collectGroups(
  SchemaNode node,
  Map<int, SchemaNode> nodeMap,
  List<SchemaNode> groups,
  Set<int> seen,
) {
  final body = node.body;
  if (body is! StructBody) return;
  for (final field in body.fields) {
    if (field.body is! GroupField) continue;
    final gf = field.body as GroupField;
    if (seen.contains(gf.typeId)) continue;
    final groupNode = nodeMap[gf.typeId];
    if (groupNode == null) continue;
    seen.add(gf.typeId);
    groups.add(groupNode);
    _collectGroups(groupNode, nodeMap, groups, seen);
  }
}

// ---------------------------------------------------------------------------
// Interface generation
// ---------------------------------------------------------------------------

void _writeInterface(
  StringBuffer sb,
  SchemaNode node,
  InterfaceBody body,
  Map<int, SchemaNode> nodeMap,
) {
  final name = _dartClassName(node.displayName);

  // Collect all methods including inherited ones (depth-first from ancestors).
  final allMethods =
      <({SchemaNode ifaceNode, SchemaMethod method})>[];
  _collectAllMethods(node, body, nodeMap, allMethods, {});

  // ---- Client stub ----
  sb.writeln('class ${name}Client extends Capability {');
  sb.writeln('  static const int _interfaceId = ${_hexId(node.id)};');
  sb.writeln();
  sb.writeln('  final Capability _cap;');
  sb.writeln('  ${name}Client(this._cap);');

  for (final m in allMethods) {
    _writeClientMethod(sb, m.ifaceNode, m.method, nodeMap);
  }

  sb.writeln();
  sb.writeln('  @override');
  sb.writeln('  Future<void> dispose() => _cap.dispose();');
  sb.writeln('}');
  sb.writeln();

  // ---- Factory ----
  sb.writeln(
      'class ${name}ClientFactory extends CapabilityFactory<${name}Client> {');
  sb.writeln('  @override');
  sb.writeln(
      '  ${name}Client fromCapability(Capability cap) => ${name}Client(cap);');
  sb.writeln('}');
  sb.writeln();

  // ---- Server stub ----
  _writeServerStub(sb, node, allMethods, nodeMap);
}

/// Depth-first collection of all methods reachable via inheritance.
/// Each method retains its defining interface node; the wire-level method ID
/// is carried in `method.ordinal`.
void _collectAllMethods(
  SchemaNode ifaceNode,
  InterfaceBody body,
  Map<int, SchemaNode> nodeMap,
  List<({SchemaNode ifaceNode, SchemaMethod method})> result,
  Set<int> seen,
) {
  if (seen.contains(ifaceNode.id)) return;
  seen.add(ifaceNode.id);

  for (final scId in body.superclassIds) {
    final scNode = nodeMap[scId];
    if (scNode == null || scNode.body is! InterfaceBody) continue;
    _collectAllMethods(
        scNode, scNode.body as InterfaceBody, nodeMap, result, seen);
  }

  for (final method in body.methods) {
    result.add((ifaceNode: ifaceNode, method: method));
  }
}

void _writeClientMethod(
  StringBuffer sb,
  SchemaNode ifaceNode,
  SchemaMethod method,
  Map<int, SchemaNode> nodeMap,
) {
  final methodName = _camel(method.name);
  final paramsNode = nodeMap[method.paramStructTypeId];
  final resultsNode = nodeMap[method.resultStructTypeId];
  final paramsName = _dartClassName(paramsNode?.displayName ?? 'Unknown');
  final ifaceId = _hexId(ifaceNode.id);
  final ordinal = method.ordinal;

  final capParams = _collectCapParams(paramsNode);
  final capField = _singleCapabilityField(resultsNode, nodeMap);

  sb.writeln();

  if (capParams.isEmpty) {
    if (capField != null) {
      final capIfaceNode = nodeMap[capField.typeId];
      final capIfaceName =
          _dartClassName(capIfaceNode?.displayName ?? 'Unknown');
      sb.writeln(
          '  ${capIfaceName}Client $methodName(void Function(${paramsName}Builder) build) {');
      sb.writeln('    final mb = MessageBuilder();');
      sb.writeln('    build(mb.initRoot(${_lcfirst(paramsName)}Factory));');
      sb.writeln(
          '    final f = _cap.dispatch($ifaceId, $ordinal, mb.serialize());');
      sb.writeln(
          '    return ${capIfaceName}Client(PipelinedCapability(f.then((r) => r.caps[0])));');
      sb.writeln('  }');
    } else {
      final resultsName =
          _dartClassName(resultsNode?.displayName ?? 'Unknown');
      sb.writeln(
          '  Future<${resultsName}Reader> $methodName(void Function(${paramsName}Builder) build) async {');
      sb.writeln('    final mb = MessageBuilder();');
      sb.writeln('    build(mb.initRoot(${_lcfirst(paramsName)}Factory));');
      sb.writeln(
          '    final result = await _cap.dispatch($ifaceId, $ordinal, mb.serialize());');
      sb.writeln(
          '    return MessageReader.deserialize(result.bytes).getRoot(${_lcfirst(resultsName)}Factory);');
      sb.writeln('  }');
    }
  } else {
    final namedParams =
        capParams.map((p) => 'required Capability ${p.$2}').join(', ');
    final capsList = capParams.map((p) => p.$2).join(', ');

    if (capField != null) {
      final capIfaceNode = nodeMap[capField.typeId];
      final capIfaceName =
          _dartClassName(capIfaceNode?.displayName ?? 'Unknown');
      sb.writeln(
          '  ${capIfaceName}Client $methodName(void Function(${paramsName}Builder) build, {$namedParams}) {');
      sb.writeln('    final mb = MessageBuilder();');
      sb.writeln('    final b = mb.initRoot(${_lcfirst(paramsName)}Factory);');
      for (final (_, fname, capIdx) in capParams) {
        sb.writeln('    b.set${_ucfirst(fname)}($capIdx);');
      }
      sb.writeln('    build(b);');
      sb.writeln(
          '    final f = _cap.dispatch($ifaceId, $ordinal, mb.serialize(), paramsCapabilities: [$capsList]);');
      sb.writeln(
          '    return ${capIfaceName}Client(PipelinedCapability(f.then((r) => r.caps[0])));');
      sb.writeln('  }');
    } else {
      final resultsName =
          _dartClassName(resultsNode?.displayName ?? 'Unknown');
      sb.writeln(
          '  Future<${resultsName}Reader> $methodName(void Function(${paramsName}Builder) build, {$namedParams}) async {');
      sb.writeln('    final mb = MessageBuilder();');
      sb.writeln('    final b = mb.initRoot(${_lcfirst(paramsName)}Factory);');
      for (final (_, fname, capIdx) in capParams) {
        sb.writeln('    b.set${_ucfirst(fname)}($capIdx);');
      }
      sb.writeln('    build(b);');
      sb.writeln(
          '    final result = await _cap.dispatch($ifaceId, $ordinal, mb.serialize(), paramsCapabilities: [$capsList]);');
      sb.writeln(
          '    return MessageReader.deserialize(result.bytes).getRoot(${_lcfirst(resultsName)}Factory);');
      sb.writeln('  }');
    }
  }
}

/// Returns the [InterfaceRefType] fields (sorted by codeOrder) in [paramsNode]
/// as a list of `(ptrOffset, fieldName, capTableIndex)`.
List<(int, String, int)> _collectCapParams(SchemaNode? paramsNode) {
  if (paramsNode == null) return const [];
  final body = paramsNode.body;
  if (body is! StructBody) return const [];

  final fields = [...body.fields]
    ..sort((a, b) => a.codeOrder.compareTo(b.codeOrder));
  final result = <(int, String, int)>[];
  int capIdx = 0;
  for (final field in fields) {
    if (field.body is! SlotField) continue;
    final sf = field.body as SlotField;
    if (sf.type is InterfaceRefType) {
      result.add((sf.offset, _camel(field.name), capIdx++));
    }
  }
  return result;
}

/// Returns true if [resultsNode] represents an effectively-void result struct.
bool _isVoidResultStruct(SchemaNode? resultsNode) {
  if (resultsNode == null) return true;
  final body = resultsNode.body;
  if (body is! StructBody) return true;
  if (body.dataWordCount == 0 && body.pointerCount == 0) return true;
  return body.fields.every((f) {
    if (f.body is! SlotField) return false;
    return (f.body as SlotField).type is VoidType;
  });
}

void _writeServerStub(
  StringBuffer sb,
  SchemaNode node,
  List<({SchemaNode ifaceNode, SchemaMethod method})> allMethods,
  Map<int, SchemaNode> nodeMap,
) {
  final name = _dartClassName(node.displayName);

  sb.writeln('abstract class ${name}Server extends Capability {');

  for (final m in allMethods) {
    final method = m.method;
    final paramsNode = nodeMap[method.paramStructTypeId];
    final resultsNode = nodeMap[method.resultStructTypeId];
    final methodName = _camel(method.name);
    final paramsName = _dartClassName(paramsNode?.displayName ?? 'Unknown');
    final isVoid = _isVoidResultStruct(resultsNode);

    sb.writeln();
    if (isVoid) {
      sb.writeln(
          '  Future<void> $methodName(${paramsName}Reader params, List<Capability> paramsCapabilities);');
    } else {
      sb.writeln(
          '  Future<DispatchResult> $methodName(${paramsName}Reader params, List<Capability> paramsCapabilities);');
    }
  }

  sb.writeln();
  sb.writeln('  @override');
  sb.writeln(
      '  Future<DispatchResult> dispatch(int interfaceId, int methodId, Uint8List params, {');
  sb.writeln('    List<Capability> paramsCapabilities = const [],');
  sb.writeln('  }) async {');

  if (allMethods.isNotEmpty) {
    // Group by defining interface ID.
    final byIface =
        <int, List<({SchemaNode ifaceNode, SchemaMethod method})>>{};
    for (final m in allMethods) {
      (byIface[m.ifaceNode.id] ??= []).add(m);
    }

    sb.writeln('    switch (interfaceId) {');
    for (final entry in byIface.entries) {
      sb.writeln('      case ${_hexId(entry.key)}:');
      sb.writeln('        switch (methodId) {');
      for (final m in entry.value) {
        final paramsNode = nodeMap[m.method.paramStructTypeId];
        final resultsNode = nodeMap[m.method.resultStructTypeId];
        final methodName = _camel(m.method.name);
        final paramsName =
            _dartClassName(paramsNode?.displayName ?? 'Unknown');
        final isVoid = _isVoidResultStruct(resultsNode);

        sb.writeln('          case ${m.method.ordinal}:');
        sb.writeln('            final p = MessageReader.deserialize(params)');
        sb.writeln(
            '                .getRoot(${_lcfirst(paramsName)}Factory);');
        if (isVoid) {
          sb.writeln('            await $methodName(p, paramsCapabilities);');
          sb.writeln('            return DispatchResult.empty;');
        } else {
          sb.writeln(
              '            return await $methodName(p, paramsCapabilities);');
        }
      }
      sb.writeln('          default:');
      sb.writeln('            break;');
      sb.writeln('        }');
    }
    sb.writeln('      default:');
    sb.writeln('        break;');
    sb.writeln('    }');
  }
  sb.writeln(
      '    return super.dispatch(interfaceId, methodId, params, paramsCapabilities: paramsCapabilities);');
  sb.writeln('  }');
  sb.writeln();
  sb.writeln('  @override');
  sb.writeln('  Future<void> dispose() async {}');
  sb.writeln('}');
}

/// Returns the [InterfaceRefType] if [node] is a result struct with exactly one
/// non-void field that is an interface reference; otherwise returns `null`.
InterfaceRefType? _singleCapabilityField(
    SchemaNode? node, Map<int, SchemaNode> nodeMap) {
  if (node == null) return null;
  final body = node.body;
  if (body is! StructBody) return null;
  final nonVoid = body.fields.where((f) {
    if (f.body is! SlotField) return false;
    return (f.body as SlotField).type is! VoidType;
  }).toList();
  if (nonVoid.length != 1) return null;
  final sf = nonVoid.first.body as SlotField;
  return sf.type is InterfaceRefType ? sf.type as InterfaceRefType : null;
}

// ---------------------------------------------------------------------------
// Enum generation
// ---------------------------------------------------------------------------

void _writeEnum(StringBuffer sb, SchemaNode node, EnumBody body) {
  final name = _dartClassName(node.displayName);
  final sorted = [...body.enumerants]
    ..sort((a, b) => a.codeOrder.compareTo(b.codeOrder));

  sb.writeln('enum $name {');
  for (final e in sorted) {
    sb.writeln('  ${_camel(e.name)},');
  }
  sb.writeln('}');
  sb.writeln();
  sb.writeln(
      '$name? ${_lcfirst(name)}FromUint16(int v) => '
      'v < $name.values.length ? $name.values[v] : null;');
  sb.writeln('int ${_lcfirst(name)}ToUint16($name v) => v.index;');
}

// ---------------------------------------------------------------------------
// Struct generation
// ---------------------------------------------------------------------------

void _writeStruct(
  StringBuffer sb,
  SchemaNode node,
  StructBody body,
  Map<int, SchemaNode> nodeMap,
) {
  final name = _dartClassName(node.displayName);
  final dataWords = body.dataWordCount;
  final ptrWords = body.pointerCount;

  final fields = [...body.fields]
    ..sort((a, b) => a.codeOrder.compareTo(b.codeOrder));

  // ---- Reader ----
  sb.writeln('final class ${name}Reader extends StructReader {');
  sb.writeln('  ${name}Reader(super.raw);');

  if (body.discriminantCount > 0) {
    final discByteOffset = body.discriminantOffset * 2;
    sb.writeln();
    sb.writeln('  int get which => getUint16Field($discByteOffset);');
  }

  for (final field in fields) {
    _writeReaderField(sb, field, nodeMap);
  }
  sb.writeln('}');
  sb.writeln();

  // ---- Builder ----
  sb.writeln('final class ${name}Builder extends StructBuilder {');
  sb.writeln('  ${name}Builder(super.raw);');
  sb.writeln();
  sb.writeln('  @override');
  sb.writeln('  ${name}Reader asReader() => ${name}Reader(rawToReader());');

  if (body.discriminantCount > 0) {
    final discByteOffset = body.discriminantOffset * 2;
    sb.writeln();
    sb.writeln('  void _setWhich(int v) => setUint16Field($discByteOffset, v);');
  }

  for (final field in fields) {
    _writeBuilderField(sb, field, nodeMap, body);
  }
  sb.writeln('}');
  sb.writeln();

  // ---- Factory ----
  sb.writeln('final class _${name}Factory');
  sb.writeln('    extends StructFactory<${name}Reader, ${name}Builder> {');
  sb.writeln('  @override int get dataWords => $dataWords;');
  sb.writeln('  @override int get ptrWords => $ptrWords;');
  sb.writeln('  @override');
  sb.writeln(
      '  ${name}Reader fromRawReader(RawStructReader r) => ${name}Reader(r);');
  sb.writeln('  @override');
  sb.writeln(
      '  ${name}Builder fromRawBuilder(RawStructBuilder r) => ${name}Builder(r);');
  sb.writeln('}');
  sb.writeln();
  sb.writeln('final ${_lcfirst(name)}Factory = _${name}Factory();');
}

void _writeReaderField(
  StringBuffer sb,
  SchemaField field,
  Map<int, SchemaNode> nodeMap,
) {
  final fname = _camel(field.name);
  sb.writeln();

  if (field.body is GroupField) {
    final gf = field.body as GroupField;
    final groupNode = nodeMap[gf.typeId];
    if (groupNode == null) return;
    final gname = _dartClassName(groupNode.displayName);
    sb.writeln('  ${gname}Reader get $fname => ${gname}Reader(raw);');
    return;
  }

  final sf = field.body as SlotField;
  final type = sf.type;
  final offset = sf.offset;

  final (dartType, getter) = _readerGetter(type, offset, nodeMap);
  sb.writeln('  $dartType get $fname => $getter;');
}

void _writeBuilderField(
  StringBuffer sb,
  SchemaField field,
  Map<int, SchemaNode> nodeMap,
  StructBody structBody,
) {
  final fname = _camel(field.name);
  final discVal = field.discriminantValue;
  final hasDisc = field.isUnionField;
  final discByteOffset = structBody.discriminantOffset * 2;

  if (field.body is GroupField) {
    final gf = field.body as GroupField;
    final groupNode = nodeMap[gf.typeId];
    if (groupNode == null) return;
    final gname = _dartClassName(groupNode.displayName);
    sb.writeln();
    if (hasDisc) {
      sb.writeln('  ${gname}Builder get $fname {');
      sb.writeln('    setUint16Field($discByteOffset, $discVal);');
      sb.writeln('    return ${gname}Builder(raw);');
      sb.writeln('  }');
    } else {
      sb.writeln('  ${gname}Builder get $fname => ${gname}Builder(raw);');
    }
    return;
  }

  final sf = field.body as SlotField;
  final type = sf.type;
  final offset = sf.offset;

  sb.writeln();

  if (_isPointerType(type)) {
    _writeBuilderPointerField(sb, fname, type, offset, nodeMap, hasDisc,
        discVal, discByteOffset);
  } else {
    _writeBuilderDataField(
        sb, fname, type, offset, nodeMap, hasDisc, discVal, discByteOffset);
  }
}

void _writeBuilderDataField(
  StringBuffer sb,
  String fname,
  SchemaType type,
  int offset,
  Map<int, SchemaNode> nodeMap,
  bool hasDisc,
  int discVal,
  int discByteOffset,
) {
  final (dartType, setter) = _builderDataSetter(type, offset, nodeMap);
  sb.writeln('  set $fname($dartType v) {');
  if (hasDisc) {
    sb.writeln('    setUint16Field($discByteOffset, $discVal);');
  }
  sb.writeln('    $setter;');
  sb.writeln('  }');
}

void _writeBuilderPointerField(
  StringBuffer sb,
  String fname,
  SchemaType type,
  int offset,
  Map<int, SchemaNode> nodeMap,
  bool hasDisc,
  int discVal,
  int discByteOffset,
) {
  final setDisc =
      hasDisc ? '    setUint16Field($discByteOffset, $discVal);\n' : '';

  if (type is TextType) {
    sb.writeln('  set $fname(String? v) {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    setTextField($offset, v);');
    sb.writeln('  }');
  } else if (type is DataType) {
    sb.writeln('  set $fname(Uint8List? v) {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    setDataField($offset, v);');
    sb.writeln('  }');
  } else if (type is StructRefType) {
    final refNode = nodeMap[type.typeId];
    final refName = _dartClassName(refNode?.displayName ?? 'Unknown');
    final refBody = refNode?.body;
    final dw = refBody is StructBody ? refBody.dataWordCount : 0;
    final pw = refBody is StructBody ? refBody.pointerCount : 0;
    final ucfname = _ucfirst(fname);
    sb.writeln('  ${refName}Builder init$ucfname() {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    return initStructFieldWith($offset,');
    sb.writeln('        (r) => ${refName}Builder(r), $dw, $pw);');
    sb.writeln('  }');
    sb.writeln();
    sb.writeln('  bool has$ucfname() => hasPointerField($offset);');
  } else if (type is ListType) {
    _writeListBuilderField(
        sb, fname, type, offset, nodeMap, setDisc, hasDisc);
  } else if (type is AnyPointerType) {
    sb.writeln('  set $fname(Uint8List? v) {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    if (v != null) setAnyPointerFromMessage($offset, v);');
    sb.writeln('  }');
  } else if (type is InterfaceRefType) {
    final ucfname = _ucfirst(fname);
    sb.writeln('  void set$ucfname(int capTableIndex) {');
    if (hasDisc) sb.write(setDisc);
    sb.writeln('    setCapabilityField($offset, capTableIndex);');
    sb.writeln('  }');
  }
}

void _writeListBuilderField(
  StringBuffer sb,
  String fname,
  ListType type,
  int offset,
  Map<int, SchemaNode> nodeMap,
  String setDisc,
  bool hasDisc,
) {
  final ucfname = _ucfirst(fname);
  final elem = type.elementType;

  final (initCall, retType) = _listInitCall(elem, offset, nodeMap);
  sb.writeln('  $retType init$ucfname(int length) {');
  if (hasDisc) sb.write(setDisc);
  sb.writeln('    return $initCall;');
  sb.writeln('  }');
}

// ---------------------------------------------------------------------------
// Helpers: type mapping
// ---------------------------------------------------------------------------

(String, String) _readerGetter(
  SchemaType type,
  int offset,
  Map<int, SchemaNode> nodeMap,
) {
  return switch (type) {
    VoidType() => ('void', '{}'),
    BoolType() => ('bool', 'getBoolField($offset)'),
    Int8Type() => ('int', 'getInt8Field($offset)'),
    Int16Type() => ('int', 'getInt16Field(${offset * 2})'),
    Int32Type() => ('int', 'getInt32Field(${offset * 4})'),
    Int64Type() => ('int', 'getInt64Field(${offset * 8})'),
    UInt8Type() => ('int', 'getUint8Field($offset)'),
    UInt16Type() => ('int', 'getUint16Field(${offset * 2})'),
    UInt32Type() => ('int', 'getUint32Field(${offset * 4})'),
    UInt64Type() => ('int', 'getUint64Field(${offset * 8})'),
    Float32Type() => ('double', 'getFloat32Field(${offset * 4})'),
    Float64Type() => ('double', 'getFloat64Field(${offset * 8})'),
    TextType() => ('String?', 'getTextField($offset)'),
    DataType() => ('Uint8List?', 'getDataField($offset)'),
    AnyPointerType() => ('Uint8List?', 'getAnyPointerAsMessageBytes($offset)'),
    EnumRefType(:final typeId) =>
      _enumReaderGetter(typeId, offset * 2, nodeMap),
    StructRefType(:final typeId) =>
      _structReaderGetter(typeId, offset, nodeMap),
    ListType(:final elementType) =>
      _listReaderGetter(elementType, offset, nodeMap),
    _ => ('dynamic', 'null /* unsupported type */'),
  };
}

(String, String) _enumReaderGetter(
    int typeId, int byteOffset, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownEnum');
  // fromUint16 returns $name? to handle unknown values from newer schemas.
  return ('$name?', '${_lcfirst(name)}FromUint16(getUint16Field($byteOffset))');
}

(String, String) _structReaderGetter(
    int typeId, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownStruct');
  return ('${name}Reader?',
      'getStructFieldWith($ptrIndex, (r) => ${name}Reader(r))');
}

(String, String) _listReaderGetter(
    SchemaType elem, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  return switch (elem) {
    BoolType() => ('ListReader<bool>?', 'getBoolListField($ptrIndex)'),
    Int8Type() => ('ListReader<int>?', 'getInt8ListField($ptrIndex)'),
    Int16Type() => ('ListReader<int>?', 'getInt16ListField($ptrIndex)'),
    Int32Type() => ('ListReader<int>?', 'getInt32ListField($ptrIndex)'),
    Int64Type() => ('ListReader<int>?', 'getInt64ListField($ptrIndex)'),
    UInt8Type() => ('ListReader<int>?', 'getUint8ListField($ptrIndex)'),
    UInt16Type() => ('ListReader<int>?', 'getUint16ListField($ptrIndex)'),
    UInt32Type() => ('ListReader<int>?', 'getUint32ListField($ptrIndex)'),
    UInt64Type() => ('ListReader<int>?', 'getUint64ListField($ptrIndex)'),
    Float32Type() =>
      ('ListReader<double>?', 'getFloat32ListField($ptrIndex)'),
    Float64Type() =>
      ('ListReader<double>?', 'getFloat64ListField($ptrIndex)'),
    TextType() => ('ListReader<String?>?', 'getTextListField($ptrIndex)'),
    DataType() =>
      ('ListReader<Uint8List?>?', 'getDataListField($ptrIndex)'),
    StructRefType(:final typeId) =>
      _structListReaderGetter(typeId, ptrIndex, nodeMap),
    _ => ('ListReader<dynamic>?', 'null /* unsupported list element */'),
  };
}

(String, String) _structListReaderGetter(
    int typeId, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownStruct');
  return ('ListReader<${name}Reader>?',
      'getStructListFieldWith($ptrIndex, (r) => ${name}Reader(r))');
}

(String, String) _builderDataSetter(
    SchemaType type, int offset, Map<int, SchemaNode> nodeMap) {
  return switch (type) {
    BoolType() => ('bool', 'setBoolField($offset, v)'),
    Int8Type() => ('int', 'setInt8Field($offset, v)'),
    Int16Type() => ('int', 'setInt16Field(${offset * 2}, v)'),
    Int32Type() => ('int', 'setInt32Field(${offset * 4}, v)'),
    Int64Type() => ('int', 'setInt64Field(${offset * 8}, v)'),
    UInt8Type() => ('int', 'setUint8Field($offset, v)'),
    UInt16Type() => ('int', 'setUint16Field(${offset * 2}, v)'),
    UInt32Type() => ('int', 'setUint32Field(${offset * 4}, v)'),
    UInt64Type() => ('int', 'setUint64Field(${offset * 8}, v)'),
    Float32Type() => ('double', 'setFloat32Field(${offset * 4}, v)'),
    Float64Type() => ('double', 'setFloat64Field(${offset * 8}, v)'),
    EnumRefType(:final typeId) =>
      _enumBuilderSetter(typeId, offset * 2, nodeMap),
    _ => ('dynamic', '/* unsupported data type */'),
  };
}

(String, String) _enumBuilderSetter(
    int typeId, int byteOffset, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownEnum');
  return (name, 'setUint16Field($byteOffset, ${_lcfirst(name)}ToUint16(v))');
}

(String, String) _listInitCall(
    SchemaType elem, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  return switch (elem) {
    BoolType() => ('initBoolListField($ptrIndex, length)', 'ListBuilder<bool>'),
    Int8Type() =>
      ('initInt8ListField($ptrIndex, length)', 'ListBuilder<int>'),
    Int16Type() =>
      ('initInt16ListField($ptrIndex, length)', 'ListBuilder<int>'),
    Int32Type() =>
      ('initInt32ListField($ptrIndex, length)', 'ListBuilder<int>'),
    Int64Type() =>
      ('initInt64ListField($ptrIndex, length)', 'ListBuilder<int>'),
    UInt8Type() =>
      ('initUint8ListField($ptrIndex, length)', 'ListBuilder<int>'),
    UInt16Type() =>
      ('initUint16ListField($ptrIndex, length)', 'ListBuilder<int>'),
    UInt32Type() =>
      ('initUint32ListField($ptrIndex, length)', 'ListBuilder<int>'),
    UInt64Type() =>
      ('initUint64ListField($ptrIndex, length)', 'ListBuilder<int>'),
    Float32Type() =>
      ('initFloat32ListField($ptrIndex, length)', 'ListBuilder<double>'),
    Float64Type() =>
      ('initFloat64ListField($ptrIndex, length)', 'ListBuilder<double>'),
    TextType() =>
      ('initTextListField($ptrIndex, length)', 'ListBuilder<String?>'),
    DataType() =>
      ('initDataListField($ptrIndex, length)', 'ListBuilder<Uint8List?>'),
    StructRefType(:final typeId) =>
      _structListInitCall(typeId, ptrIndex, nodeMap),
    _ => ('/* unsupported */', 'dynamic'),
  };
}

(String, String) _structListInitCall(
    int typeId, int ptrIndex, Map<int, SchemaNode> nodeMap) {
  final node = nodeMap[typeId];
  final name = _dartClassName(node?.displayName ?? 'UnknownStruct');
  final body = node?.body;
  final dw = body is StructBody ? body.dataWordCount : 0;
  final pw = body is StructBody ? body.pointerCount : 0;
  final initCall = 'initStructListFieldWith($ptrIndex, length, '
      '(r) => ${name}Builder(r), $dw, $pw)';
  return (initCall, 'ListBuilder<${name}Builder>');
}

bool _isPointerType(SchemaType t) => switch (t) {
      TextType() ||
      DataType() ||
      StructRefType() ||
      ListType() ||
      InterfaceRefType() ||
      AnyPointerType() =>
        true,
      _ => false,
    };

// ---------------------------------------------------------------------------
// Identifier helpers
// ---------------------------------------------------------------------------

String _dartClassName(String rawName) {
  var name = rawName;
  final colonIdx = name.lastIndexOf(':');
  if (colonIdx >= 0) name = name.substring(colonIdx + 1);
  if (name.contains(r'$') && name.contains('.')) {
    name = name.split('.').map(_ucfirst).join();
  } else {
    final dotIdx = name.lastIndexOf('.');
    if (dotIdx >= 0) name = name.substring(dotIdx + 1);
  }
  if (name.contains(r'$')) {
    name = name.split(r'$').map(_ucfirst).join();
  }
  return name;
}

String _camel(String s) {
  if (s.isEmpty) return s;
  if (s[0] == s[0].toLowerCase()) return s;
  return s[0].toLowerCase() + s.substring(1);
}

String _lcfirst(String s) =>
    s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);
String _ucfirst(String s) =>
    s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

String _hexId(int id) {
  final hi = id >>> 32;
  final lo = id & 0xFFFFFFFF;
  return '0x${hi.toRadixString(16).padLeft(8, '0')}${lo.toRadixString(16).padLeft(8, '0')}';
}
