name: capnproto_dart
description: A pure Dart implementation of Cap'n Proto serialization and streaming.
version: 0.1.0
# repository: https://github.com/my_org/capnproto-dart

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
