name: complex_client
description: Complex schema interoperability sample.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  capnproto_dart:
    path: ../../../packages/capnproto_dart
  capnproto_dart_rpc:
    path: ../../../packages/capnproto_dart_rpc
