// Generated by capnpc-dart — do not edit by hand.
// ignore_for_file: annotate_overrides, unnecessary_this

import 'dart:typed_data';
import 'package:capnproto_dart/capnproto_dart.dart';
import 'package:capnproto_dart_rpc/capnproto_dart_rpc.dart';

final class GreetSessionGreetParamsReader extends StructReader {
  GreetSessionGreetParamsReader(super.raw);
}

final class GreetSessionGreetParamsBuilder extends StructBuilder {
  GreetSessionGreetParamsBuilder(super.raw);

  @override
  GreetSessionGreetParamsReader asReader() => throw UnimplementedError();
}

final class _GreetSessionGreetParamsFactory
    extends StructFactory<GreetSessionGreetParamsReader, GreetSessionGreetParamsBuilder> {
  @override int get dataWords => 0;
  @override int get ptrWords => 0;
  @override
  GreetSessionGreetParamsReader fromRawReader(RawStructReader r) => GreetSessionGreetParamsReader(r);
  @override
  GreetSessionGreetParamsBuilder fromRawBuilder(RawStructBuilder r) => GreetSessionGreetParamsBuilder(r);
}

final greetSessionGreetParamsFactory = _GreetSessionGreetParamsFactory();

final class GreetSessionGreetResultsReader extends StructReader {
  GreetSessionGreetResultsReader(super.raw);

  String? get reply => getTextField(0);
}

final class GreetSessionGreetResultsBuilder extends StructBuilder {
  GreetSessionGreetResultsBuilder(super.raw);

  @override
  GreetSessionGreetResultsReader asReader() => throw UnimplementedError();

  set reply(String? v) {
    setTextField(0, v);
  }
}

final class _GreetSessionGreetResultsFactory
    extends StructFactory<GreetSessionGreetResultsReader, GreetSessionGreetResultsBuilder> {
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreetSessionGreetResultsReader fromRawReader(RawStructReader r) => GreetSessionGreetResultsReader(r);
  @override
  GreetSessionGreetResultsBuilder fromRawBuilder(RawStructBuilder r) => GreetSessionGreetResultsBuilder(r);
}

final greetSessionGreetResultsFactory = _GreetSessionGreetResultsFactory();

final class GreeterGreetParamsReader extends StructReader {
  GreeterGreetParamsReader(super.raw);

  String? get name => getTextField(0);
}

final class GreeterGreetParamsBuilder extends StructBuilder {
  GreeterGreetParamsBuilder(super.raw);

  @override
  GreeterGreetParamsReader asReader() => throw UnimplementedError();

  set name(String? v) {
    setTextField(0, v);
  }
}

final class _GreeterGreetParamsFactory
    extends StructFactory<GreeterGreetParamsReader, GreeterGreetParamsBuilder> {
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreeterGreetParamsReader fromRawReader(RawStructReader r) => GreeterGreetParamsReader(r);
  @override
  GreeterGreetParamsBuilder fromRawBuilder(RawStructBuilder r) => GreeterGreetParamsBuilder(r);
}

final greeterGreetParamsFactory = _GreeterGreetParamsFactory();

final class GreeterGreetResultsReader extends StructReader {
  GreeterGreetResultsReader(super.raw);

  String? get reply => getTextField(0);
}

final class GreeterGreetResultsBuilder extends StructBuilder {
  GreeterGreetResultsBuilder(super.raw);

  @override
  GreeterGreetResultsReader asReader() => throw UnimplementedError();

  set reply(String? v) {
    setTextField(0, v);
  }
}

final class _GreeterGreetResultsFactory
    extends StructFactory<GreeterGreetResultsReader, GreeterGreetResultsBuilder> {
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreeterGreetResultsReader fromRawReader(RawStructReader r) => GreeterGreetResultsReader(r);
  @override
  GreeterGreetResultsBuilder fromRawBuilder(RawStructBuilder r) => GreeterGreetResultsBuilder(r);
}

final greeterGreetResultsFactory = _GreeterGreetResultsFactory();

final class GreeterNewSessionParamsReader extends StructReader {
  GreeterNewSessionParamsReader(super.raw);

  String? get name => getTextField(0);
}

final class GreeterNewSessionParamsBuilder extends StructBuilder {
  GreeterNewSessionParamsBuilder(super.raw);

  @override
  GreeterNewSessionParamsReader asReader() => throw UnimplementedError();

  set name(String? v) {
    setTextField(0, v);
  }
}

final class _GreeterNewSessionParamsFactory
    extends StructFactory<GreeterNewSessionParamsReader, GreeterNewSessionParamsBuilder> {
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreeterNewSessionParamsReader fromRawReader(RawStructReader r) => GreeterNewSessionParamsReader(r);
  @override
  GreeterNewSessionParamsBuilder fromRawBuilder(RawStructBuilder r) => GreeterNewSessionParamsBuilder(r);
}

final greeterNewSessionParamsFactory = _GreeterNewSessionParamsFactory();

final class GreeterNewSessionResultsReader extends StructReader {
  GreeterNewSessionResultsReader(super.raw);

  dynamic get session => null /* unsupported type */;
}

final class GreeterNewSessionResultsBuilder extends StructBuilder {
  GreeterNewSessionResultsBuilder(super.raw);

  @override
  GreeterNewSessionResultsReader asReader() => throw UnimplementedError();

}

final class _GreeterNewSessionResultsFactory
    extends StructFactory<GreeterNewSessionResultsReader, GreeterNewSessionResultsBuilder> {
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreeterNewSessionResultsReader fromRawReader(RawStructReader r) => GreeterNewSessionResultsReader(r);
  @override
  GreeterNewSessionResultsBuilder fromRawBuilder(RawStructBuilder r) => GreeterNewSessionResultsBuilder(r);
}

final greeterNewSessionResultsFactory = _GreeterNewSessionResultsFactory();

class GreetSessionClient extends Capability {
  static const int _interfaceId = 0xb5f4a6c78d3e1029;

  final Capability _cap;
  GreetSessionClient(this._cap);

  Future<GreetSessionGreetResultsReader> greet(void Function(GreetSessionGreetParamsBuilder) build) async {
    final mb = MessageBuilder();
    build(mb.initRoot(greetSessionGreetParamsFactory));
    final result = await _cap.dispatch(_interfaceId, 0, mb.serialize());
    return MessageReader.deserialize(result.bytes).getRoot(greetSessionGreetResultsFactory);
  }

  @override
  Future<void> dispose() => _cap.dispose();
}

class GreetSessionClientFactory extends CapabilityFactory<GreetSessionClient> {
  @override
  GreetSessionClient fromCapability(Capability cap) => GreetSessionClient(cap);
}

class GreeterClient extends Capability {
  static const int _interfaceId = 0xd41d8cd98f00b204;

  final Capability _cap;
  GreeterClient(this._cap);

  Future<GreeterGreetResultsReader> greet(void Function(GreeterGreetParamsBuilder) build) async {
    final mb = MessageBuilder();
    build(mb.initRoot(greeterGreetParamsFactory));
    final result = await _cap.dispatch(_interfaceId, 0, mb.serialize());
    return MessageReader.deserialize(result.bytes).getRoot(greeterGreetResultsFactory);
  }

  Future<GreetSessionClient> newSession(void Function(GreeterNewSessionParamsBuilder) build) async {
    final mb = MessageBuilder();
    build(mb.initRoot(greeterNewSessionParamsFactory));
    final result = await _cap.dispatch(_interfaceId, 1, mb.serialize());
    return GreetSessionClient(result.caps[0]);
  }

  @override
  Future<void> dispose() => _cap.dispose();
}

class GreeterClientFactory extends CapabilityFactory<GreeterClient> {
  @override
  GreeterClient fromCapability(Capability cap) => GreeterClient(cap);
}

