// Generated by capnpc-dart — do not edit by hand.
// ignore_for_file: annotate_overrides, unnecessary_this

import 'dart:typed_data';
import 'package:capnproto_dart_rpc/capnproto_dart_rpc.dart';

final class GreetSessionGreetParamsReader extends StructReader {
  GreetSessionGreetParamsReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = greetSessionGreetParamsSchema;
}

final class GreetSessionGreetParamsBuilder extends StructBuilder {
  GreetSessionGreetParamsBuilder(super.raw);

  @override
  GreetSessionGreetParamsReader asReader() => GreetSessionGreetParamsReader(rawToReader());
}

final class _GreetSessionGreetParamsFactory
    extends StructFactory<GreetSessionGreetParamsReader, GreetSessionGreetParamsBuilder> {
  @override StructSchemaInfo get schema => greetSessionGreetParamsSchema;
  @override int get dataWords => 0;
  @override int get ptrWords => 0;
  @override
  GreetSessionGreetParamsReader fromRawReader(RawStructReader r) => GreetSessionGreetParamsReader(r);
  @override
  GreetSessionGreetParamsReader fromRawReaderWithCapabilities(RawStructReader r, List<Object?> capabilities) => GreetSessionGreetParamsReader(r, capabilities: capabilities);
  @override
  GreetSessionGreetParamsBuilder fromRawBuilder(RawStructBuilder r) => GreetSessionGreetParamsBuilder(r);
}

const StructSchemaInfo greetSessionGreetParamsSchema = StructSchemaInfo(
  id: 0xe935a66aac554355,
  displayName: 'greeter.capnp:GreetSession.greet\$Params',
  shortName: 'greet\$Params',
  dataWords: 0,
  pointerWords: 0,
  fields: [
  ],
);

final greetSessionGreetParamsFactory = _GreetSessionGreetParamsFactory();

final class GreetSessionGreetResultsReader extends StructReader {
  GreetSessionGreetResultsReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = greetSessionGreetResultsSchema;

  String? get reply => getTextField(0);
}

final class GreetSessionGreetResultsBuilder extends StructBuilder {
  GreetSessionGreetResultsBuilder(super.raw);

  @override
  GreetSessionGreetResultsReader asReader() => GreetSessionGreetResultsReader(rawToReader());

  set reply(String? v) {
    setTextField(0, v);
  }
}

final class _GreetSessionGreetResultsFactory
    extends StructFactory<GreetSessionGreetResultsReader, GreetSessionGreetResultsBuilder> {
  @override StructSchemaInfo get schema => greetSessionGreetResultsSchema;
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreetSessionGreetResultsReader fromRawReader(RawStructReader r) => GreetSessionGreetResultsReader(r);
  @override
  GreetSessionGreetResultsReader fromRawReaderWithCapabilities(RawStructReader r, List<Object?> capabilities) => GreetSessionGreetResultsReader(r, capabilities: capabilities);
  @override
  GreetSessionGreetResultsBuilder fromRawBuilder(RawStructBuilder r) => GreetSessionGreetResultsBuilder(r);
}

const StructSchemaInfo greetSessionGreetResultsSchema = StructSchemaInfo(
  id: 0xb11eef075dd40768,
  displayName: 'greeter.capnp:GreetSession.greet\$Results',
  shortName: 'greet\$Results',
  dataWords: 0,
  pointerWords: 1,
  fields: [
    FieldSchemaInfo(
      name: 'reply',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(
        offset: 0,
        type: PrimitiveTypeSchemaInfo('Text'),
      ),
    ),
  ],
);

final greetSessionGreetResultsFactory = _GreetSessionGreetResultsFactory();

final class GreeterGreetParamsReader extends StructReader {
  GreeterGreetParamsReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = greeterGreetParamsSchema;

  String? get name => getTextField(0);
}

final class GreeterGreetParamsBuilder extends StructBuilder {
  GreeterGreetParamsBuilder(super.raw);

  @override
  GreeterGreetParamsReader asReader() => GreeterGreetParamsReader(rawToReader());

  set name(String? v) {
    setTextField(0, v);
  }
}

final class _GreeterGreetParamsFactory
    extends StructFactory<GreeterGreetParamsReader, GreeterGreetParamsBuilder> {
  @override StructSchemaInfo get schema => greeterGreetParamsSchema;
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreeterGreetParamsReader fromRawReader(RawStructReader r) => GreeterGreetParamsReader(r);
  @override
  GreeterGreetParamsReader fromRawReaderWithCapabilities(RawStructReader r, List<Object?> capabilities) => GreeterGreetParamsReader(r, capabilities: capabilities);
  @override
  GreeterGreetParamsBuilder fromRawBuilder(RawStructBuilder r) => GreeterGreetParamsBuilder(r);
}

const StructSchemaInfo greeterGreetParamsSchema = StructSchemaInfo(
  id: 0xe8328d642eb4ddbb,
  displayName: 'greeter.capnp:Greeter.greet\$Params',
  shortName: 'greet\$Params',
  dataWords: 0,
  pointerWords: 1,
  fields: [
    FieldSchemaInfo(
      name: 'name',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(
        offset: 0,
        type: PrimitiveTypeSchemaInfo('Text'),
      ),
    ),
  ],
);

final greeterGreetParamsFactory = _GreeterGreetParamsFactory();

final class GreeterGreetResultsReader extends StructReader {
  GreeterGreetResultsReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = greeterGreetResultsSchema;

  String? get reply => getTextField(0);
}

final class GreeterGreetResultsBuilder extends StructBuilder {
  GreeterGreetResultsBuilder(super.raw);

  @override
  GreeterGreetResultsReader asReader() => GreeterGreetResultsReader(rawToReader());

  set reply(String? v) {
    setTextField(0, v);
  }
}

final class _GreeterGreetResultsFactory
    extends StructFactory<GreeterGreetResultsReader, GreeterGreetResultsBuilder> {
  @override StructSchemaInfo get schema => greeterGreetResultsSchema;
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreeterGreetResultsReader fromRawReader(RawStructReader r) => GreeterGreetResultsReader(r);
  @override
  GreeterGreetResultsReader fromRawReaderWithCapabilities(RawStructReader r, List<Object?> capabilities) => GreeterGreetResultsReader(r, capabilities: capabilities);
  @override
  GreeterGreetResultsBuilder fromRawBuilder(RawStructBuilder r) => GreeterGreetResultsBuilder(r);
}

const StructSchemaInfo greeterGreetResultsSchema = StructSchemaInfo(
  id: 0xc1381616d86e0ad3,
  displayName: 'greeter.capnp:Greeter.greet\$Results',
  shortName: 'greet\$Results',
  dataWords: 0,
  pointerWords: 1,
  fields: [
    FieldSchemaInfo(
      name: 'reply',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(
        offset: 0,
        type: PrimitiveTypeSchemaInfo('Text'),
      ),
    ),
  ],
);

final greeterGreetResultsFactory = _GreeterGreetResultsFactory();

final class GreeterNewSessionParamsReader extends StructReader {
  GreeterNewSessionParamsReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = greeterNewSessionParamsSchema;

  String? get name => getTextField(0);
}

final class GreeterNewSessionParamsBuilder extends StructBuilder {
  GreeterNewSessionParamsBuilder(super.raw);

  @override
  GreeterNewSessionParamsReader asReader() => GreeterNewSessionParamsReader(rawToReader());

  set name(String? v) {
    setTextField(0, v);
  }
}

final class _GreeterNewSessionParamsFactory
    extends StructFactory<GreeterNewSessionParamsReader, GreeterNewSessionParamsBuilder> {
  @override StructSchemaInfo get schema => greeterNewSessionParamsSchema;
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreeterNewSessionParamsReader fromRawReader(RawStructReader r) => GreeterNewSessionParamsReader(r);
  @override
  GreeterNewSessionParamsReader fromRawReaderWithCapabilities(RawStructReader r, List<Object?> capabilities) => GreeterNewSessionParamsReader(r, capabilities: capabilities);
  @override
  GreeterNewSessionParamsBuilder fromRawBuilder(RawStructBuilder r) => GreeterNewSessionParamsBuilder(r);
}

const StructSchemaInfo greeterNewSessionParamsSchema = StructSchemaInfo(
  id: 0xbdd3ce0b4a587bd9,
  displayName: 'greeter.capnp:Greeter.newSession\$Params',
  shortName: 'newSession\$Params',
  dataWords: 0,
  pointerWords: 1,
  fields: [
    FieldSchemaInfo(
      name: 'name',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(
        offset: 0,
        type: PrimitiveTypeSchemaInfo('Text'),
      ),
    ),
  ],
);

final greeterNewSessionParamsFactory = _GreeterNewSessionParamsFactory();

final class GreeterNewSessionResultsReader extends StructReader {
  GreeterNewSessionResultsReader(super.raw, {super.capabilities});

  static const StructSchemaInfo schema = greeterNewSessionResultsSchema;

  GreetSessionClient? get session {
    final cap = getCapabilityObjectField(0);
    return cap == null ? null : GreetSessionClient(vendCapabilityHandle(cap as Capability));
  }

  int get sessionCapIndex => getCapabilityField(0);
}

final class GreeterNewSessionResultsBuilder extends StructBuilder {
  GreeterNewSessionResultsBuilder(super.raw);

  @override
  GreeterNewSessionResultsReader asReader() => GreeterNewSessionResultsReader(rawToReader());

  void setSession(int capTableIndex) {
    setCapabilityField(0, capTableIndex);
  }

  void setSessionTyped(GreetSessionClient cap, List<Object?> capTable) {
    capTable.add(cap.capability);
    setCapabilityField(0, capTable.length - 1);
  }
}

final class _GreeterNewSessionResultsFactory
    extends StructFactory<GreeterNewSessionResultsReader, GreeterNewSessionResultsBuilder> {
  @override StructSchemaInfo get schema => greeterNewSessionResultsSchema;
  @override int get dataWords => 0;
  @override int get ptrWords => 1;
  @override
  GreeterNewSessionResultsReader fromRawReader(RawStructReader r) => GreeterNewSessionResultsReader(r);
  @override
  GreeterNewSessionResultsReader fromRawReaderWithCapabilities(RawStructReader r, List<Object?> capabilities) => GreeterNewSessionResultsReader(r, capabilities: capabilities);
  @override
  GreeterNewSessionResultsBuilder fromRawBuilder(RawStructBuilder r) => GreeterNewSessionResultsBuilder(r);
}

const StructSchemaInfo greeterNewSessionResultsSchema = StructSchemaInfo(
  id: 0x9d89651a31cd267c,
  displayName: 'greeter.capnp:Greeter.newSession\$Results',
  shortName: 'newSession\$Results',
  dataWords: 0,
  pointerWords: 1,
  fields: [
    FieldSchemaInfo(
      name: 'session',
      codeOrder: 0,
      body: SlotFieldSchemaInfo(
        offset: 0,
        type: InterfaceRefTypeSchemaInfo(0xb5f4a6c78d3e1029),
      ),
    ),
  ],
);

final greeterNewSessionResultsFactory = _GreeterNewSessionResultsFactory();

class GreetSessionClient extends Capability {
  static const int _interfaceId = 0xb5f4a6c78d3e1029;
  static const InterfaceSchemaInfo schema = greetSessionSchema;

  final Capability _cap;
  GreetSessionClient(this._cap);
  Capability get capability => _cap;

  Future<GreetSessionGreetResultsReader> greet(void Function(GreetSessionGreetParamsBuilder) build) async {
    final result = await _cap.dispatchBuilding(0xb5f4a6c78d3e1029, 0, (anyPtr) => build(anyPtr.initStruct(greetSessionGreetParamsFactory)));
    return result.payload.getTyped(greetSessionGreetResultsFactory, capabilities: result.caps);
  }

  @override
  Future<void> dispose() => _cap.dispose();
}

const InterfaceSchemaInfo greetSessionSchema = InterfaceSchemaInfo(
  id: 0xb5f4a6c78d3e1029,
  displayName: 'greeter.capnp:GreetSession',
  shortName: 'GreetSession',
  methods: [
    MethodSchemaInfo(
      name: 'greet',
      ordinal: 0,
      paramStructTypeId: 0xe935a66aac554355,
      resultStructTypeId: 0xb11eef075dd40768,
    ),
  ],
);

class GreetSessionClientFactory extends CapabilityFactory<GreetSessionClient> {
  @override
  GreetSessionClient fromCapability(Capability cap) => GreetSessionClient(cap);
}

abstract class GreetSessionServer extends Capability {

  Future<DispatchResult> greet(GreetSessionGreetParamsReader params, List<Capability> paramsCapabilities);
  Future<DispatchResult> greetWithContext(GreetSessionGreetParamsReader params, List<Capability> paramsCapabilities, DispatchContext context) =>
      greet(params, paramsCapabilities);

  @override
  Future<DispatchResult> dispatch(int interfaceId, int methodId, RpcPayload params, {
    List<Capability> paramsCapabilities = const [],
  }) => dispatchWithContext(
    interfaceId,
    methodId,
    params,
    paramsCapabilities: paramsCapabilities,
  );

  @override
  Future<DispatchResult> dispatchWithContext(int interfaceId, int methodId, RpcPayload params, {
    List<Capability> paramsCapabilities = const [],
    DispatchContext? context,
  }) async {
    final dispatchContext = context ?? DispatchContext.neverCanceled;
    switch (interfaceId) {
      case 0xb5f4a6c78d3e1029:
        switch (methodId) {
          case 0:
            final p = params.getTyped(greetSessionGreetParamsFactory, capabilities: paramsCapabilities);
            return await greetWithContext(p, paramsCapabilities, dispatchContext);
          default:
            break;
        }
      default:
        break;
    }
    return super.dispatchWithContext(interfaceId, methodId, params, paramsCapabilities: paramsCapabilities, context: dispatchContext);
  }

  @override
  Future<void> dispose() async {}
}


final class GreeterNewSessionResult {
  GreeterNewSessionResult._(DispatchResult dispatchResult)
      :     session = GreetSessionClient(requireCapabilityFromResult(dispatchResult, 0)),
    result = dispatchResult.payload.getTyped(greeterNewSessionResultsFactory, capabilities: dispatchResult.caps);

  final GreeterNewSessionResultsReader result;
  final GreetSessionClient session;
}

final class GreeterNewSessionPipeline {
  GreeterNewSessionPipeline._(CapCall call)
      :     session = GreetSessionClient(call.pipelineResultPath([...const <int>[], 0])),
    result = call.result.then((r) => r.payload.getTyped(greeterNewSessionResultsFactory, capabilities: r.caps));

  final Future<GreeterNewSessionResultsReader> result;
  final GreetSessionClient session;
}
class GreeterClient extends Capability {
  static const int _interfaceId = 0xd41d8cd98f00b204;
  static const InterfaceSchemaInfo schema = greeterSchema;

  final Capability _cap;
  GreeterClient(this._cap);
  Capability get capability => _cap;

  Future<GreeterGreetResultsReader> greet(void Function(GreeterGreetParamsBuilder) build) async {
    final result = await _cap.dispatchBuilding(0xd41d8cd98f00b204, 0, (anyPtr) => build(anyPtr.initStruct(greeterGreetParamsFactory)));
    return result.payload.getTyped(greeterGreetResultsFactory, capabilities: result.caps);
  }

  Future<GreeterNewSessionResult> newSession(void Function(GreeterNewSessionParamsBuilder) build) async {
    final result = await _cap.dispatchBuilding(0xd41d8cd98f00b204, 1, (anyPtr) => build(anyPtr.initStruct(greeterNewSessionParamsFactory)));
    return GreeterNewSessionResult._(result);
  }

  GreeterNewSessionPipeline newSessionPipeline(void Function(GreeterNewSessionParamsBuilder) build) {
    final mb = MessageBuilder();
    build(mb.initRoot(greeterNewSessionParamsFactory));
    return GreeterNewSessionPipeline._(_cap.beginDispatch(0xd41d8cd98f00b204, 1, RpcPayload.fromBytes(mb.serialize())));
  }

  @override
  Future<void> dispose() => _cap.dispose();
}

const InterfaceSchemaInfo greeterSchema = InterfaceSchemaInfo(
  id: 0xd41d8cd98f00b204,
  displayName: 'greeter.capnp:Greeter',
  shortName: 'Greeter',
  methods: [
    MethodSchemaInfo(
      name: 'greet',
      ordinal: 0,
      paramStructTypeId: 0xe8328d642eb4ddbb,
      resultStructTypeId: 0xc1381616d86e0ad3,
    ),
    MethodSchemaInfo(
      name: 'newSession',
      ordinal: 1,
      paramStructTypeId: 0xbdd3ce0b4a587bd9,
      resultStructTypeId: 0x9d89651a31cd267c,
    ),
  ],
);

class GreeterClientFactory extends CapabilityFactory<GreeterClient> {
  @override
  GreeterClient fromCapability(Capability cap) => GreeterClient(cap);
}

abstract class GreeterServer extends Capability {

  Future<DispatchResult> greet(GreeterGreetParamsReader params, List<Capability> paramsCapabilities);
  Future<DispatchResult> greetWithContext(GreeterGreetParamsReader params, List<Capability> paramsCapabilities, DispatchContext context) =>
      greet(params, paramsCapabilities);

  Future<DispatchResult> newSession(GreeterNewSessionParamsReader params, List<Capability> paramsCapabilities);
  Future<DispatchResult> newSessionWithContext(GreeterNewSessionParamsReader params, List<Capability> paramsCapabilities, DispatchContext context) =>
      newSession(params, paramsCapabilities);

  @override
  Future<DispatchResult> dispatch(int interfaceId, int methodId, RpcPayload params, {
    List<Capability> paramsCapabilities = const [],
  }) => dispatchWithContext(
    interfaceId,
    methodId,
    params,
    paramsCapabilities: paramsCapabilities,
  );

  @override
  Future<DispatchResult> dispatchWithContext(int interfaceId, int methodId, RpcPayload params, {
    List<Capability> paramsCapabilities = const [],
    DispatchContext? context,
  }) async {
    final dispatchContext = context ?? DispatchContext.neverCanceled;
    switch (interfaceId) {
      case 0xd41d8cd98f00b204:
        switch (methodId) {
          case 0:
            final p = params.getTyped(greeterGreetParamsFactory, capabilities: paramsCapabilities);
            return await greetWithContext(p, paramsCapabilities, dispatchContext);
          case 1:
            final p = params.getTyped(greeterNewSessionParamsFactory, capabilities: paramsCapabilities);
            return await newSessionWithContext(p, paramsCapabilities, dispatchContext);
          default:
            break;
        }
      default:
        break;
    }
    return super.dispatchWithContext(interfaceId, methodId, params, paramsCapabilities: paramsCapabilities, context: dispatchContext);
  }

  @override
  Future<void> dispose() async {}
}

